### ISSUE TITLE
A List of Variables Used By Ion Shell

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#104]
### Implemented
- **?**:  Displays the last command's exit code
- **DIRECTORY_STACK_SIZE**: Defines the maximum size of the internal directory stack buffer
- **HISTORY_SIZE**: Defines the maximum size of the internal history buffer
- **HISTORY_FILE**: If set to 1, enables writing a history log to disk
- **HISTORY_FILE_SIZE**: Defines the maximum amount of commands to retain in the log
- **HOME**: Displays the current user's home directory
- **OLDPWD**: Displays the previous working directory
- **PWD**: Displays the current working directory
- **PROMPT**: Contains the Shell Prompt
- **USER**: Displays the current user
### Not Implemented

???

**Comment by skylerberg** [comment]
For now here are the ones that would be helpful for tuning the shell:

- [ ] PROMPT
- [ ] DIRECTORY_STACK_SIZE
- [ ] HISTORY_SIZE
- [ ] HISTORY_FILE (Requires writing history to files)

At this point it is not important whether or not we go with Bash, fish, or our own conventions. This is an easy change in the future. We should just do what makes sense or if we have no strong opinion go with what bash does. Before we go 1.0.0 (a long time from now) we should go through and make sure that everything fits with the design goals. To that end I am starting to think of what the overarching design goals should be. At some point I will write them down for input from everyone else. Also, anyone else is welcome to contribute ideas.

Let's add more variables to this list as people think of them.

**Comment by mmstick** [comment]
I'm currently making good progress on rewriting Ion to make use of variables. In doing so, history can now be logged to a file at **~/.ion_history.log** as the default location for logging history. I have currently implemented the following variables:

- DIRECTORY_STACK_SIZE
- HISTORY_FILE
- HISTORY_FILE_ENABLED
- HISTORY_SIZE
- CWD

I may upload a pull request within the next 24 hours with the changes.

**Comment by skylerberg** [comment]
@mmstick Awesome!

**Comment by skylerberg** [comment]
Add a link to https://github.com/redox-os/ion/issues/46 so that I remember to close it at the same time as this.

**Comment by mmstick** [comment]
Pull request has been submitted: https://github.com/redox-os/ion/pull/116/

**Comment by mmstick** [comment]
Three additional variables that might be useful to have are

- USER: displays the current user's username
- UID: display the UID of the current user
- GID: display the GID of the current user

**Comment by skylerberg** [comment]
Do other shells do this? I am wondering what the advantage over something like `whoami` is.

**Comment by mmstick** [comment]
Bash does indeed do this, although I suppose the `id` and `whoami` commands cover the functionality in general if the shell doesn't support it.

**Comment by mmstick** [comment]
I'll be updating the original post with implemented variables.

**Comment by GlenDC** [comment]
Both `$USER` and `$HOME` also seem to be supported by default.

**Comment by fbruetting** [comment]
@mmstick Why does Ion and all other shells save their config files in ~ directly, and not in .config/ or .local/ like almost all other programs? Sorry if this question is nooby, but I wondered why this is since… ever. ;)

**Comment by mmstick** [comment]
Basically, it is planned to do this, but no one has written the code to do
this yet.
