### ISSUE TITLE
Add history expansion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#109]
For examples of history expansion in bash: http://www.thegeekstuff.com/2011/08/bash-history-expansion/.

**Comment by nounoursheureux** [comment]
Also, when the user hits the Up key it should fill the prompt with the previous command.

**Comment by skylerberg** [comment]
@nounoursheureux Yeah, that is something that would be REALLY nice to have. Unfortunately it will not be trivial. Here is a related issue: https://github.com/redox-os/ion/issues/3.

**Comment by skylerberg** [comment]
The issue is that we need to start processing character by character instead of using the readline function. To read character by character we need to set the terminal in raw mode and we need to do this in a way that works on both linux and redox. I don't know what that will entail as I have not looked into it yet. It will be very important in the future though because we will definitely need our own line editor.

**Comment by skylerberg** [comment]
https://www.gnu.org/software/bash/manual/html_node/Event-Designators.html#Event-Designators

**Comment by skylerberg** [comment]
https://www.gnu.org/software/bash/manual/html_node/Word-Designators.html#Word-Designators

**Comment by skylerberg** [comment]
https://www.gnu.org/software/bash/manual/html_node/Modifiers.html#Modifiers

**Comment by mmstick** [comment]
Closing because this is implemented [here](https://github.com/redox-os/ion/blob/master/src/shell/binary/designators.rs). It's implemented within the REPL codepath, after obtaining a line from liner. The line is scanned for designators, and supplied command is modified accordingly as they are found.
