### ISSUE TITLE
Remove unneeded commands

### ISSUE THREAD

**Issue by hauleth** [redox-os/ion#11]
There is bunch of entries in commands that should not exist:

- `cat`
- `free`
- `ls`
- `mkdir`
- `poweroff`
- `ps`
- `rm`
- `rmdir`
- `run`
- `sleep`

All of them should be external commands. @jackpot51 could you create repo `redox-os/coreutils` where all of that should land?

**Comment by faizaanceg** [comment]
Agreed. BTW is `poweroff` better off being termed as `shutdown` ? 


P.S. New here. Interesting project. Hope to start contributing soon.

**Comment by Ticki** [comment]
Yeah. Poweroff is misleading.

**Comment by skylerberg** [comment]
It may be worth looking at an existing effort to make a Rust-based rewrite of coreutils: https://github.com/uutils/coreutils.

**Comment by hauleth** [comment]
Yeah, but they are trying to replicate GNU coreutils, I want Redox coreutils to be based on BSD one. They are simpler and less bloated. 

--
Łukasz Jan Niemier

Dnia 30 gru 2015 o godz. 21:01 Skyler Berg <notifications@github.com> napisał(a):

**Comment by Ticki** [comment]
I ported a big part of coreutils to Redox a while ago. Should be in the git history (before `ports` were deleted).

**Comment by skylerberg** [comment]
Done https://github.com/redox-os/ion/pull/28.
