### ISSUE TITLE
Add piping for builtin commands

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#113]
They should all ignore stdin for now, but they should have an stdout and stderr that can be piped into processes.

**Comment by skylerberg** [comment]
https://github.com/redox-os/ion/pull/120 does not address this. I think this will be about the same level of difficulty or possibly more difficult than implementing piping was in the first place.

**Comment by mmstick** [comment]
This has been implemented. It was actually very trivial to implement.
