### ISSUE TITLE
Add a manual

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#115]
We should add a manual. This could be manpages like http://linux.die.net/man/1/zsh. It could also be something like https://www.gnu.org/software/bash/manual/bashref.html.

**Comment by GlenDC** [comment]
Ion seems to be part of http://doc.redox-os.org/book/userspace/ion/ion.html, even though it is incomplete. So this might be the place where we can add high level (e.g. syntax), low level (how do this work exactly) and other info (what's the difference with bash).
