### ISSUE TITLE
`cat` is wrong

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#12]
`cat` is not "print this file", it's "concatenate these strings". The former usage of cat is wrong. For "print this file" in POSIXs, one use "< file".

**Comment by hauleth** [comment]
It is concatenate these files, not strings. Still this should be external tool, not builtin.

**Comment by Ticki** [comment]
@hauleth The actual implementation in GNU coretools is: if the input is `-` read from stdin until EOF, else check if a file of the name exist, if not print an error to stderr. The problem, however, is that cat does not lock the files it's reading.

**Comment by hauleth** [comment]
This is Unix tool and IIRC this is standard definition. I have written simple Unixy `cat` command (25 LOC) already and if @jackpot51 give me repo for that I will push it there.

**Comment by Ticki** [comment]
Right, it's described in SUS. All I'm saying is that the currently implementation is incorrect (it's UUOC, essentially).

**Comment by Ticki** [comment]
redox-os/coreutils

**Comment by jackpot51** [comment]
The repo is created, @hauleth is admin

**Comment by Ticki** [comment]
k.

**Comment by skylerberg** [comment]
We need to change ion to check on a path and execute commands if the supplied command is not a builtin. For ion this basically means making `exec` the default. When I say `exec`, I am specifically referring to our `exec`, not what `exec` is actually supposed to do.

**Comment by skylerberg** [comment]
`cat` is no longer a part of ion https://github.com/redox-os/ion/pull/28.
