### ISSUE TITLE
Variable expansion should always try to expand as long a string as possible

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#124]
There is a bug right now when using two variables in which one is a prefix of the other. To illustrate
```
> let var = abc
> let variable = def
> echo $var$variable
abcabciable
```
When `$var` is expanded it expands the first part of `$variable` as well.

**Comment by nounoursheureux** [comment]
I think my pull requests fixed this issue.

**Comment by skylerberg** [comment]
Just tested and it looks good. Thanks!
