### ISSUE TITLE
Special variable `?` no longer expands

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#125]
I didn't realize this until after merging https://github.com/redox-os/ion/pull/122, but since it only checks for alphanumeric and underscore it will not expand when you try `$?`.

**Comment by nounoursheureux** [comment]
Sorry, I'm gonna fix that. While we are at it, what should and what should not be allowed in a variable name ?

**Comment by skylerberg** [comment]
Let's make a utility function in `variables.rs` that checks if a character is a valid variable character. For now we should make it alphanumeric, underscore, and question mark. Then we can add more characters as we need them. I don't have a strong opinion on what should and should not be allowed.

**Comment by skylerberg** [comment]
Related https://github.com/redox-os/ion/issues/127.
