### ISSUE TITLE
Reorganize how commands are executed

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#13]
The system is currently very monolithic. Commands shouldn't be hard coded in the shell.

**Comment by skylerberg** [comment]
Agreed, however, some commands are supposed to be built into the shell, e.g., `cd`. When running  commands we should check to see if they are builtins. if so, use an appropriate function for the builtin. If not, search a path for an executable of the same name as the command.

**Comment by Ticki** [comment]
> Agreed, however, some commands are supposed to be built into the shell, e.g., cd

Yeah, alias, cd, export and so on.

**Comment by hauleth** [comment]
And very important one: `command` that will skip any builtins that conflicts with executables in `$PATH` (i.e. bash `time`).

**Comment by skylerberg** [comment]
We have moved all of the commands that shouldn't be in the shell out. Yay!
