### ISSUE TITLE
Add heredocs

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#132]
```
cat <<EOF
some
stuff
EOF
```

**Comment by mgmoens** [comment]
Can someone tell me where |, > etc. are parsed? I'd like to try this if I know where those special characters get parsed. I've been looking around in the shell folder, but I think I'm looking to deep in the rabbit hole.

**Comment by mmstick** [comment]
They are parsed [here](https://github.com/redox-os/ion/blob/master/src/parser/pipelines.rs#L198) and [here](https://github.com/redox-os/ion/blob/master/src/parser/pipelines.rs#L172) in the pipelines module. At some point, I'd like to rewrite this module. Haven't gotten around to it though.

**Comment by mmstick** [comment]
I'll have heredocs implemented in a few minutes.
