### ISSUE TITLE
Make redirection work with stderr

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#135]
There is no way to redirect stderr currently

**Comment by mmstick** [comment]
What syntax do we want here? Currently, I have this in mind:

- Pipe Stderr: `command ^| other_command`
- Pipe Stderr+Stdout: `command &| other_command`
- Redirect Stderr: `command ^> file`
- Redirect Stderr+Stdout: `command &> file`

The other variant is:

- Pipe Stderr: `command 2| other_command`
- Pipe Stderr+Stdout: `command &| other_command`
- Redirect Stderr: `command 2> file`
- Redirect Stderr+Stdout: `command &> file`

**Comment by jackpot51** [comment]
Good question. I like the idea you have about `^`. Would `|` and `>` still be used for stdout only?

**Comment by mmstick** [comment]
The `|` and `>` operators would be used for stdout only.

**Comment by polymetric1** [comment]
Personally I like `^|` because it doesn't imply that stdout only is `1|`

**Comment by mmstick** [comment]
I'll start working on this soon. I'll go for the `^|`/`^>` syntax for stderr and `&|`/`&>` for stderr + stdout.

**Comment by mmstick** [comment]
Almost finished with this work. I should have it pushed later today.

**Comment by mmstick** [comment]
This is complete and the work has been pushed. You may use `^>` to redirect stderr and `&>` to redirect stderr and stdout.
