### ISSUE TITLE
Print helpful messages when redirection fails

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#138]
Currently when something goes wrong during io redirection ion will just silently ignore it. It should  say something went wrong.

**Comment by skylerberg** [comment]
Here are the if-statements that should have an else statement with a helpful message:
https://github.com/redox-os/ion/blob/master/src/pipe.rs#L12
https://github.com/redox-os/ion/blob/master/src/pipe.rs#L18

The easiest way I can think to test this out while developing it is to try to redirect from or into a file that you do not have permission to read/write. This should cause the file io operation to fail.

**Comment by jackpot51** [comment]
Please do this, I need to see the errors in Redox as piping to a file does not work!

**Comment by jackpot51** [comment]
Oops, meant to say fixes
