### ISSUE TITLE
Unable to compile ion from sources

### ISSUE THREAD

**Issue by koyedele** [redox-os/ion#139]
I have the latest sources (commit id: 7dca7518b30a7e785ea5ff3335e24584d8818ce0) and I'm unable to compile ion. 
Here's the error
`
/Users/kunle/.cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/peg_syntax_ext.rs:1:1: 1:66 error: #[feature] may not be used on the stable release channel
/Users/kunle/.cargo/git/checkouts/rust-peg-bb4e2b887d852aec/libsyntax-changes-again/src/peg_syntax_ext.rs:1 #![feature(plugin_registrar, quote, rustc_private, box_patterns)]
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
`

**Comment by skylerberg** [comment]
Are you running on the latest nightly?

**Comment by koyedele** [comment]
latest nightly of ion, or of cargo?

**Comment by skylerberg** [comment]
Cargo/rustc

**Comment by koyedele** [comment]
No I don't think so. My cargo version is: cargo 0.9.0 (8fc3fd8 2016-02-29)

**Comment by koyedele** [comment]
Should I upgrade to the latest nightly?

**Comment by skylerberg** [comment]
We run on the nightly releases of rust for redox because we use features that are not marked stable yet for most of our projects.

https://www.rust-lang.org/downloads.html.

Upgrading should fix the issue.

**Comment by koyedele** [comment]
Thanks! I'll give that a try.

**Comment by skylerberg** [comment]
If the issue persists then I will reopen this.

Good luck, have fun :)
