### ISSUE TITLE
Raw mode is available

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#140]
I added it yesterday to `terminal`.

**Comment by Ticki** [comment]
ticki/libterm supports Redox now.

**Comment by skylerberg** [comment]
So I can use ticki/libterm to change Redox or Linux into or out of raw mode?

**Comment by Ticki** [comment]
Yes.

**Comment by skylerberg** [comment]
That is great!

**Comment by skylerberg** [comment]
This will let use move forward on https://github.com/redox-os/ion/issues/3 in the future.
