### ISSUE TITLE
Quotes after the start of an argument

### ISSUE THREAD

**Issue by jackpot51** [redox-os/ion#143]
`let something="a string"` will set something to `"astring"`, with the quotes included, and no space
`echo something="a string"` will print `something="a  string"`, with an additional space (not visible due to github formatting)
Ideally, `sometext"some other text"` would be processed as a single argument `sometestsome other text`

**Comment by skylerberg** [comment]
Thanks for reporting. I will have to take a look at how to integrate this into the grammar.

**Comment by mmstick** [comment]
I have a fix for this which I am working on. I'll submit it soon.

**Comment by mmstick** [comment]
This is now fixed
