### ISSUE TITLE
Popd and Pushd (directory stack)

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#15]

**Comment by skylerberg** [comment]
Yep, these are builtins we should definitely add.

**Comment by skylerberg** [comment]
We could make `cd`  basically do what `pushd` does. What if navigation always created a directory stack? The only downside I could think of is that the directory stack could grow to large if a script used `cd` excessively.

**Comment by Ticki** [comment]
@skylerberg It actually already does. Cd push to the dir stack.j

**Comment by skylerberg** [comment]
@Ticki I just played around with `pushd` and `popd` in bash, zsh, and fish. In zsh, cd does push to the dir stack. In the other two it does not. I like the idea that cd acts like `pushd`; I think zsh got this right.

However, there is a quirk to zsh's implementation that I think is *really* bad. Zsh appears to disallow duplicate items in the directory stack and will go so far as to reorder the stack if you switch to a directory previous on the stack. I.e., if you have the stack `a b c d` and you do `cd c` you will get the following stack `c a b d`. I think this is a nonsense and it should give you `c a b c d`.

**Comment by skylerberg** [comment]
https://github.com/redox-os/ion/pull/27 add directory stack. Currently `cd` does nothing with the directory stack (like in fish, bash, sh, and csh). This can easily be changed any time.
