### ISSUE TITLE
Add brace expansion to Ion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#150]
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html

**Comment by ElijahCaine** [comment]
Hey @skylerberg I'd like to help out with Ion by working on this issue. Is there a good reference for `ion`s design and maybe some suggested docs to get started working on issues like this?

**Comment by nounoursheureux** [comment]
I don't think we have references for ion's design, so if you have any questions don't hesitate to ask. The code for string expansion is currently located in the [`Variables::expand_string`](https://github.com/redox-os/ion/blob/85ad6ba4c1043762205cfc8a4635cfe7a3aca789/src/variables.rs#L195) method. From there you can do two things:
* Add a `brace_expansion` function that loops through a string, does braces expansion as shown [here](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_04.html) on the string and returns the new string; and then call this function after [this line](https://github.com/redox-os/ion/blob/85ad6ba4c1043762205cfc8a4635cfe7a3aca789/src/variables.rs#L197)
* Or you can try to integrate brace expansion into the [variable expansion loop](https://github.com/redox-os/ion/blob/85ad6ba4c1043762205cfc8a4635cfe7a3aca789/src/variables.rs#L199). It would give better performance as we wouldn't have to loop multiple times over the same string, but it would require you to rewrite both the variable expansion and the brace expansion code.

Also, it would be better to implement brace expansion without using regular expressions, as they are not currently supported on Redox. Again, if you have any question don't hesitate to ask :smiley:

**Comment by skylerberg** [comment]
Thanks, @nounoursheureux! All that information is spot on.

@ElijahCaine, welcome to the project! :)

**Comment by ElijahCaine** [comment]
@nounoursheureux thank you so much for the information! When I get some work in on this I will definitely keep you up to date @skylerberg. I won't promise any code soon with school sucking up a lot of my free time, but I'll do my best.

I'm excited to contribute and can't wait to get started :smile: .

**Comment by mmstick** [comment]
@ElijahCaine Do you still plan to work on this feature? If not, I can quickly implement this feature.

**Comment by mmstick** [comment]
I've an implementation that combines brace expansion with variable expansion. I'll have a pull request uploaded shortly.

**Comment by mmstick** [comment]
This should be marked as complete as this was merged: https://github.com/redox-os/ion/commit/d0a2e0a224bc1c57718d58b7b2d1cd8d1c80d052

**Comment by jackpot51** [comment]
Thanks!

**Comment by ElijahCaine** [comment]
Thanks for implementing this.  I got pulled away by other projects.  Glad it got merged.

**Comment by mmstick** [comment]
I'll soon be working on improving it by eliminating as much heap allocations as possible by creating a tokenizer that will slice the string at all key indices. However, that may be a week or two as family is currently visiting from Arkansas this week.

**Comment by mmstick** [comment]
Now beginning work on eliminating all the usages of vectors in my implementation. It's fairly close to being finished. The only heap allocations in use will be the string that is generated from the entire process, and a vector of tokens that is returned from the expansion tokenizer. It should be a fair amount faster than what's currently in use.

**Comment by mmstick** [comment]
Had to get a new laptop configured as my previous one bit the dust, but I'm deciding to expand the functionality of our brace expansion with my new implementation which will support variables inside braces, and permutating braces when there's more than one, all the while still aiming for absolute performance and minimal heap allocations. There will be a ton of added test cases once I'm complete.

**Comment by mmstick** [comment]
I'll have a pretty good pull request to make soon. I got a bit sidetracked, and I've rewritten it a couple times, but I'm almost finished with implementing a vastly superior version of brace/variable expansion, where I try to create and use Iterators as much as possible. Here's a sneak peek of what the new code will look like, taken from a submodule named `shell_expand`

```rust
pub fn expand_string<T, V>(original: &str, tilde_fn: T, variable_fn: V) -> String
    where T: Fn(String) -> String,
          V: Fn(&str)   -> Option<String>,
{
    let mut output = String::with_capacity(original.len() >> 1);
    for word in WordIterator::new(original) {
        match word {
            WordToken::Normal(text) => {
                output.push_str(&text)
            },
            WordToken::Tilde(text) => {
                output.push_str(&tilde_fn(text));
            }
            WordToken::Variable(text) => {
                variables::expand(&mut output, text, |variable| variable_fn(variable));
            },
            WordToken::Brace(text, contains_variables) => {
                if contains_variables {
                    let mut temp = String::new();
                    variables::expand(&mut temp, text, |variable| variable_fn(variable));
                    output.push_str(&braces::expand_braces(temp));
                } else {
                    output.push_str(&braces::expand_braces(text));
                }
            }
        }
    }
    output
}
```

The function will be called by the existing function in variables.rs like so:

```rust
    pub fn expand_string<'a>(&'a self, original: &'a str, dir_stack: &DirectoryStack) -> String {
        let tilde_fn    = |tilde: String | self.tilde_expansion(tilde, dir_stack);
        let variable_fn = |variable: &str| self.get_var(variable);
        shell_expand::expand_string(original, tilde_fn, variable_fn)
    }
```
