### ISSUE TITLE
Make tilde expansion work for other users' home directories

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#155]
`~foo` should expand to the home directory for a user called `foo`.

**Comment by mmstick** [comment]
Should we use the getent command on UNIX systems for obtaining a list of user IDs and initializing their values during the init phase? Or should we get the values from the passwd file directly (has issues with LDAP systems)?

**Comment by skylerberg** [comment]
We should probably not get them from the passwd file directly, if possible. I am not sure what the best approach for solving this is.

**Comment by mmstick** [comment]
The best approach will be conditional compilation for each supported platform. Obtaining the information from getent is the best solution for NIX systems.

**Comment by mmstick** [comment]
@MovingtoMars Do you still plan on pursuing implementing tilde expansion for other users?

**Comment by MovingtoMars** [comment]
Well I have an open pull request, but it seems no-one has looked at it in so long that it's out-of-date now. I'll rebase it soon.

**Comment by jackpot51** [comment]
Thanks @MovingtoMars!
