### ISSUE TITLE
Executing commands on PATH by default.

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#16]
Instead of having `exec` spawn a subprocess we should use that logic when the user enters a non-builtin command. For the sake of usability on redox we need to make sure that it uses PATH properly to find commands on the system.

Once we do this, we will be able to a remove all the commands we have that should not be builtins. We will also be able to to add more commands into redox by putting them wherever the equivalent of /bin ends up.

**Comment by skylerberg** [comment]
I just merged a change that makes the shell run external commands by default. Now we just need to go into redox and make sure that environment variables work, that coreutils is on PATH, and that all the commands we need are in coreutils. Once that is complete we can remove all the unneeded commands from Ion, which will be a great relief to me.

**Comment by Ticki** [comment]
Cool.

**Comment by polymetric1** [comment]
Nice. I'll get the builtins working with coreutils.

**Comment by skylerberg** [comment]
@jackpot51 Fixed this in redox, I think.
