### ISSUE TITLE
Add process expansion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#167]
In shells like Bash you can use backticks or `$()` to run a process in a subshell and then use it's output in the place where you used process substitution. We should support this and we should not use the backtick syntax. Instead we should use either `$()` or just parens `()`.

**Comment by mmstick** [comment]
I will look into implementing this feature using the `$()` syntax. I think it's at least important that Redox has a shell that has support for a POSIX-syntax mode.

**Comment by mmstick** [comment]
Updating to say that I have process expansion functionality in working, I'm just currently blocked by needing to find a way to get the output from the standard output of the subprocess.

**Comment by jackpot51** [comment]
I have been working on this here: https://github.com/redox-os/ion/tree/process_expansion

The problem right now is that the peg parser will break `$(command args)` into `$(command` and `args)` unless it is quoted like `"$(command args)"`

**Comment by mmstick** [comment]
I'm looking into that right now. I have a number of changes to make to the **shell_expand** module as well as **variables.rs**.

**Comment by jackpot51** [comment]
Thanks!
