### ISSUE TITLE
loss of spaces in specific use cases of a `let` assignment

### ISSUE THREAD

**Issue by GlenDC** [redox-os/ion#194]
**Reproduction**: run any of the following commands:
+ `let countdown="One, two, three... Go!"; echo $countdown`
+ `let countdown ="One, two, three... Go!"; echo $countdown`

**Expected behavior**: stdout: `One, two, three... Go!`

**Actual behavior**: stdout: `One,two,three...Go!`

**Build information**: 
+ `rustc -V`: `rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)`
+ `git rev-parse HEAD`: `852a1170487053f4f6f29a5b2647e68fd4e78a21`

**Comment by GlenDC** [comment]
Sorry, this might be related or a duplicate of issue #143

**Comment by mmstick** [comment]
It is a duplicate. There's an issue with the peg parser whereby you need to have a space after `=` otherwise it won't correctly parse what follows next.

**Comment by mmstick** [comment]
I'll have this fixed soon.

**Comment by mmstick** [comment]
You'll find that this issue is fixed now.
