### ISSUE TITLE
Error about pipe "|"

### ISSUE THREAD

**Issue by watafalk** [redox-os/ion#207]
**Reproduction**:  ls|cat

**Expected behavior**: print the content of "ls" command

**Actual behavior**: it shows `ion: command not found: ls|cat`

**Build information**: https://github.com/redox-os/redox/releases/download/0.0.3/livedisk.iso

---

Because it requires space before the pipe symbol.

Another problem: `wtf | wtf|wtf`

Error:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', rust/src/libcollections/vec.rs:1362
   0: 0x0 - <unknown>
```

![2016-12](https://cloud.githubusercontent.com/assets/14152973/20827405/b567019e-b8ac-11e6-8dcc-b15c0136b416.png)

**Comment by mmstick** [comment]
I'll have it fixed in pretty much no time, with added unit tests to account for spaceless piping.

**Comment by mmstick** [comment]
I've fixed it, so I'll be uploading a pull request soon with the fix.

**Comment by jackpot51** [comment]
@mmstick thanks!
