### ISSUE TITLE
macOS: left arrow doesn't work

### ISSUE THREAD

**Issue by vors** [redox-os/ion#209]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
On macOS,

```
cargo run
```

Then type anything and try to use left arrow

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

left arrow works

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

left arrrow doesn't work

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

```
rustc 1.16.0-nightly (4ecc85beb 2016-12-28)
```

**Comment by mmstick** [comment]
Does this still apply today?

**Comment by GungnirInd** [comment]
I can't reproduce this with current master on macOS 10.12.4; all arrow keys work as expected.

**Comment by mmstick** [comment]
@vors Is it okay with you if I close this issue now?

**Comment by vors** [comment]
Sure!

**Comment by vors** [comment]
Hm, turned out the problem was in the fact that I run Ion from [PowerShell](https://github.com/PowerShell/PowerShell). From bash it works just fine.
