### ISSUE TITLE
Discussion: Variable scoping (do we really need export)

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#21]
I have what may be a radical, and possibly bad idea: export everything.

I think having two different classes of variables is an unnecessary complication that adds unneeded state to the shell. What if we just used the environment for everything?

Pros:
 - Simplicity in the shell application
 - Less state moving around the application
 - Easier to learn

Cons:
 - Performance: Needs to interact with the OS for variable assignments.
 - Data leaking: Sending data to child processes that do not need it.

**Comment by Ticki** [comment]
Scoping is great for a lot of things. It will help preventing a number of bugs (such as memory leaks), and security issues. :+1:

**Comment by skylerberg** [comment]
Yeah, we are going to need to scope which variables are exported. I wish it could be simplified, but oh well.
