### ISSUE TITLE
Readme and design goals

### ISSUE THREAD

**Issue by vors** [redox-os/ion#210]
Hello,

I'm interested in shells in general and recently started learned rust.
I played around with ion a little bit.
I'd like to gain some context about this project.
I.e. what are the design goals? What a non-goals?
It seems that POSIX-compatibility is non-goal for example.

Would love to see some elaborate text about it in the README, if possible.

Regards,
-Sergei

**Comment by msehnout** [comment]
I can see that this issue is quite old, but I also think that Ion should have some sort of design documents, so contributors know what to do. What do you think @skylerberg, @jackpot51, @mmstick ?

**Comment by mmstick** [comment]
Basically, any area where you think Ion could use some improvement, you're free to work on that. If you have some ideas then you're free to propose them. Pick a feature and implement it.

**Comment by mmstick** [comment]
@msehnout I've created a few issues that covers some areas where Ion is currently lacking. In the coming week I'll try and write documentation for each and every function, and provide a **README.md** for each module. Maybe even adding a few TODOs in the source code to highlight areas that could use improvement.

**Comment by mmstick** [comment]
@vors Overall, the main goal of Ion is to be a capable shell on all platforms, in addition to being the default shell for Redox. Pretty much nothing is POSIX-compliant these days as standards have evolved over time. Ion should be a modern take on what a shell should be for the modern day, taking inspiration from other existing shells, such as bash and fish -- probably more influence from bash with just a dash of fish. If there is a feature that you'd like to have within a shell that other shells do not have, you're free to propose your ideas here and I might implement them.

The documentation needs to be updated to reflect current shell syntax though.

### While Loops

```fish
while true; echo one; sleep 1; end
while $var; echo one; sleep 1; end
while $(echo $(echo true)); echo one; sleep 1; end
```

### For Loops

```fish
for i in 1...10; echo $i; end
for i in 1..11; echo $i; end
for i in $(seq 1 10); echo $1; end
for i in a b c d; echo $i; end
```

### Subshells

```fish
echo $(echo one $(echo two # three) four # five)
```

### If Conditional

```fish
if $a == $b; echo true; end
```

### Shell Expansion

```fish
echo 123{a,b,c}456{g,h,i}
echo $var
echo ${var}
echo $(echo $var)
```

**Comment by msehnout** [comment]
@mmstick Good work! I don't have much time now, but I'd like to implement the fish-like autocompletion in liner, so it can be used on Redox.

**Comment by vors** [comment]
@mmstick good, thank you for the response!

**Comment by mmstick** [comment]
@vors @msehnout Major changes have happened to the flow control logic, so we could use some testers to try out Ion and report any issues discovered.

**Comment by msehnout** [comment]
@mmstick So far I only came across this issue, but I'm not sure if it's related to your current work: for instance when I run a while loop and want to stop it with Ctrl+C, I'd expect it to return me back to the running shell instance, but it terminates the whole session.
```txt
~/r/ion (master|…) $ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/ion`
msehnout:/home/redox/ion# while true
    echo one
    sleep 1
    end
one
one
^C⏎
~/r/ion (master|…) $ 

```

**Comment by mmstick** [comment]
@vors So the problem here is that Ion does not have a means of capturing signals. It's never worked before. Issue #85

**Comment by jeandudey** [comment]
@msehnout it happens too when you close a program with Ctrl+C

**Comment by vors** [comment]
I see you added info to the readme, awesome!
