### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by jeandudey** [redox-os/ion#215]
Will command aliases be supported?

**Comment by jeandudey** [comment]
About that, trying to workaround this with `fn` gives this bug:

#### Example
```
fn ls
ls --color
end
```
in shell:
```
ion:/home/jeandudey/# ls
This function takes 0 arguments, but you provided 1
```

I don't know if this is a bug, or a intentional feature (recursiveness?).

**Comment by msehnout** [comment]
I think the intention is to use functions for this purpose.

```txt
ion:/# ll
ion: command not found: ll
ion:/# fn ll
fn> ls -l
fn> end
ion:/# ll
total 20
...
```

**Comment by mmstick** [comment]
The `alias` command simply hasn't been implemented yet. You're free to implement it if you want though.

**Comment by mmstick** [comment]
I'm working on this at the moment.

**Comment by mmstick** [comment]
I'm halfway through implementing this. Syntax will expand upon the existing `let` functionality by adding a new `alias` keyword to define that the following binding will be an alias binding versus a variable binding.

```sh
let alias ls = 'ls --color'
```

**Comment by mmstick** [comment]
This can be closed now. You can write aliases like so:

```sh
alias ls = 'ls --color'
ls -l
```

**Comment by jackpot51** [comment]
@mmstick I also added `unalias`
