### ISSUE TITLE
Allow numeric calculations through command line input.

### ISSUE THREAD

**Issue by ticki** [redox-os/ion#22]
A thing I wished other shells had:

```
$ 1 + 2
3
$ 2*3
6
$ 4 /2
2
```

**Comment by hauleth** [comment]
I would rather use NPN instead.

**Comment by jackpot51** [comment]
This should really be a command, like expr:

`expr 2 + 3`

**Comment by jackpot51** [comment]
If you want NPN you can also have a command for that

**Comment by Ticki** [comment]
@hauleth No, please not. NPN is the most horrible piece of notation ever created.

**Comment by Ticki** [comment]
@jackpot51 Why a command? Why not just these operators build in to Ion?

**Comment by jackpot51** [comment]
I don't like NPN but I see no problem with having a command that handles it

`npn + 2 3`

**Comment by Ticki** [comment]
> I don't like NPN but I see no problem with having a command that handles it

Me neither. But I really dislike the idea of it being default.

**Comment by jackpot51** [comment]
Then variable assignments would still work for ion, replacing $() with whatever our inline command syntax is

`variable=$(npn + 2 3)` or `variable=$(expr 2 + 3)`. Since they are external commands, you get to choose what is installed by default

**Comment by Ticki** [comment]
If it was built in, one could do:

```
var = 2 + 3;
```

**Comment by Ticki** [comment]
Personally, I dislike the idea of shell scripting being so foreign. I would much rather have it feel like a modern dynamic language.

**Comment by jackpot51** [comment]
I would like PR's to be done showing the proposed syntax in https://github.com/redox-os/ion/blob/master/SYNTAX.md

To start, I described the current ion syntax

This way we could keep track of proposed changes

**Comment by Ticki** [comment]
I'll make a grammar proposal.

**Comment by skylerberg** [comment]
I like this idea a lot. Right now my workflow for doing this is to open a shell and open a python shell inside that shell then do some calculations.

However, we have to consider the implications of this change: strings matching something like `[0-9+-/*]+` would no longer be valid command names.

**Comment by Ticki** [comment]
I use python for calculations too, but I'd really see this to be integrated into a sane shell scripting language.

**Comment by Ticki** [comment]
Also, on the string matching, you can just restrict these characters to literals.

**Comment by mmstick** [comment]
What if were to do as the `fish` shell does and provide a built-in `math` command?
