### ISSUE TITLE
Optional Descriptions for Functions

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#232]
The fish shell allows defining a description for each function created, and I think it'd be a good idea to also support that here.

```fish
fn name_of_function arg1 arg2 --description 'description of function'
    ...
end
```

**Comment by Maaarcocr** [comment]
I would like to help on this, would it be possible to have a bit more information about this? (For example, the code that should be changed).

**Comment by mmstick** [comment]
A description field needs to be added [here](https://github.com/redox-os/ion/blob/master/src/flow_control.rs#L32), parsed [here](https://github.com/redox-os/ion/blob/master/src/parser/grammar.rustpeg#L73), and then displayed [here](https://github.com/redox-os/ion/blob/master/src/builtins/functions.rs#L6).

**Comment by Maaarcocr** [comment]
Any ideas on the grammar? I feel like the approach used for fish would look a bit weird.
Maybe something like a documentation comment straight before the function declaration? Or maybe at the end of it?

**Comment by mmstick** [comment]
Thanks. Closing this now.
