### ISSUE TITLE
Arithmetic Expressions

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#243]
In the future, it should be possible to perform arithmetic by containing such expressions within `$((...))`, such as how Bash performs it. As an example:

```bash
let result = $(( ($x * $y) * 2 ))
```

**Comment by andychu** [comment]
BTW POSIX shell and bash have a pseudo-experssion mode where you can just do:

`$(( (x * y) * 2 ))`

that is leave off the sigils.

**Comment by mmstick** [comment]
Closing duplicate issue
