### ISSUE TITLE
Brace Ranges

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#244]
We should enhance the existing brace expansion logic to be capable of expanding to ranges of letters / numbers. However, we should probably rewrite it to handle multiple levels of braces.

```bash
$ echo {0..5}
0 1 2 3 4 5

$ echo {a..d}
a b c d
```

**Comment by andychu** [comment]
FWIW I just implemented this for Oil, and talk extensively about it here:

http://lists.oilshell.org/pipermail/oil-dev-oilshell.org/2017-March/000034.html

http://lists.oilshell.org/pipermail/oil-dev-oilshell.org/2017-March/000035.html

There is a tiny implementation in Python in core/braces.py in the Oil repo.

I'm not sure how interested you are in all the reverse-engineering stuff, but I thought it was interesting that there are 3 features:

- `{foo,bar}`
- `{0..5..2}`
- `{a..d..2}`

And dash supports 0, mksh supports 1, zsh supports 2, and bash supports all 3.

**Comment by mmstick** [comment]
I'll be working on this soon, along with a rewrite of the existing brace parsing logic to handle multiple levels of braces, and the removal of error checks here in the expansion module as they will no longer be possible, due to catching syntax errors in the StatementSplitter iterator now.

**Comment by mmstick** [comment]
Closing as this issue will be tracked in issue #254

**Comment by mmstick** [comment]
This is now implemented
