### ISSUE TITLE
Substrings & Arrays

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#245]
### Create an Array
```ion
let array = [ 'one two' 'three four' five six seven ]
```

### Convert an Array into a String
```ion
let as_string = $join(array, ' ')
let as_string = @array
```

### Convert a String into an Array

```ion
let as_array = @split(as_string, ' ')
```

### Take the First Value from an Array
```ion
let first_value = @array[0]
```

### Copy an Array
```ion
let copy array = [ @array ]
```

### Convert Command Output into an Array
```ion
for i in @[echo one two three]
    echo $i
end
```

**Comment by suhr** [comment]
`echo ${var[3]}`

I disagree. Lists (arrays) should be first-class citizens, there's literally no reason to imitate BASH-like semantics.

**Comment by mmstick** [comment]
@suhr Have any syntax examples?

**Comment by suhr** [comment]
Sure: http://www.oilshell.org/blog/2016/11/06.html and http://www.oilshell.org/blog/2017/02/05.html.

So in oil, the third example will be `echo @split(var)[3]`. In rc or es, it will *probably* be

```
x=`{echo $var} $x(4)
```

I like short and explicit approach of oil.

**Comment by mmstick** [comment]
@suhr We can try for implementing that and other ideas. Will need some serious brainstorming though.

**Comment by mmstick** [comment]
@suhr What do you think of this proposed syntax?

### Creating an array

```
let array = ['one two' 'three four' 'five six' 'seven eight']
```

### Accessing element from array

```
$ echo @array[0]
one two
```

### Copying elements from an array into a new array

```
let begin = [ @array[..2]  ] # first two elements
let mid   = [ @array[1..3] ] # middle elements
let end   = [ @array[3..]  ] # last elements
let copy  = [ @array       ] # copy entire array
```

## Concatenate arrays

```
let new = @concat(first, second)
let new = [ @first @second ]
```

### Push/Drop element from array

???

### Pass elements from array

```
command @args
echo @args[0..3]
```

### Sort array

```
let array = @sort(array)
```

### Splitting a string into an array of words

```
let word_array = @split(var)    # Maybe implement possible multi-dimensional arrays?
let word_array = @split(var[0]) # Split first element by whitespace
```

### Splitting a variable into an array using a custom delimiter

```
let csv_row = @split(row ',')
```

### Obtaining a substring from a string

```
let slice = $var[0..3]
```

### Apply function and get specific element

```
echo @split(var)[3]
```

**Comment by jackpot51** [comment]
I don't like the idea of using @ as shell grammar

**Comment by mmstick** [comment]
@jackpot51 Primary benefit of the @ character is that it allows you to know that you're working with an array instead of a variable. Here's another example, but using the $ character.

@suhr What do you think of this proposed syntax?

### Creating an array

```
let array = ['one two' 'three four' 'five six' 'seven eight']
```

### Accessing element from array

```
$ echo $array[0]
one two
```

### Copying elements from an array into a new array

```
let begin = [ $array[..2]  ] # first two elements
let mid   = [ $array[1..3] ] # middle elements
let end   = [ $array[3..]  ] # last elements
let copy  = [ $array       ] # copy entire array
```

## Concatenate arrays

```
let new = $concat(first, second)
let new = [ $first $second ]
```

### Push/Drop element from array

???

### Pass elements from array

```
command $args
echo $args[0..3]
```

### Sort array

```
let array = [ $sort(array) ]
```

### Splitting a string into an array of words

```
let word_array = [ $split(var) ]    # Maybe implement possible multi-dimensional arrays?
let word_array = [ $split(var[0]) ] # Split first element by whitespace
```

### Splitting a variable into an array using a custom delimiter

```
let csv_row = [ $split(row ',') ]
```

### Flatten array with custom delimiter

```
let string = $join(array ',')
```

### Obtaining a substring from a string

??? Not sure how to do this here in the event that the variable is an array

### Apply function and get specific element

```
echo $split(var)[3]
```

**Comment by suhr** [comment]
```
let array = ['one two' 'three four' 'five six' 'seven eight']

echo $array[0]
# one two

let begin = [ @array[..2]  ] # first two elements
let mid   = [ @array[1..3] ] # middle elements
let end   = [ @array[3..]  ] # last elements
let copy  = [ @array       ] # copy entire array

let new = @concat(first, second)
let new = [ @first @second ]

command @args
echo @args[0..3]

let array = [ @sort(array) ]

let csv_row = [ @split(row ',') ]

let string = @join(array ',')

echo @split(var)[3]
```

NOTES:

* If arrays are only flat (so [[a b] c] is [a b c]), `let copy = [$array]` can be used. But otherwise, `@` is needed to “unarray” the `array` to create a copy of it. The same is for command arguments.
* Array operations have `@` to differentiate them from variables.
* We don't really need `@concat()`
* Taking a substring is not an array operation

**Comment by mmstick** [comment]
@suhr 
- Substrings will be taken by unicode codepoints, so there will never be boundary issues to worry about.
- I don't see a use case for more than flat arrays in a shell language, but I could be convinced otherwise.
- What if array operations were done like so?

```
let csv_row = ${split row ','}
echo ${split var}[3]
```

@jackpot51 What's your opinion on syntax for supporting arrays and array operations?

**Comment by suhr** [comment]
> Substrings will be taken by chars

Do you mean code points or graphems? The first is better than indexing by bytes, but still invalid (graphems can be several code points long), the second is complicated enough to wonder why would we even need this (maybe better to make everything to support json?)

> I don't see a use case for more than flat arrays in a shell language

I believe that nested array can be useful, but the only example I have right now is indeed putting json everywhere.

Lack of experience with a proper shell (due to lack of proper shells), you know.

> What if array operations were done like so?

Ad-hoc bash syntax? I'm not a fan of it. Actually, `split` could be just a function, so:

```
let csv_row = $(split $row ',')
echo $(split $var)[3]
```

This conflicts with `split` as a command though (in elvish this problem is solved with namespaces: `e:cmd` will run external `cmd`).

cc @andychu

**Comment by mmstick** [comment]
@suhr 

> Do you mean code points or graphems? The first is better than indexing by bytes, but still invalid (graphems can be several code points long), the second is complicated enough to wonder why would we even need this (maybe better to make everything to support json?)

Rust handles this quite easily out of the box -- unicode scalar values. The simplest being:

```rust
let substring: String = value.chars().skip(start).take(end-start).collect();
```

> I believe that nested array can be useful, but the only example I have right now is indeed putting json everywhere.

I think I'd like to use associated arrays for that, but I can aim for multidimensional arrays in addition.

> This conflicts with split as a command though (in elvish this problem is solved with namespaces: e:cmd will run external cmd).

I can have the let keyword define it's own syntax as it does in bash.

**Comment by andychu** [comment]
Hey thanks for cc'ing me -- I didn't know about Ion until now!  (I've heard of Redox OS but just a little.)

I added Ion to my wiki page here:

https://github.com/oilshell/oil/wiki/ExternalResources

So far I like what I see.  I guess I will explain what I'm doing with Oil and you can feel free to copy it or take inspiration from it.

I am preserving the nice property of bash that you can just put a command inside an array, and the argv becomes the array, without execution.

For example, in bash:

```
echo bare_word *.py {alice,bob}@example.com  # glob and brace expansion
array=(bare_word *.py {alice,bob}@example.com)   # same thing in array, note bareword
echo "${array[@]}"
```

Although bash has bad syntax, I like the consistency between arrays and commands.  It's also consistent with the for loop.

In Oil:

```
echo bare_word *.py `{alice,bob}@example.com`  # braces are special
array = [ bare_word *.py {alice,bob}@example.com ]
echo @array  
```

I think of @ as "array splicing" and $  "to string".  For functions, the sigil has to match the return value.

For example:

```
myString = 'one two three'
myArray = [one two three]
echo $myString @myArray
echo @split(myString) $join(myArray, " ")
```

Split returns an array from a string, so the sigil is @.  Join returns a string from an array, so the sigil is $.

Other things that I could go into detail about:

- Oil has command vs. expression lexer and parser modes.   What's inside parens in $func(...) is in expression mode.
- Arrays are non-nested and homogeneous in Oil.  I thought about the JSON issue, and I'm thinking I will have a separate List type for it.  I don't expect List to be very common actually... almost all real use cases will use Arrays.  The List data type could cheat and use Map underneath, like JavaScript and Lua do.

**Comment by jackpot51** [comment]
I am not sure @mmstick. I bash does not do it a sane way, we are free to implement any syntax

**Comment by mmstick** [comment]
@jackpot51 I think the Oil shell does a pretty good job in this area, so I will likely pursue copying that syntax.

**Comment by mmstick** [comment]
@andychu So what happens when you call $ on an array directly?

**Comment by andychu** [comment]
I haven't implemented it yet, but in Oil I think that should be a runtime error.

It's possible that `$array` could implicitly join it with IFS, and `@str` could split it with IFS, but I prefer an explicit `$join()` and `@split()` for readability.  I don't believe it's a common use case at the interactive prompt.

Shells tend to avoid runtime errors and keep plugging along, which I think is bad because it just obscures the location of bugs.

For example if you do

```
x="$@" 
x="${array[@]}"
```

Then it will silently decay the array into a string by joining it.  This preserves the array:

```
x=("$@")
x=("${array[@]}")
```

Likewise, if you try to compare an array like [[ "$@" == '1 2 3' ]] it will also decay into a string before comparing.

In OSH, I think I will allow the user to disable this with `set +o array-decay`.

**Comment by andychu** [comment]
Oh I guess the more direct comparison is doing

```
a=(1 2 3)
echo $a
```

in bash.  Bash and mksh have the bizarre behavior where $a is equivalent fo ${a[0]}.

Likewise, if you have:

```
s='foo'
echo ${s[@]}
```

It just ignores the `[@]`, which normally means "array".  This design seems totally wrong and just an accident of history.   Imagine if in Python `a=[1 2 3]; print a` showed you the first element.

**Comment by mmstick** [comment]
@andychu I figured as much, as this is how I currently have it working in my local copy. I'll have some basic array support available soon.
