### ISSUE TITLE
Borrow ideas from other shells

### ISSUE THREAD

**Issue by suhr** [redox-os/ion#249]
Like [Oil Shell](http://www.oilshell.org/), [Elvish](https://github.com/elves/elvish) or [Oh](https://github.com/michaelmacinnis/oh).

The list of shells: https://github.com/oilshell/oil/wiki/ExternalResources

Particularly, elvish has many cool features, like piping lists or lambdas or `$@list` syntax (there's even [some](https://elvish.io) documentation).

**Comment by mmstick** [comment]
If there's specific features that you think would be a great fit, you're free to open an issue for each specific issue. If you would like to contribute, I can help you with that.

**Comment by suhr** [comment]
This is a meta issue. I'll think about concrete examples though.
