### ISSUE TITLE
Higher-Order Functions

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#251]
Functions should be able to accept other functions as inputs.

**Comment by andychu** [comment]
Oil has the dichotomy between funcs and procs sort of for this reason.  procs can be run in pipelines, as the other issue mentioned.  funcs can (possibly) accept other functions, return functions, accept and return compound data structures, etc.

I think that procs are mostly a restricted version of funcs.  They take an argv array and return an exit code, and have file descriptors.

It's probably possible to have both properties with one construct, although I think it will get a little hairy for the implementer and user.

It might be more of a syntactic issue than anything.
