### ISSUE TITLE
Shell Expansion Expansion

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#254]
This issue will track the progress of the shell expansion rewrite that I am now working on.

- [x] Rewrite the Word Iterator
  - [x] Array
  - [x] Array Variable
  - [x] ArrayMethod
  - [x] Brace
  - [x] Variable
  - [x] ArrayVariable
  - [x] StringMethod
  - [x] Process
  - [x] Array Process
  - [x] Tilde
  - [x] Normal
  - [x] Whitespace
  - [x] Handle Quoting
- [x] Rewrite Brace Expansion
  - [x] Enable braces within braces
  - [x] Collect words before and after before expanding
  - [x] Implement brace ranges
- [x] Rewrite Variable Expansion
- [x] Migrate Let into Grammar
- [ ] Migrate Export into Grammar
- [x] Make Arrays First Class Citizens
- [x] Array Slicing
  - [x] Slice by ID
  - [x] Slice by Range
  - [ ] Slice with Expression
- [x] Improve Syntax Validation Layer
- [x] Rewrite Tests & Add More Tests

Once complete, performance should also further improve. Most of the CPU time spent in the shell is within this module, and the new design should require much less CPU time and be easier to read / maintain.

**Comment by mmstick** [comment]
I may push all the changes that I've made tomorrow. I have a good working base that is now more functional than what Ion currently offers. I just need to fix and add more tests and it will be ready, then I can continue working on implementing the rest of the unimplemented features.

**Comment by mmstick** [comment]
So the work was merged and seems to be doing well. I will be working on gracefully handling syntax errors, fixing tests and adding new ones before my next set of changes.

**Comment by andychu** [comment]
Nice!

What about globbing?  If I were to design a shell without compatibility, I would probably get rid of the globbing after substitution.  A file named `*.py` on the file system can trick you into doing something you didn't want.

Oil will probably have a mode to disable this, so only unquoted literals like `echo *.py` are globbed.  For the rarer dynamic use cases, there could be a glob type that works like Glob("$prefix/*.py"), similar to a regex.

Globbing also introduces some parsing problems if you want to use `[]` for arrays, e.g. `?.[ch]` is a valid glob.

FWIW here are the data structures I'm using for the word evaluation pipeline, which consists of string and arrays.

https://github.com/oilshell/oil/blob/master/core/runtime.asdl

(ASDL is basically algebraic data types, which I assume should play well with Rust.  The osh/osh.asdl file may also be interesting.  ASDL is mentioned a lot in the blog)

If you don't have implicit word splitting and word elision (e.g. `$empty` and `$(echo -n '')` expand to zero args, not a single empty arg), then it could probably be simpler.

Also I'm not sure how much it matters for Ion, but I noticed that brace expansion is really metaprogramming in bash.  It doesn't depend on any runtime variables, and it can duplicate expressions with side effects, like:

    $ echo {a,b,c}-$((i++))
    a-0 b-1 c-2
    # other shells give  a-0 b-0 c-0 because of different evaluation order

Last test case here:

https://github.com/oilshell/oil/blob/master/tests/brace-expansion.test.sh

**Comment by mmstick** [comment]
@andychu We have globbing being implemented with the [official glob crate from the Rust team](https://doc.rust-lang.org/glob/glob/index.html) at the moment, and it currently happens after the expansions performed in this module so there won't be any syntax conflicts. I need to improve it though as it doesn't work correctly in for loops yet -- the returned expression is represented as a single string instead of a vector of strings, which is needed to loop with each individual argument separately. At some point though, I will migrate globbing into this module and have it only expand words that aren't double quoted.

> ASDL is basically algebraic data types, which I assume should play well with Rust

Indeed, Rust is heavy on these kinds of types, as seen [here](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/words.rs#L13:L23).

> ```
> $ echo {a,b,c}-$((i++))
> a-0 b-1 c-2
> # other shells give  a-0 b-0 c-0 because of different evaluation order
> ```

I don't think we will do what Bash does here. That wouldn't be compatible with my permutate crate, so this works as other shells do.

**Comment by mmstick** [comment]
[This commit](https://github.com/redox-os/ion/commit/ef9609053b6f00633d53a475d20c423dd3edf43d) fixes the glob expansion for for loops.

**Comment by jackpot51** [comment]
Cool!

**Comment by mmstick** [comment]
Arrays are now implemented, and all that's left to complete the array-related work is to implement the array splicing syntax, and the ArrayToString and StringToArray syntax. The projects README has been updated to display the current features.

One downside to implementing the array support is that the PROMPT had to be modified to remove the coloring, as it conflicts with the array syntax. We might want to do as the fish shell does and make the prompt a function rather than a variable, and come up with a means of setting colors.

**Comment by jackpot51** [comment]
Why does it conflict with a colored prompt?

**Comment by mmstick** [comment]
@jackpot The colored prompt uses ] and [ characters which the shell is currently wired to assume they are being used to create arrays. One fix would be to make an exception for those particular combinations of characters so that the shell doesn't interpret them as array syntax.

**Comment by andychu** [comment]
Note that using `[]` for arrays also potentially conflicts with globs like `*.[ch]`.

There are a couple ways to handle this in Oil, but I haven't implemented it yet.

It's possible to use `()` like bash, but I've decided against that.

**Comment by jackpot51** [comment]
That sounds like a really bad regression @mmstick

**Comment by mmstick** [comment]
@jackpot51 Easily fixed though

**Comment by mmstick** [comment]
@jackpot51 https://github.com/redox-os/ion/commit/5ff6f0139e09f1969018bd5dfcca61c1da3a2c39 fixes the prompt by wrapping the brackets in single quotes.

**Comment by mmstick** [comment]
With the last two commits, it is now possible to slice arrays by ID and range. Therefore, the following is now valid syntax:

```ion
let a = [ 1 2 3 ]
echo @a[0]
echo @a[1]
echo @a[2]

echo @[echo 1 2 3][0]
echo @[echo 1 2 3][1]
echo @[echo 1 2 3][2]

echo [1 2 3][0]
echo [1 2 3][1]
echo [1 2 3][2]

let array = [ 1 2 3 4 5 ]

echo @array[2..3]
echo @array[2...3]
echo @array[..3]
echo @array[3..]
echo @array[..]
```

**Comment by mmstick** [comment]
In other news, seems we are now at 4400 lines of Rust source code in this project.

**Comment by mmstick** [comment]
With array and string method syntax now complete, I will close this.
