### ISSUE TITLE
Implement Arithmetic Expressions

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#257]
We would like to support inline arithmetic expressions in the Ion shell, like so:

```ion
echo $(( b * (h * h) ))
```

One should be able to omit or retain the $ sigil when calling for variables. An error should be returned if a variable is not a number. We should be able to directly hook the expression into the existing calc built in command.

**Comment by Maaarcocr** [comment]
Could I work on this? (I cannot promise by when I will finish this, because I'm revising for exams that will end on the 11th of May). 
I was thinking of changing the way assignments are parsed (right now it's done in rust), by completely implement them in peg and then also support arithmetic expressions. 
Does it sounds okay?

**Comment by mmstick** [comment]
I'm actually probably going to move towards eliminating peg entirely. It demands a nightly compiler to use, the returned results have to be heap allocated, and the error messages aren't what we'd want for a shell. The RHS of assignments has to go through the shell expansion module anyway.

As for this feature in particular, most of what needs to be done is just hook the logic into the existing calc command that's currently a built-in command. A few changes would be needed to allow for the **$(( expr.. ))** combination, and the inner expression would just need a quick scan for words that are string variables that may be converted  into numbers.

**Comment by Maaarcocr** [comment]
Is the code here: https://github.com/redox-os/ion/blob/5ff6f0139e09f1969018bd5dfcca61c1da3a2c39/src/parser/assignments.rs#L34 still usable? 
So, just to be sure I've understood, I would need to check when the RHS of an assignment is an arithmetic expressions and then use calc?

**Comment by mmstick** [comment]
I don't think we will have the let keyword check for mathematical expressions on the RHS. That would increase runtime costs in most cases where it's not.

Instead, mathematical expressions will go within $(()) for inline arithmetic the same as other shells.

**Comment by jackpot51** [comment]
Awesome @mmstick, that makes more sense

**Comment by mmstick** [comment]
Updated the OP to make it more clear as to what we are trying to do at the moment in regards with arithmetic expressions. Forgot to remove the let arithmetic portion which I decided against.

**Comment by mgmoens** [comment]
Doesn't something similiar already work with calc? It would be `calc $b * ($h * $h)`.
Of course, not using $ everytime you use a variable would be better.
Or do you want $(()) to get calculated as a mathematical expression, regardless of the command? I mean something like `scrot -d $(( b * (h * h) ))` (scrot is just the first program that accepts a number that popped into my head honestly).

**Comment by mmstick** [comment]
The problem with $() is that that it calls a costly sub-process. $(()) would instead happen within our parser and avoid the cost of a sub-process.

**Comment by huntergoldstein** [comment]
I've been hacking away at this for a bit. It's ready to go (will open a PR soon) but it seems like the parser is kinda buggy, opening an issue with my finding.
