### ISSUE TITLE
Improve Range Syntax With Negative Values for Taking From the End

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#263]
To further improve the capabilities of the range syntax, we can expand on that to support the following syntax, where a negative value indicates to count and take values from the end of an array, versus from the beginning

```ion
# Syntax for getting the last value?
echo @array[-1]   # Take the next to last value
echo @array[..-1] # Take all but the last value
echo @array[-5..] # Take the last five values
echo @array[-5..-2]
```

**Comment by ZSarver** [comment]
Forgive my ignorance, but what's the rationale on making @array[-1] the next to last value instead of the last value?

**Comment by mmstick** [comment]
@ZSarver There isn't much rationale to the syntax here yet -- it's largely just in idea stage. My thinking was that it might be confusing that a positive 0 is the first value, but a negative 1 is the last value.

**Comment by ametisf** [comment]
IMO negative zero would be super confusing.

**Comment by simondesloges** [comment]
```sh
echo @array[-1]   # Take the next to last value
echo @array[..-1] # Take all but the last value
```
Weird... Souldn't `@array[..-1]` take all but the two last values, since -1 is next to last and `..` is exclusive range syntax?

If it can help, here are some exemples of related syntactic sugar from other programming languages:

In Python, you can index with negative values. I don't think it's all that confusing.
```python
w = "Hello!"
assert w[0] == "H"
assert w[-0] == "H" # -0 is still 0
assert w[-1] == "!"
```

In Dlang, when indexing or slicing, `$` is used as a shorthand for the array's length. Another character could be used for Ion.
```d
string a = "Hello!";
assert(a[0] == 'H');
assert(a[$-1] == '!');
// a[$] <-- out of range!!
```
Using the concept of negative zero, how is it going to work with variables and arithmetic?
```sh
let array = [ 1 2 3 ]
let i = -1
echo @array[$i] # 2
let i += 1 # this is 0 or -0?
echo @array[$i] # 1 or 3?
```
What if indexing was always 1 based like lua? Not that I like one-based indexing, but it's an idea.
```sh
let array = [ 1 2 3 ]
# echo @array[0] <--- not a valid index
echo @array[1] # 1
echo @array[2] # 2
echo @array[-1] # 3
```

**Comment by ZSarver** [comment]
I have to agree with @ametisf since mathematically -0 = 0. My personal preference would be for @array[-1] to be the last value. That's, for example, what Python does. (Yes, yes, I know I should really just start using Python 3 already.)

`Python 2.7.11 
Type "help", "copyright", "credits" or "license" for more information.
>>> arr = [1,2,3,4]
>>> arr[-1]
4
>>>
`

**Comment by mmstick** [comment]
@ZSarver Computers do actually have a concept of signed zeros, where the zero has the negative bit set. That said, we can go for -1 being the last variable if there are no objections to that.

**Comment by ZSarver** [comment]
@mmstick Sorry, I deleted my comment because @simondesloges said everything I wanted to only more and better. Just to throw in my two cents, I think it's irrelevant whether zero can have the negative bit set. I think it would be confusing to users.

**Comment by mmstick** [comment]
If anyone would like to implement this feature, I can point you in the right direction. I'm busy with a lot of other things at the moment so my constant stream of updates to Ion will be paused for a bit.

**Comment by ZSarver** [comment]
@mmstick I'd be interested, but I am both busy and something of a newbie rustacean. I can't make any promises as to when I'd be able to get to it.

**Comment by mmstick** [comment]
@ZSarver Basically, you will:

1. Start [here](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/ranges.rs#L64) and modify the `parse::<usize>()` calls to `parse::<isize>()`
2. Change [this enum](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/words.rs#L28) to offer a new `FromEnd(usize)` variant
3. Do the same [here](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/words.rs#L20) to offer a `IDFromEnd(usize)` variant
4. Modify the Range variant so that the start value in the tuple can either be `FromStart(usize)` or `FromEnd(usize)`, so you'd need to create a `IndexStart` enum for that. Maybe also change the name of `IndexPosition` to `IndexEnd` for clarification that it only applies to the ending index.
4. Go back [here](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/ranges.rs#L64) and write the code to check for negativeness, returning the new variants that you have just created, and use the 'abs()' method to convert negative integers into positive ones.
5. Your Rust IDE should be giving you warnings in all the areas where the new variants apply, so you will have to add the code to grab the Nth value from the end or a range of Nth values from the end in each of those areas.
6. When finished, you can add some example tests in the [arrays script and associated out file](https://github.com/redox-os/ion/blob/master/examples), and you could also add a few unit tests for good measure if you want.

**Comment by robinvd** [comment]
@mmstick Most computers use [Two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) which does not have the concept of signed 0's.

**Comment by MovingtoMars** [comment]
@robinvd  I believe @mmstick is referring to floats, which do negative 0's, rather than integers.

However, I think -1 should be the last, not the next to last element.

**Comment by huntergoldstein** [comment]
Is there any update on this? I took a stab at it (some progress in [my fork's master](https://github.com/huntergoldstein/ion)). Two notes:
- There are now three enums that are, essentially, named `Index`; this is fairly confusing and perhaps can be consolidated to `Selector` (currently `Index`) and `Index` (currently `IndexStart` and `IndexEnd`).
- Many of the code-sites modified have very similar logic, either `skip(...).take(..)` or `nth`

**Comment by mmstick** [comment]
@huntergoldstein No one's made an attempt at this yet. Just waiting for a good PR to be submitted. If you feel that you have a good solution, you're free to open a PR (even if it's WIP). It's okay if there's some confusion with the names at the moment. That's a problem that's easily resolved with a tiny bit of refactoring.
