### ISSUE TITLE
Goal: Soundly Defeat Bash in Performance

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#264]
There are a few areas in the shell that could use some optimizations to better compete with other established shells. Here are some optimizations that I can think of that would be beneficial and not too complicated to implement.

- [ ] Implement echo, test, and other essential commands.

- [ ] When creating a new Job structure, the structure should contain both the original arguments, set to private, and a tokenized variant that self references to the original arguments. This could probably be achieved using the rental crate. In any case, without this optimization, each loop through a set of statements requires re-tokenizing arguments.

- [ ] Statements contained within loops should be collected and reused, rather than having to recollect a copy of each statement for each loop.

- [ ] JIT-compile scripts into an IR representation, and cache this IR for future runs. Basically, this would allow the ability to skip much of the parsing and validation for future runs of the same script. Compare the hash and filename of the script, and if the hash and filename match an existing pre-compled script, load the Statements from that script and execute it.

**Comment by jsalzbergedu** [comment]
>- [ ] JIT-compile scripts into an IR representation, and cache this IR for future runs.

This sounds _really_ cool and it is something I would be interested in doing, but I'm kind of a newb. Is there any reading that I should do first or any direction you had in mind for this?

**Comment by mmstick** [comment]
@jsalzbergedu No reading that I know of. Basically, the parser in the shell must convert given commands into a collection of `Statements` before it can execute them, and this process involves verification that the syntax is valid.

We could write this data directly to the disk in a cache directory, with the filename of each cached script being a hash of the file. How much of an improvement this would make though, I don't know. It probably wouldn't help much at all.

### Top Priority

Currently, the biggest area of improvement for the Ion shell would be implementing the echo and test commands natively in the shell. Simplest means of doing so would largely be copying the source code for these commands from the redox coreutils or uutils project.

The fibonacci.ion script takes 33 ms on my laptop to complete, in comparison to Bash which takes 45 ms. Bash has the test and echo commands built in, which leads to major performance improvements. Without them, Bash would take 89 ms to complete the same task. I suspect that if we were to implement the echo and test commands natively, Ion could drop the runtime down to 11 ms, and we would be halfway there to competing with the Dash shell, and this issue would largely be complete.

### Other

I would like to see more contributions in the examples directory though, for testing and benchmarking purposes. The fibonacci example is the only test I have to go with at the moment.

**Comment by jsalzbergedu** [comment]
Thanks, I'll see if I can implement that but first I'll see if I can help w/ getting a native echo and test

**Comment by mmstick** [comment]
The `echo` command is now builtin and `test` is on the way. Times have dropped down to 15 ms for that fibonacci script, instead of 33 ms as it was before.

**Comment by mmstick** [comment]
We are now many times faster than bash, and on the same level as Ion, so I think we are good here.
