### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by fbruetting** [redox-os/ion#270]
With Ion supporting Linux and Redox, it would be nice if it would work on the BSDs, too – most importantly of course FreeBSD! :)

**Comment by mmstick** [comment]
It should already be working on BSDs, theoretically, as BSDs also use the same unix modules.

**Comment by myfreeweb** [comment]
It certainly works on FreeBSD after my tiny PR to termion landed: https://github.com/ticki/termion/pull/98

**Comment by fbruetting** [comment]
If this is also true for ion, would someone please advertise this on the GitHub front page, then we could close this. :)

**Comment by myfreeweb** [comment]
I meant ion, what else could "it" refer to? ;)

+1 to updating the readme.

**Comment by fbruetting** [comment]
I was a bit confused, how ion could be supported by a patch for termion. But I now think that this was a termion problem, but ion ran on BSD even before… :P

**Comment by myfreeweb** [comment]
Maybe it ran before the `TIOCGWINSZ` usage was added.

**Comment by mmstick** [comment]
Closing issue since BSD's have always been supported as a UNIX platform.
