### ISSUE TITLE
Implement Match / Switch / Case Flow Keyword

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#273]
Implementing this will require a bit of studying of the existing **FlowLogic** methods. Shouldn't be too hard though. The hardest part should be determining the syntax that we want to go with.

```ion
match $(getconf LONG_BIT)
    case "32"
        echo "32-bit OS found"
        end
    case "64"
        echo "64-bit OS found"
        end
    case _
        echo "Unsupported OS architecture"
        end
end
```

We could introduce two new statement types: Match and MatchArm. The statement splitter should be able to split upon detecting a complete match arm.

**Comment by ids1024** [comment]
Would it create parsing ambiguities to remove the `end` from the individual cases? Since we presumably don't wan't to allow fall-through, the `end` doesn't add anything.

**Comment by mmstick** [comment]
I think we can remove the `end` keyword. Just need to find out what match arm syntax we want to use. My example syntax would be a tiny bit difficult to implement. Perhaps we could use `case VAL => EXPR`?

**Comment by jackpot51** [comment]
I like case VAL, then either a newline or a semicolon, then EXPR, then end (since case is a block and so far all blocks end with end)
