### ISSUE TITLE
Eliminate Dependency on Nightly Compiler

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#277]
I see no reason for us to continue using and relying upon a nightly compiler for the Ion project. Stable has everything we need. This will require a few changes. The hardest will be getting rid of the need for the nightly requirement with PEG right now. I'd like to target the latest Rust 1.17 release as a minimum target for now.

**Comment by kevinmehall** [comment]
rust-peg [no longer requires nightly](https://github.com/kevinmehall/rust-peg#with-a-build-script).

**Comment by mmstick** [comment]
@kevinmehall Seems the non-nightly usage variant would conflict with the `build.rs` that we are already using.

**Comment by kevinmehall** [comment]
You can add the `extern crate peg;` and `peg::cargo_build` lines to the existing build.rs.

**Comment by mmstick** [comment]
One dependency on nightly down. Two more to go. Next is removing the usage of the box keyword.

**Comment by mmstick** [comment]
Box syntax usage is now eliminated. Only one left.

**Comment by mmstick** [comment]
Ion now builds with the 1.17.0 compiler.
