### ISSUE TITLE
Tag new version numbers in git?

### ISSUE THREAD

**Issue by z3ntu** [redox-os/ion#279]
I have just now created Arch Linux packages for ion and it works great! Found [here (ion)](https://aur.archlinux.org/packages/ion/) and [here (ion-git)](https://aur.archlinux.org/packages/ion-git/).

It would be easier for me if the releases (eg 1.0.1) would be tagged as I could then just specify the version number instead of finding out the commit (eg fd9389f).

Thanks!

**Comment by jackpot51** [comment]
@mmstick tagged the latest release (1.0.2), and will probably tag future releases

**Comment by z3ntu** [comment]
Awesome! Thank you very much.
