### ISSUE TITLE
alias weirdness

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#281]
```
james:/home/james# alias ls = 'echo foo'
james:/home/james# ls
ls: cannot access 'foo': No such file or directory
```

using the 1.0.2 github release, `rustc 1.17.0 (56124baa9 2017-04-24)`, first time user

**Comment by mmstick** [comment]
I'll look into this shortly.

**Comment by mmstick** [comment]
I'll have the fix uploaded within a few minutes.

**Comment by mmstick** [comment]
The fix has been pushed. The command field simply wasn't being changed to reflect the command issued in the alias.
