### ISSUE TITLE
request: implicit cd

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#282]
a nice feature from fish shell is 'implicit cd', where simply typing a path to a directory will automatically `cd` there.

**Comment by mmstick** [comment]
I'll look into this soon.

**Comment by mmstick** [comment]
Feature implemented ( https://github.com/redox-os/ion/commit/5d3ca8997365c1c0366cac8c69afa072b1b0cabb )

**Comment by mmstick** [comment]
Now here's a question:

Should we do as Fish and only allow implicit cd to work when the path starts with a dot or ends with a slash?
