### ISSUE TITLE
autosuggestion creates new lines

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#283]
if i enter a command which exceeds a single line, re-typing the command causes the auto suggest to create new lines.

    james:/home/james# echo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

![bug](http://i.imgur.com/fZBqSfz.png)

**Comment by mmstick** [comment]
This should be filed against the liner crate, as Ion does not have control over the readline functionality provided my liner.

**Comment by MovingtoMars** [comment]
This is fixed in liner 0.2.0.
