### ISSUE TITLE
tab completion doesn't escape filenames

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#284]
```
mkdir 'x()'
cd x<Tab> # cd x()/
ion: syntax error: '(' at position 5 is out of place
```

**Comment by mmstick** [comment]
Tab completion is currently exclusively handled by the liner crate, so we have no means of influencing how tab completions are expanded.

**Comment by gyscos** [comment]
It currenly escape spaces, but not quotes or parenthesis.

**Comment by mmstick** [comment]
Once the liner crate offers a mechanism to provide a callback so that we can influence tab completions, i'll be able to fix this. This is basically the same issue that we have with tilde home expansions.

**Comment by huntergoldstein** [comment]
What about writing a `Completer` that uses a `FilenameCompleter` internally and escapes the filenames? It seems like that could be done instead of using a `FilenameCompleter` alone.

**Comment by mmstick** [comment]
I'll look into it, and if it's feasible, I'll probably have a patch out soon.

**Comment by mmstick** [comment]
So the main issue with the `FilenameCompleter` is that in order for Ion to provide completions for files in directories, the `completions` method would need access to the Ion shell's `DirectoryStack` and `Variables` fields. So, I'll need to write a different kind of completer.

**Comment by huntergoldstein** [comment]
Is there somewhere beyond [here in `Shell::readln`](https://github.com/redox-os/ion/blob/5614d77dd26fa6f7d4329f32a7df2dbf3ff421a6/src/shell/mod.rs#L106) where the completer is built up?

**Comment by mmstick** [comment]
So the `FilenameCompleter` will take a directory, and then read that directory and generate a list of files within the `completions()` method. One particular enhacement that we need to see done would be also escaping parenthesis, in addition to spaces.

Now, regarding home directory expansions specifically, you could probably expand that before passing it into a `FilenameCompleter`.

**Comment by MovingtoMars** [comment]
@mmstick yeah, I'd definitely expand all the `~`s and variables and stuff before passing the path to the filename completer.

Offering some options for the escaping problem here:
1. Just escape directly in `FilenameCompleter`. Probably easiest.
Could have option like
```rust
enum Escape {
    Never,
    // forgive the naming, can't think of better one right now
    SpacesWithBackslashesAndSpecialsWithQuotes,
    SpacesAndSpecialsWithQuotes,
    Always,
}
```

2. Create a `struct<T: Completer> EscapingCompleter<T> { inner: T }`
```rust
impl Completer for EscapingCompleter {
    fn completions(&self, start: &str) -> Vec<String> {
        self.inner.completions().iter().map(|x| escape(x)).collect()
    }
}

fn escape(s: String) -> String {
    ...
}
```

3. Provide a callback in `FilenameCompleter.complete()`.

Personally, number 2 is my favourite. I think using composure like this is quite elegant. Thoughts?

**Comment by mmstick** [comment]
I'll try out the second option soon.

**Comment by mmstick** [comment]
This issue is now resolved.
