### ISSUE TITLE
Possible enhancement: support `set -o vi`

### ISSUE THREAD

**Issue by jwbowen** [redox-os/ion#289]
`set -o vi` is a way of life for me in shells. It would be neat if ion offered it. I'm also guessing that this would be a rather large undertaking and one of quite low priority.

**Comment by MovingtoMars** [comment]
Liner actually supports vi mode. It's just not exposed in Ion.

All that needs to be done is for Ion to handle the `set -o` command and change `liner::Context.KeyBindings` appropriately.

**Comment by jwbowen** [comment]
Ah, I did not know that about `Liner`. I'll poke around and see if I might have the time to add handling for `set -o`.

(But if someone else wants to make this enhancement go ahead, as I'm new to Rust and don't know if I'll actually have the time to allocate to it.)

**Comment by mmstick** [comment]
Adding support should be very simple. It's largely a matter of adding the o flag to set built-in command that sets it's associated bit flag in the shell, and then adding a check for that in readline to select to correct binding.

**Comment by mmstick** [comment]
I'm working on this.

**Comment by mmstick** [comment]
I have completed this feature ( https://github.com/redox-os/ion/commit/ce0a19672e7d76c4ff431bffa2731852a893157e ). Supported keybindings are emacs and vi.

**Comment by jwbowen** [comment]
jbowen:/home/jbowen/bld/ion# set -o vi
jbowen:/home/jbowen/bld/ion# echo "'set -o vi' is working"
'set -o vi' is working
jbowen:/home/jbowen/bld/ion# date
Sat Jun 17 10:13:04 CDT 2017
jbowen:/home/jbowen/bld/ion# hostname
flexo
jbowen:/home/jbowen/bld/ion# # Thanks, mmstick!
jbowen:/home/jbowen/bld/ion#
