### ISSUE TITLE
use HISTFILE instead of HISTORY_FILE

### ISSUE THREAD

**Issue by mallochine** [redox-os/ion#299]
There's probably some context I'm missing here, but shouldn't the shell be using "HISTFILE" instead of "HISTORY_FILE"? HISTFILE is the standard bash variable:

https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

**Comment by mmstick** [comment]
Original plan has been to not follow Bash for the sake of following Bash. HISTORY_FILE is more descriptive than HISTFILE

**Comment by mallochine** [comment]
hm I see. Though if you want to see adoption of ion from bash, backwards-compatibility is super important.

For instance, I wrote a spell checker in python that uses the $HISTFILE environment variable. This script will break on 'ion'.

But from a business perspective...anyway I suggest reading this for why backwards-compatibility is important: https://www.joelonsoftware.com/2000/05/24/strategy-letter-ii-chicken-and-egg-problems/
https://www.joelonsoftware.com/2004/06/13/how-microsoft-lost-the-api-war/

**Comment by mmstick** [comment]
We aren't competing with Dash/Bash though. Ion is the default shell of RedoxOS, and if you want to use it on Linux or some other platform, then that's up to your discretion.

**Comment by mgmoens** [comment]
This might sound kind of idiotic, but wouldn't having a $HISTORY var containing the name of the variable containing the history file be a fix? It's descriptive and people can adopt it to whatever thing they want it to be compatible with.

**Comment by mmstick** [comment]
At that point, you could just use either a TOML or YAML configuration file to configure Ion settings.

**Comment by mmstick** [comment]
Anyone else have any opinion on what the name of the history file variable should be? Should be copy Bash here?

**Comment by jackpot51** [comment]
If you change it at all, copy bash

**Comment by mgmoens** [comment]
I agree with jackpot51

**Comment by mmstick** [comment]
I think it'd be fine to switch the name to what Bash is using.
