### ISSUE TITLE
Command line editor for ion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#3]
Shells like bash and zsh have line editors that make them far more usable. For example here are some features provided by GNU Readline used in bash:

* Tab completion
* Up arrow for previous command
* Reverse search (ctrl-r)

Readline is kind of the standard for line readers, but it is under a GPL license. It would be nice to have our own line editor written in Rust that can be used by our shell.

NOTE: This was originally an issue opened in Redox (https://github.com/redox-os/redox/issues/346), but I am moving it here.

**Comment by stratact** [comment]
We're planning to look at the Fish shell for inspiration on how to implement those features.

cc @mgattozzi @hauleth @Ticki

**Comment by skylerberg** [comment]
One of the barriers to implementing this is the need to run the terminal in raw mode. Right now the shell works in cooked mode and does not support reading input character by character. I have not taken a closer look at how the terminal works in redox, but there might be some work there to make it possible to switch to raw mode.

**Comment by mgattozzi** [comment]
The main problem is being able to use keyboard interrupts. As it stands the Rust Standard Library lacks nonblocking io and as you mention per char input like getch from C for instance. Libraries like [copperline](https://github.com/srijs/rust-copperline) use low level c bindings to get around this and implement the behaviour of readline. On the shell I had been writing before I implemented some of this on my own in C but it was some nitty gritty work. Not saying it can't be done, just expect to be doing a lot of unsafe for it to work.

Though that's a fun challenge that would be fun to implement.

**Comment by hexsel** [comment]
@stratact I never thought I'd get away from good ol' Bash, but Fish Shell just did that, and it's 90% because of their command line interface.  Can't go wrong there :)

**Comment by Ticki** [comment]
I prefer zsh over fish

_now kill me_

**Comment by stratact** [comment]
@hexsel it does seem to have more innovation than any other shell, which is what we desire most in Redox.

**Comment by skylerberg** [comment]
I am not a big fan of fish because I think it sacrifices too much in the name of simplicity. That said, if we start of going in the direction of fish, there is still plenty of work for us to do and I am totally okay with it.

**Comment by mgattozzi** [comment]
@Ticki Hey I'm with you on that one. Still we can get the best of
Fish/ZSH/Bash etc etc

**Comment by stratact** [comment]
Right, we can pick the best parts from each shell. Doesn't have to be all Fish.

**Comment by MovingtoMars** [comment]
Should the GNU readline-like functionality be implemented in ion itself, or a separate crate?

**Comment by hexsel** [comment]
@skylerberg you mean generally, or the commandline interface? I've meant the latter, where fish is actually quite elaborate.

i agree some stuff is not perfect in fish, e.g. their error handling is atrocious, specially if you want a stop-on-error script.

**Comment by Ticki** [comment]
@MovingtoMars,

> Should the GNU readline-like functionality be implemented in ion itself, or a separate crate?

If it _can_, it _should. So I guess, the answer is: yes, it should be a separate crate.

**Comment by hexsel** [comment]
examples: Fish has a simple script for prompt, lots of plugins inc an amazing one for git, you can jump words back and forth even on OSX, you can set the repeat rate for keypresses, it uses colour quite well (and occasionally excessively).

**Comment by skylerberg** [comment]
@hexsel I meant generally. Fish does quite a bit for the command line interface

@MovingtoMars @Ticki I think it will be simpler to put it in the same crate so that it can more easily make use of thinks like shell history, shell variables, information about builtin commands, etc. That isn't to say that we couldn't do it in a separate crate, but I don't think we will gain a lot from doing that.

**Comment by MovingtoMars** [comment]
Hey all, just letting you know that I'm working on a readline replacement using termion. Typing, editing and history work quite well, and primitive filename completion is working (with a couple of bugs). There's just some more work and polishing to do before I'm ready to publish.

**Comment by msehnout** [comment]
@MovingtoMars When do you plan to publish it? I was thinking of implementing the same, but I don't want to duplicate the work, so I'll wait for your library.

**Comment by MovingtoMars** [comment]
I'll try to get it done in the next few days. There's just a bit of work I have to do. For example, word boundaries don't take into account quoted words and escaped spaces yet.

**Comment by MovingtoMars** [comment]
Here we go: https://github.com/MovingtoMars/liner
Keep in mind it's in early stages and many things need improvement.

**Comment by jackpot51** [comment]
@MovingtoMars @skylerberg I am working on integrating liner, it is fairly straightforward because everything we need is contianed in src/input_editor.rs

**Comment by dcampbell24** [comment]
@jackpot51 @MovingtoMars @skylerberg https://github.com/kkawakam/rustyline looks like it may be a more mature and feature complete project that is also under an MIT license.

**Comment by jackpot51** [comment]
Liner has provided a complete component for this,  closing
