### ISSUE TITLE
>> not implemented?

### ISSUE THREAD

**Issue by mallochine** [redox-os/ion#300]
I was trying out:

"echo asdf >> asdf"

and this didn't work? "wc -l  asdf" doesn't give me any lines.

**Comment by polymetric1** [comment]
did you actually look at the file? (`cat asdf`) maybe it's `wc` that's not working.

**Comment by mmstick** [comment]
That's odd. It would seem that redirection is somehow broken?

**Comment by huntergoldstein** [comment]
It might be a problem with `echo`; the following works as expected.
```
$ cat <some_file> >> asdf
$ cat asdf
<contents of some_file>
```

**Comment by mallochine** [comment]
```
# touch asdf
# cat asdf
# echo "blah" >> asdf
blah
# cat asdf
#
```

**Comment by mmstick** [comment]
That would make sense. Builtin commands don't support redirection or piping yet.

**Comment by mallochine** [comment]
oh ok yeah, cat works fine. echo doesn't.

**Comment by mmstick** [comment]
I think we should instead execute `/usr/bin/bash` when redirection/piping is required.

**Comment by huntergoldstein** [comment]
How would that work? Doesn't that defeat the purpose of writing a shell? Am I missing something?

**Comment by mmstick** [comment]
This is actually what Ion does at the moment when it detects that piping is required. It executes the external echo command rather than the builtin echo command. There's just no check to also see if redirection is required.

**Comment by mmstick** [comment]
Try again with the latest master. This issue should be fixed now.

**Comment by huntergoldstein** [comment]
WFM on master now; sorry, I misunderstood your comment to mean _any_ time redirection / piping is required versus just for `echo`.
