### ISSUE TITLE
bash-compatible functions?

### ISSUE THREAD

**Issue by mallochine** [redox-os/ion#301]
Hi,

Was trying out ion on some of my bash stuff. Probably intentional....but do we have any plans to support bash-style functions? Just helps with backward-compatibility.

test code:

```
# test.sh
hello() {
  echo "hi"
}
hello
```

**Comment by mmstick** [comment]
The problem with this is that functions in Ion are argument-checked to ensure that the correct number of arguments were supplied, and that's not the only place where syntax is very different. Arguments are contained within arrays, not variables.

**Comment by mmstick** [comment]
Closing as we are not going to implement bash-compatible functions.
