### ISSUE TITLE
Support Multiple Assignments & Swapping Variables

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#305]
I think it'd be nice to also support multiple assignments, which therefore would open the door to swapping values in a single statement.

```ion
$ let a b c = [ 1 2 3 ]
$ echo $a
1
$ echo $b
2
$ echo $c
3
$ let a b = [ $b $a ]
$ echo $a
2
$ echo $b
1
```

**Comment by huntergoldstein** [comment]
We could support packing / unpacking arrays [as done in Python{2,3}](https://anothercomputingblog.blogspot.com/2010/05/functional-unpacking-style.html).

**Comment by mmstick** [comment]
I'm looking into this right now.

**Comment by mmstick** [comment]
I have a solution almost ready. I just need to write some tests and it'll be pushed.

**Comment by mmstick** [comment]
Complete ( https://github.com/redox-os/ion/commit/a6fd25147ac12685b3a650d8478724f7bff80fb1 )
