### ISSUE TITLE
inline tilde expansion

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#307]
`cd ~/f<Tab>` ->  `cd ~/foo/`. this expansion does not occur. using the full path works: `cd /home/james/f<Tab>` -> `/home/james/foo/`.

edit: in liner: https://github.com/MovingtoMars/liner/issues/34

**Comment by mmstick** [comment]
If no one else wants to look into this, I'll look into this tomorrow.

**Comment by mmstick** [comment]
I am officially beginning my investigation into fixing this.

**Comment by mmstick** [comment]
Almost have it working.

**Comment by mmstick** [comment]
It's working in my local branch now. I will have the commit pushed shortly after reviewing my changes.

**Comment by mmstick** [comment]
Issue resolved (https://github.com/redox-os/ion/commit/dd42c629caf7e19f28cc80dc80c9b239ecd7612c)
