### ISSUE TITLE
Use bitflags instead of home-rolled constants for flags

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#308]
# Problem
- Rules and bit fiddling can be difficult to remember for bitflags; the more someone has to think through and remember how this all works the more likely they are to make a mistake
-  It is harder to debug which flags are set when: most methods either are prone to human error or are tedious

# Solution
We could make use of the [bitflags crate](https://docs.rs/bitflags/0.9.1/bitflags/) which should be as efficient as just using constants but increases quality of life (see above).

**Comment by mmstick** [comment]
Would you be interested in trying this out?

**Comment by huntergoldstein** [comment]
Sure!

**Comment by mmstick** [comment]
Great! Currently investigating how difficult it would be to implement signal handling in Ion with `tokio-signal`.

**Comment by mgmoens** [comment]
Have you actually thought about using something like the [nom](https://github.com/Geal/nom) crate? It might make certain things more readable. It would, however, change the whole structure of the project.
