### ISSUE TITLE
Obtain Length of Array/String

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#315]
We need to come up with a syntax for obtaining the length of an array/string. Arrays are counted by elements, and strings are counted by graphemes. Perhaps this approach can be taken?

```ion
let length = $len(string)
let length = @len(array)
```

**Comment by huntergoldstein** [comment]
That would probably be the easiest to implement; I don't see an immediate issue with this.

**Comment by mmstick** [comment]
I'll have this implemented soon.

**Comment by mmstick** [comment]
Implemented ( https://github.com/redox-os/ion/commit/14d6b336ca342df7dc012f7168f6d731f301e956 )
