### ISSUE TITLE
breaks awk

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#319]
awk -v x=$x '{ if (1) print $1 }' myfile

this `awk` command should print every line in `myfile`, instead it ignores `myfile` and waits for input

**Comment by mmstick** [comment]
I get a different behavior on my end:

```ion
mmstick:/home/mmstick/Sources/ion# awk -v x=$x '{ if (1) print $1 }' Cargo.toml
awk: cmd. line:1: { if (1) print $1 } Cargo.toml
awk: cmd. line:1:                          ^ syntax error
```

**Comment by aeosynth** [comment]
that's probably another bug, try a file without a `.`

**Comment by mmstick** [comment]
Seems to be caused by the `(` character.

**Comment by mmstick** [comment]
The pipeline parser had the same issue as the statement splitter that was fixed earlier. Issue is now resolved.

**Comment by aeosynth** [comment]
thanks again!

**Comment by mmstick** [comment]
As a side note, the following is an Ion equivalent to that awk command:

```ion
for line in $(cat myfile)
    echo @split(line)[0]
end
```

**Comment by jackpot51** [comment]
Ion is damn powerful :)
