### ISSUE TITLE
restrict ./ expansion to filenames

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#321]
`./f<Tab>` shows all commands beginning with 'f', and it shows files starting with 'f'; it should only show the files

**Comment by mmstick** [comment]
i had noticed this myself, but I haven't been sure as to why liner is providing binaries in $PATH as completion options when a completion begins with `./`.

**Comment by huntergoldstein** [comment]
I believe this is happening because of [not properly recognizing that `./` is the start of a file](https://github.com/redox-os/ion/blob/c7c66eea7acc4d605fe6b006d2aa365063126728/src/shell/mod.rs#L100). Investigating further.
