### ISSUE TITLE
String/Array Methods Discussion

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#322]
The purpose of this issue is to discuss the current and future direction and implementations of methods in Ion. The current idea is that methods should be assigned based on the type that they return, which means that if a method returns a string, then it should be a string method, whereas if the method returns an array, then it should be an array method. Methods implemented are below:

# String Var Methods

- $join(array[, pattern])
    - Join an array into a string with an optional pattern
    - Default pattern is a space
- $len(string)
    - Returns the number of graphemes in the string
    - Should this also support arrays? And if so, how?
- $len_chars(string)
    - Returns the number of chars in the string
    - **Not implemented**
- $len_bytes(string)
    - Returns the number of bytes in the string
- $len_array(string)
   - Possible method for getting length of arrays?
- $trim(string)
    - **Not Implemented**
    - Performs the trim method on the given variable

# Array Var Methods

- @split(string[, pattern])
    - Split a string with an optional pattern
    - Default pattern is to split by whitespace characters
    - Patterns should probably support regex, but currently don't
- @len(array)
    - **This method should probably be migrated as a string method**

**Comment by mmstick** [comment]
# Inline Expression Methods?

Should we support inline methods in order to execute actions in the parser without needing to store data as temporary values? What syntax would we support, if we did choose to pursue this feature?

## Possible Syntax

While we currently use `method(variable, arguments)` for applying methods to variables, we could perhaps use `method[expression, arguments]` for applying methods to inline expressions, which is just exchanging the parenthesis for brackets.

- $method{expression, arguments}
    - `let license = $open[LICENSE]`
    - `let license = $head[LICENSE, 10]`
- @method{expression, arguments}
    - `let license = @lines[$(cat LICENSE)]`
    - `let license = @lines[$open[LICENSE]]`
    - `let license = @split[$open[LICENSE], '\n']`

**Comment by huntergoldstein** [comment]
Would the difference be that inline expression methods are expanded before the pipeline is executed? To me this seems like how methods ought to function in general. I was very confused on the syntax of `@split` and `$join` initially.

**Comment by mmstick** [comment]
Yes, methods always occur during the parsing stage, rather than pipeline execution. An inline expression would prevent the need to round trip outputs to variables.

**Comment by huntergoldstein** [comment]
I'm wondering if there's a benefit to making all methods "inline." As you have in your examples it makes composing methods much simpler and it would eliminate the need for separate `len_X` functions.

**Comment by mmstick** [comment]
I have thought about just generalizing the existing methods to make them inline, but I'm unsure on whether or not that's a good approach. If a method requires an array, and you pass a string, should it treat the string as a single-element array? If a method requires a string, and you pass an array, should it join the array with spaces between elements?

**Comment by huntergoldstein** [comment]
Both of those seem like reasonable behavior. I'm kind of worried because this would introduce implicit type-casting, in a sense, whereas current Ion will treat "type errors" as the empty string.

**Comment by mmstick** [comment]
@huntergoldstein It could be possible to specify a type kind within the method parameters, in order to make the distinction explicit between an expression, array var, or string var.

**Comment by huntergoldstein** [comment]
So the arguments would be typechecked?

**Comment by aeosynth** [comment]
i'd like methods for matching strings by literals or regular expressions, and functional array methods like map/reduce

**Comment by aeosynth** [comment]
string methods always returning strings makes them awkward to use as conditionals:

```
# if test 1 -eq $contains('asdf', f); echo true; end
true
```

will there be both this string method, and a builtin method?

**Comment by mmstick** [comment]
@aeosynth That's the plan.

**Comment by aeosynth** [comment]
cool, but now the `$contains` string method seems redundant.
