### ISSUE TITLE
more unescaping

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#323]
touch 'x$()'
    cat x<Tab> # cat x$\(\)
    ion: invalid string method: \
    cat: x: No such file or directory

perhaps there should be an exhaustive test of characters which need  escaping

**Comment by mmstick** [comment]
Escaping occurs [here](https://github.com/redox-os/ion/blob/master/src/shell/completer.rs#L69), so each character that we want escaped needs to be added here. If we are to add `$`, then we probably also want to add `@`, `{`, and `}`, `<`, `>`, and `;`.

**Comment by mmstick** [comment]
Resolved
