### ISSUE TITLE
Documentation Discussion

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#325]
# Source Code Documentation

I'd like for others that attempt to read through the source code of Ion to post in here when they find a section of code that they don't understand, or where documentation is inadequate/wrong, so that we can work to get all the potentially-confusing code properly documented for future generations of Ion users and developers.

# Ion Syntax Documentation

Likewise, any users of Ion that find documentation lacking in the readme should report here should we need to write some better documentation, add more examples, explain how some things work and why. That sort of thing.

**Comment by vmchale** [comment]
I'm an ion user, but a few things that I have noticed so far (that prevent me from switching for daily use):

1. I'd really like some sort of idiomatic way to process command line flags in shell scripts.

2. Documentation of completions would be quite nice, especially for those of us who write Rust :)

3. If there's an equivalent of `crtl-r` or the like, I'd like documentation for that. If not, documentation of how to set keybindings so that I could use e.g. `fzf`.

4. Documentation of something equivalent to `.bashrc`. I'd like to be able to set stuff at runtime and whatnot, especially `PATH`. 

And thanks to all the contributors for what you've done so far!

**Comment by aeosynth** [comment]
There's no documentation on enabling history or customizing the prompt.

**Comment by mmstick** [comment]
@vmchale 

1. Do you mean something like getopt?
2. I'll see what I can do about writing more code documentation for that section. Completions are largely handled by [liner](https://github.com/MovingtoMars/liner) though. One thing to note is that the `start` input parameter [in the completions method](https://github.com/redox-os/ion/blob/master/src/shell/completer.rs#L32) will contain the value currently entered in the prompt after pressing tab.
3. That would be handled entirely by the liner crate, which doesn't yet support that. There's also no way to set key bindings at the moment.
4. We currently use `~.ionrc`, but I plan to move that to `~/.config/ion/initrc` in the near future.

@aeosynth If you type and enter just `let` by itself, you will get a list of variables and arrays set in the shell. Setting `let HISTORY_FILE_ENABLED = 1` will enable history. The PROMPT variable currently isn't very user friendly to interface with, as it contains a raw string with the already-expanded form of what you'd be use with in other shells.

**Comment by mmstick** [comment]
Just added code documentation for the [shell::completer](https://github.com/redox-os/ion/blob/master/src/shell/completer.rs) module.

**Comment by aeosynth** [comment]
Yes I figured out how to enable history, but I still feel the process should be documented. Off topic, why isn't history enabled by default?

**Comment by mmstick** [comment]
@aeosynth It's just not been changed to enable it by default yet, as it was originally broken, but has long since been fixed.

**Comment by mmstick** [comment]
With the XDG app dir support having been landed, you should notice when launching the shell that the initrc and history files are reported as being in new, proper directories.

Initrc: $HOME/.config/ion/initc
History: $HOME/.local/share/ion/history

Also, history is enabled by default now.
