### ISSUE TITLE
Syntax Discussion: $(), $[], @(), @[], $(())

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#329]
There's an issue that we will need to resolve before Ion's officially ready for the greater public, and that is solidifying our syntax. So far, the syntax has been moving along pretty well and I don't expect much to change before the big 1.1 release, but there is one glaring problem that needs to be resolved: **$(command args..)** is incompatible with **@[command args...]**, and this will cause issues with syntax design in the immediate future.

So, there are two ways that we can go about fixing this:

1. Follow the Oil Shell
  - Change **$()** into **$[]**
  - Change **$(())** into **$()**
2. Do the opposite of the Oil Shell
  - Change **@[]** into **@()**
  - Change **$(())** into **$[]**

**Comment by mmstick** [comment]
Leaning more towards changing @[] into @(), and $(()) into $[] myself, given that there's already a lot of precedence for using () for process expansions.

**Comment by huntergoldstein** [comment]
I agree; `@(...)` seems more intuitive to me in terms of "subshell that becomes array."

**Comment by mmstick** [comment]
Yeah, I will switch the syntax over soon. Better to fix it now rather than wait for it to become a problem later.

**Comment by mmstick** [comment]
@huntergoldstein I've now changed `@[]` into `@()`. How do you feel about changing the arithmetic expression from `$(())` to `$[]`?

**Comment by huntergoldstein** [comment]
Perfectly fine by me.

**Comment by andychu** [comment]
FWIW for Oil at least there is a pretty obvious motivation for the opposite style: to be consistent with arrays and parenthesized expressions.

In bash you can do this:

- `if (( a > b ))`
- `for (( i = 0; i < n; i++ ))`

Oil will change it to the obvious:

- `if ( a > b )`
- `for ( i = 0; i < n; i++ )`

In Oil an array literal is:

    a = [ ls /bin /lib *.py ]  # an array of words that you can execute later

So I think `$(a > b)` and `$(1 + 2)` and `$[ls /bin/ /lib/ *.py]` is a lot more consistent with itself than the other way around.  Of course I don't know what Ion needs to be consistent with.

**Comment by mmstick** [comment]
@andychu Ion doesn't need to be consistent with anything, so I think `$()` and `@()` are a better approach for us. We don't support `(( a > b ))` or `(( i = 0; i < n; i++ ))`, so I don't think that will be an issue for us. I know for certain that we won't ever support the latter expression, in the same way that Rust doesn't support such an expression.

Haven't quite decided if we will support a boolean expression syntax, or what syntax we would use if we did decide to. I have been thinking about supporting prefix/polish notation as solution in addition to the test command though, such as:

- ```if > a b; echo true; end```
- ```if > (+ a b) c; echo true; end```
- ```if > + a b c; echo true; end``` <- same as above

Has a bonus of being easier for a computer to parse, and eliminates the need for parenthesis.

**Comment by huntergoldstein** [comment]
@mmstick, @andychu brings up a good point about the consistency of all of these sub-shell expressions. We might want to keep an open mind about this and/or somehow get user feedback about the syntax.

**Comment by andychu** [comment]
Also I would consider what your subshell syntax is, i.e. `( echo hi )` in POSIX sh as opposed to `$(echo hi)`, which is a command sub.

I would highly, highly recommand against using `( echo hi )`.  Because that is the #1 feature of shell that I've seen misused in the wild.  `{ }` means grouping, but people use `()` instead because `()` "obviously" means grouping and `{}` is hard to get right because you need a trailing semi-colon.

For Oil it's just `shell { echo hi; echo bye }`, and `do { echo hi; echo bye }` for pure grouping without a subshell.

**Comment by mmstick** [comment]
@andychu `( echo hi )` is a syntax error in Ion, and I have no plans to ever support that as a syntax feature. If Ion were to emulate this, it would potentially be very similar to what you have, but more like so: ```shell; echo hi; echo bye; end```, as we designate the `end` keyword as the end of a scope.

**Comment by mmstick** [comment]
Explicit array syntax has now been implemented.
