### ISSUE TITLE
Implement &| (Stdout + Stderr Piping)

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#331]
At the moment, `&|` is equivalent to `^|`, in that it only maps stderr, instead of both stdout and stderr. This will be important to resolve before the 1.1 release.

**Comment by huntergoldstein** [comment]
This looks like it works as expected (aside from a strange extra newline)
[![asciicast](https://asciinema.org/a/N0xTAlfQe2bl3OaRuiB7bgQmu.png)](https://asciinema.org/a/N0xTAlfQe2bl3OaRuiB7bgQmu)

**Comment by mmstick** [comment]
I believe it's the piping (&|) that specifically doesn't work, as it just copies the behavior of piping stderr (^|)

**Comment by huntergoldstein** [comment]
Confirmed: I don't think `parser::pipelines` recognizes it as it looks like it parses `foo &| bar` as "fork `foo` to the background, run `| bar`."

**Comment by mmstick** [comment]
The main issue is that there's no way to specify two file descriptors for the stdin of the next command in line. You may only specify one file descriptor at a time, which means that you can only either listen to stderr, or stdout. The fix would entail somehow creating a new, internal file descriptor in memory as a buffer, and supplying that temporary file descriptor for the stdin of the next command.

**Comment by huntergoldstein** [comment]
Yup I realize that now; I thought I could get away with just `dup` trickery.

**Comment by mmstick** [comment]
I was thinking that we could perhaps use [memfd_create](https://docs.rs/nix/0.8.1/nix/sys/memfd/fn.memfd_create.html). It will create a memory region and return a file descriptor to it, which we could map the stdout and stderr to, and then the stdin of the next process could be that region.

**Comment by huntergoldstein** [comment]
How about for Redox? Part of the hope of just using `dup` was that there are `dupN` syscalls for Redox.

**Comment by mmstick** [comment]
@huntergoldstein Do you think you could implement it with the `dup` syscalls?

**Comment by huntergoldstein** [comment]
I think what `memfd_create` does can also be done with pipes, which I would assume Redox has _some_ form of. I'll have to play around with it more, I've been looking at updating `statement.rs` and `pipeline.rs`.

**Comment by huntergoldstein** [comment]
Taking a closer look now; I tried to rewrite `statements.rs` and `pipelines.rs` over the weekend, I'll open up an issue with my findings.

**Comment by huntergoldstein** [comment]
It seems like the best way to do this is just with pipes versus messing around with `dup`. After trying to do this manually for a while I found [`os_pipe`](https://docs.rs/os_pipe/0.5.1/os_pipe/) which appears to work. I'm going to take a look at the source of the library to figure out why `os_pipe` worked but my approaches didn't and figure out what to do for Redox (I could submit a patch for Redox; considering this).

**Comment by huntergoldstein** [comment]
I managed to get this to work without `os_pipe` (though I quite like the interface). The main fun involved the `O_CLOEXEC` flag: setting the flag prevents the child process from owning the pipes. This seemed to matter for short pipelines like `ls | wc -l`, where the output of `ls` was eaten and `wc -l` would wait forever for input on `stdin`, but not for pipelines like `yes | tr '[a-z]' '[A-Z]'` which would output a never-ending stream of `Y`.

I changed the approach for setting up the process communication (all pipes) so I'm going to make sure that the approach works using Redox's syscalls.

**Comment by mmstick** [comment]
I wonder if there'd be any benefit in Redox implementing `memfd_create` as a possible solution in the future.

**Comment by mmstick** [comment]
We do need to figure out how to get commands like `yes | head` to work correctly as well. The `yes` command is supposed to quit when the `head` command quits.

**Comment by huntergoldstein** [comment]
That's part of #29 correct? I remember it being mentioned that `SIGPIPE` handling isn't quite working.

**Comment by mmstick** [comment]
From what I understand, it's a signal that the kernel sends automatically when the fds close, so it's likely that processes aren't closing in the right order.
