### ISSUE TITLE
Move `calc` logic to a separate crate

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#337]
# Pros
* Permits faster iteration and more experimentation
* Sufficiently decouples the current `calc` monolith from the rest of `ion`
* Allows other applications to easily make use of `calc`'s logic

# Cons
* Adds another dependency
* Version differences may cause incompatibilities (for example if some byte sequence is always special in `ion` but is used for a particular purpose in `calc`)

**Comment by jackpot51** [comment]
Also, cleans up the fact that there are two other implementations:
The original one - https://github.com/redox-os/extrautils/blob/master/src/bin/calc.rs
GUI version - https://github.com/redox-os/orbutils/blob/master/src/calculator/main.rs

**Comment by mmstick** [comment]
I wouldn't really consider being a dependency as a con. I would consider it a pro though, because it's still going to be a dependency, regardless of whether or not it's maintained within Ion or externally, and by being developed as a standalone library outside of Ion, it is certain to see more exposure / testing / feature additions over time that could be beneficial to Ion.

**Comment by huntergoldstein** [comment]
Could we make a repository under the `redox-os` organization for this?

**Comment by jackpot51** [comment]
Sure, who would like to commit it?

**Comment by huntergoldstein** [comment]
I would be willing; what are the steps I need to take?

**Comment by huntergoldstein** [comment]
I have a separate crate ready to go [here](https://github.com/huntergoldstein/calc) with some touch ups, unit tests, benchmarks. Still need to set up CI (we want to use `homu` right? otherwise I'll just set up Travis) and it hasn't been published as a crate. I can transfer ownership to _someone_ in the Redox org then publish it, or just keep it under my account. I don't feel great about the later as it isn't really my work.

**Comment by jackpot51** [comment]
@huntergoldstein would you maintain this? If so, I can give you admin access to a `redox-os` repository

**Comment by huntergoldstein** [comment]
I'd be able to maintain it.

**Comment by mgmoens** [comment]
This happened I guess?

**Comment by mmstick** [comment]
And so it did, so I'll close this now.
