### ISSUE TITLE
Single-Element Arrays & Explicit Copying of Arrays

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#339]
It's currently not possible to create an array with only a single element. Any attempt to do so will merely store that array as a string. Which brings us to the question: should we solve this by having array variable lookups fall back to string variable lookups, or follow the Oil shell and make the act of copying an array explicit? If we pursue to make array copying explicit, that would entail an extra step in the `let` command to see if the first and last character are `[` and `]` respectively, which would designate to store the value in an array. What are your thoughts?

### Explicit Array Copying

Personally, I may be leaning more towards this one, myself.

```ion
let array = [ 1 ]
let array_copy = [ @array ]
let string = @array
```

### Implicit Array Copying w/ String Fallback

```
let string = [ 1 ]
echo $string @string # <- Same output for both
let array = [ 1 2 ]
let array_copy = @array
```

@huntergoldstein @mgmoens @jackpot51

**Comment by huntergoldstein** [comment]
:+1: for explicit array copying, though I wonder how that would interact with the behavior in #322. For example, if we had the following (imagine we had some `@reverse` method):
```
$ let array = [ 1 2 3 ]
$ echo @reverse(@array)
3 2 1
```
If `@reverse(@array)` gets evaluated inline as discussed in #322, does it become a string, then gets re-parsed as an array and reversed? Or does it remain an array while it is passed to `@reverse`?

**Comment by mmstick** [comment]
@huntergoldstein The behavior there would be the same as before -- it's treated as an array of arguments when used within a command. The behavior discussed here is exclusively regarding how the `let` command handles array expressions. If the supplied expression is not wrapped within `[ expr ]` then it will be combined into a string.

**Comment by mmstick** [comment]
If there's no opposition to explicit copying, I think we can pursue implementing it soon.

**Comment by mmstick** [comment]
Okay, I am beginning work on this now. I should have a commit out later today that implements explicit copying, and I'll update the README accordingly.

**Comment by mmstick** [comment]
Found a parsing bug:

```ion
mmstick:/home/mmstick/Sources/ion# echo [@(echo one)]
thread '<unnamed>' panicked at 'ion: fatal error with syntax validation: unterminated array process', src/parser/shell_expand/words.rs:784
```

It's the only blocker for the explicit array copying at the moment ( that I know of). I will investigate the cause and have the fix issued alongside explicit array copying, soon.
