### ISSUE TITLE
Unify stdin and arguments

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#34]
xargs have always been a huge pain. I suggest that we unify stdin and arguments. Any ideas?

**Comment by polymetric1** [comment]
How would this work? Maybe piping could just add an argument linking to a temp file?

**Comment by Ticki** [comment]
The arguments could be sent as stdin ending on a SOH (^A) followed by the "real" stdin.

**Comment by Ticki** [comment]
So the stdin for `echo yay | rm -rf --no-preserve-root / ~/*;` would look somewhat like this to the program:

```
-rf^]--no-preserve-root^]/^]~/*^Ayay
```

**Comment by Ticki** [comment]
Another possibility would be multiple pipelines, which would really reduce the limits of the command line.

**Comment by polymetric1** [comment]
Multiple piplines might be hard to manage, depending on how it's implemented. It might hurt application compatibilty, too

**Comment by Ticki** [comment]
@polymetric1 Well, you can just have a main pipeline, which *nix programs use solely.

**Comment by polymetric1** [comment]
But what about redox -> unix? I guess they could just check which OS and change their parser based on that

**Comment by Ticki** [comment]
Well, restricting us to one to one compatibility (unix -> redox AND redox -> unix), will restrict us a lot, so I would rather avoid that.

**Comment by jackpot51** [comment]
This is a bad idea. I should not have to explain why this is a bad idea, it should be obvious.

The distinction between stdio and arguments is a critical, strongly typed distinction that comes from the following fact:

stdin is a file. This file is setup by the terminal or terminal emulator (/dev/tty for example) and tells the application which bytes it should process as streaming input. These bytes are delivered in a blocking, unpredictable manner.
argv is an array of strings. They are setup by the shell and tell the application how to change its behavior in a static way. They are not streaming, they are not a file. They are available immediately.

Don't spout "it will restrict us to stay compatible." *All* major operating systems, Linux, OS X, Unix-like, Windows, etc, provide a distinction between these two forms of input.

When you say "multiple pipelines," this is technically feasible in many shells, you can setup file descriptor 3, 4, etc to a file that the application can then use.

My advice, use `xargs` and close this issue immediately

**Comment by polymetric1** [comment]
Good call @jackpot51. I think it's good that this was at least discussed, but it doesn't really make sense.

**Comment by Ticki** [comment]
Well, personally I don't like the first idea, I gave, because ... yeah, it's fucked. A bad idea. But I believe, that utilizing secondary pipelines for arguments, is a good idea, since it solves the very problem in a general manner.

**Comment by skylerberg** [comment]
@Ticki Can you give an example of what this might look like at the command line that shows it solving a problem you have with xargs?
