### ISSUE TITLE
Ctrl-C while running a program exits the shell

### ISSUE THREAD

**Issue by dead10ck** [redox-os/ion#343]
**Reproduction**: Start a long-running program, e.g. `find / -name foo`, and hit Ctrl-C while it's running.

**Expected behavior**: The shell should send a signal to the running program to terminate and go back to the prompt.

**Actual behavior**: The shell exits.

**Build information**:

```sh
[I] ~/.c/p/ion (master ± ) ∫ rustc -V
rustc 1.18.0 (03fc9d622 2017-06-06)
[I] ~/.c/p/ion (master ± ) ∫ git rev-parse HEAD
f5bb8ebd5cf6e0e3e007758989982e82d1070131
[I] ~/.c/p/ion (master ± ) ∫ uname -a 
Linux opendns-arch-x1 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux
```

**Comment by mmstick** [comment]
> f5bb8ebd5cf6e0e3e007758989982e82d1070131

I don't recognize that commit, and cannot find it in our history. How did you obtain Ion?

```sh
mmstick:/home/mmstick/Sources/ion# git rev-parse HEAD
4cc422eb383653333a744b0266dc3f35ebd36c7b
```

Signal handling is implemented and works fine on my end, including with exiting out of control flow logic and the prompt.

**Comment by dead10ck** [comment]
I got it from the Arch User Repository, which downloaded a shallow commit of 1.0.3. I tried this out with the latest git head, and Ctrl-C actually made it crash on this build:

```sh
# yes
y
y
y
...
y
y
y
y
y
^Cion: received SIGINT (Ctrl+C)
ion: child ended by signal
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unable to set Termios attribute.") }) }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I was not able to reproduce again, but even on future iterations, it still exits ion:

```sh
y
y
y
^Cion: received SIGINT (Ctrl+C)
ion: child ended by signal
dead10ck:/home/dead10ck/src/rust/ion# ⏎
[I] ~/s/r/ion (master) ∫
```

**Comment by dead10ck** [comment]
Interesting! I just discovered that `ion` is still running in the background, even though my terminal went back to `fish`.

**Comment by mmstick** [comment]
The 1.03 release does not feature signal handling. It's been a long time since we have made a release, and a lot of features have been implemented since then, so I would recommend always testing against the latest master, because [we move very quickly](https://github.com/redox-os/ion/commits/master). Also note to not use `cargo run` with Ion because that seems to cause an issue with termion when we are handling signals.

**Comment by dead10ck** [comment]
Oh, I see! It seems to work when I run it directly, instead of via `cargo run`. My apologies, that's not something I would have expected :) feel free to close this issue, then. I look forward to the next release.

**Comment by mmstick** [comment]
Be warned though that two breaking changes will occur in the next release compared to 1.0.3. `@[]` has been changed to `@()`, and to set an array with `let`, that array must be wrapped within `[]`, else it will be coerced into a string, due to moving towards explicit array copying syntax.

**Comment by dead10ck** [comment]
Hmm, on some further thought, that seems like it could be a separate issue. Why does it not work from `cargo run`? Does that mean, for instance, that if I run ion from a bash script as a regular subprocess that I cannot expect ion to handle `SIGINT` correctly?

**Comment by dead10ck** [comment]
@mmstick confirmed, this is an issue:

```sh
#!/usr/bin/env bash

./target/release/ion <(echo "cat /dev/random | tr -dc '[:alnum:]' | pv -qL 1K") &
pid=$!

sleep 3

echo "Killing ion"
kill -s SIGTERM $pid
echo "Killed ion, exit: $?"
```

This will say that `kill` was successful, but the background processes are still going and have to be forcefully killed.

**Comment by mmstick** [comment]
May want to open that as a separate issue

**Comment by dead10ck** [comment]
I updated #344. I'll let you figure out what the underlying issue is :)
