### ISSUE TITLE
Incomplete Signal Handling

### ISSUE THREAD

**Issue by dead10ck** [redox-os/ion#344]
- [x] Implement SIGINT Handling
- [x] Implement SIGTERM Handling
- [ ] Ensure that SIGPIPE is working correctly
- [X] Implement SIGSTOP Handling
- [X] Implement SIGCONT Handling
    - [x] Implement `bg`
    - [ ] Implement `fg`
- [ ] Implement SIGHUP Handling
- [ ] disown
- [ ] suspend

**Comment by mmstick** [comment]
Works fine here:

```sh
mmstick:/home/mmstick/Sources/ion# yes | head -n 10
y
y
y
y
y
y
y
y
y
y
^Cion: received SIGINT (Ctrl+C)
mmstick:/home/mmstick/Sources/ion# 
```

**Comment by dead10ck** [comment]
You hit Ctrl-C, of course it exited. It should exit on its own. Try that out in a different shell.

**Comment by dead10ck** [comment]
The "Signal madness" siection of [this article](http://linusakesson.net/programming/tty/index.php) has a pretty good list of all the signals that a shell should handle.

**Comment by mmstick** [comment]
Currently working on implementing SIGTERM handling.

**Comment by mmstick** [comment]
I have SIGTERM handling working, and will be uploading the work soon.

**Comment by mmstick** [comment]
You can try out the new SIGTERM handling now ( https://github.com/redox-os/ion/commit/c32cd6d7f7a1f679d43a7d7277a5b20265ca7d96 ). SIGKILL signals apparently cannot be intercepted as the kernel handles them directly. The same goes for SIGPIPE, but I'm not quite sure why the kernel isn't sending the SIGPIPE signal yet.

**Comment by mmstick** [comment]
Investigating implementing SIGTSTP now.

**Comment by mmstick** [comment]
SIGTSTP is now implemented, alongside the `jobs`, `wait`, and `bg` commands. https://github.com/redox-os/ion/commit/d9506aa6c8a7851981547736161a168ccf0ad69b

**Comment by mmstick** [comment]
Closing this as I'd rather not keep posting updates to duplicate issues. See issue #29

**Comment by dead10ck** [comment]
@mmstick  I'm not sure they are duplicate issues. Job control of course makes heavy use of signals, but working signal handling are kind of a prerequisite to job control. And what about signals that have nothing to do with job control? Did you get `SIGPIPE` working? How about `SIGHUP`? `SIGQUIT`? `SIGCHLD`? `SIGWINCH`? I realize several of these are typically managed by the kernel, but you should still make sure that the shell is playing nice with the kernel and that everything is working as it should.

**Comment by mmstick** [comment]
- SIGPIPE isn't working yet. Not sure how to go about fixing that yet.
- SIGHUP is being handled, and you may tag background processes to not receive SIGUP with `disown -h`.
- Not doing anything SIGWINCH, SIGCHLD is ignored in shell, and SIGQUIT is also not being handled

All of the signal handling code is found in the [signals module](https://github.com/redox-os/ion/blob/master/src/shell/signals.rs)

**Comment by dead10ck** [comment]
So given all of that, do you think it's accurate to say this issue is closed?
