### ISSUE TITLE
empty string arguments

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#345]
the empty string is not treated as a valid argument:

```
# touch a
# rename '' 0 a
rename: not enough arguments
# fn foo x; end
# foo ''
ion: function takes 1 arguments, but you provided 0
```

**Comment by huntergoldstein** [comment]
Taking a look at this; it looks like the problem stems from single quotes (and double quotes) only being recognized as the end of a word token, not the start. See:
```
$ fn foo x; end
$ foo ""
```
also failing.

The parser in `parser::shell_expands::words` just sets the quote flags and keeping looking for other characters to end off a `WordToken`. Simple fix for single quotes, not so easy for double quotes as it creates issues when the boundary of a word token is at the beginning of a double quoted string, i.e. something like:
```
$ touch "$FOO"
```
might cause issues. Keyword here is might: investigating in the morning.

**Comment by huntergoldstein** [comment]
So adding a similar rule for double quotes creates these odd `WordToken::Normal("")` artifacts, for example the above would become:
```
[Normal("touch"), Whitespace(" "), Normal(""), Variable("FOO")]
```
It doesn't seem to affect program behavior normally, but I'd rather try to avoid it.

**Comment by aeosynth** [comment]
This issue has returned, same as the OP.
