### ISSUE TITLE
no completion after special chars

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#347]
```
touch 'f(x)'
rm f\(<Tab> # no completion
```

**Comment by huntergoldstein** [comment]
Strange: [this works for me on current `master`](https://asciinema.org/a/nPcW6SWZvb3mAWMUBVn8Cf7J8). Perhaps updating `liner` had something to do with it @MovingtoMars @mmstick ?

**Comment by aeosynth** [comment]
same issue on 6e53a36602374a701503cecb66c00bf6398f899e. i filed the issue before the liner update commit.

**Comment by huntergoldstein** [comment]
See #354; that commit has a small bug which should be fixed now (which is my fault for rushing through #353).

I meant to say that updating liner resolved the issue, hence why `master` before [`6e53a36`](https://github.com/redox-os/ion/commit/6e53a36602374a701503cecb66c00bf6398f899e) did not have that problem.

**Comment by MovingtoMars** [comment]
I can reproduce on my machine. Will look into it soon.

**Comment by huntergoldstein** [comment]
@MovingtoMars: #354 should resolve the latest issue.

**Comment by aeosynth** [comment]
this issue is fixed, thanks @huntergoldstein
