### ISSUE TITLE
Inform the user if a script is incomplete

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#356]
# Problem
The following, if placed in a script, will run without any output and setting the status to `0`:
```
for i in 0..10
```
If this were run as part of an interactive session Ion would prompt the user for more input.

# Solution
Have `Shell` somehow check the current flow control after executing a script. If the flow control indicates a partial command in memory, indicate the command and exit with a non-zero status.

**Comment by mmstick** [comment]
Should we even execute a script that's incomplete? Perhaps we should verify that scripts are complete before execution.

**Comment by huntergoldstein** [comment]
We could make two runs through the script if we wanted, but I think at least printing out some sort of warning for exiting a script with a non-empty flow control is needed.
