### ISSUE TITLE
Is Ion expected to build with the current stable Rust/Cargo versions?

### ISSUE THREAD

**Issue by jwbowen** [redox-os/ion#359]
I'm getting build failures related to `break`ing with a value (Rust RFC 1624, GitHub issue  [#37339](https://github.com/rust-lang/rust/issues/37339)).

I can post the verbose output of the failed build if so.

**Comment by mmstick** [comment]
You must have a very old version of Rust. The build error should be telling you that you need at least Rust 1.18 to compile Ion.

**Comment by jwbowen** [comment]
I'm using Rust 1.18.0.

date:
Sat Jul  1 11:11:57 CDT 2017

uname -a:
Linux bender 4.12.0-rc7+ #1 SMP Mon Jun 26 08:46:11 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release:
NAME=Fedora
VERSION="25 (Workstation Edition)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation

rustc --version: rustc 1.18.0
cargo --version: cargo 0.19.0

cat .git/refs/heads/master:
578e04e09884575dbe3ba251418be99b80b692ea
-------------------------------------------------------------------------------
Now building ion with `cargo install --force --verbose`
  Installing ion-shell v1.0.3 (file:///home/jbowen/bld/ion)
   Compiling bitflags v0.7.0
   Compiling slab v0.3.0
   Compiling scoped-tls v0.1.0
   Compiling cfg-if v0.1.1
     Running `rustc --crate-name bitflags /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.7.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=50648a2c9f75de56 -C extra-filename=-50648a2c9f75de56 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
     Running `rustc --crate-name slab /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.3.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=1d39eb2650889945 -C extra-filename=-1d39eb2650889945 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
     Running `rustc --crate-name scoped_tls /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=c4803bb19056b839 -C extra-filename=-c4803bb19056b839 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
     Running `rustc --crate-name cfg_if /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=d5011616501a0c3e -C extra-filename=-d5011616501a0c3e --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling permutate v0.3.2
     Running `rustc --crate-name permutate /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/permutate-0.3.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=ce5a8e3ef93fd6df -C extra-filename=-ce5a8e3ef93fd6df --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling smallvec v0.4.1
     Running `rustc --crate-name smallvec /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.4.1/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=d18b01fb8f72be32 -C extra-filename=-d18b01fb8f72be32 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling log v0.3.8
     Running `rustc --crate-name log /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.3.8/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=afb927e2848cffe5 -C extra-filename=-afb927e2848cffe5 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling version_check v0.1.2
     Running `rustc --crate-name version_check /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=77ff85ef68de3231 -C extra-filename=-77ff85ef68de3231 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling futures v0.1.14
     Running `rustc --crate-name futures /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.14/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="with-deprecated"' --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=7bb57da4eebc8dbe -C extra-filename=-7bb57da4eebc8dbe --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling libc v0.2.24
     Running `rustc --crate-name libc /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.24/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=bac9883df7bea2d8 -C extra-filename=-bac9883df7bea2d8 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling lazycell v0.4.0
     Running `rustc --crate-name lazycell /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/lazycell-0.4.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=63c04d4976d78cbc -C extra-filename=-63c04d4976d78cbc --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling fnv v1.0.5
     Running `rustc --crate-name fnv /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/fnv-1.0.5/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=5d595168641010fe -C extra-filename=-5d595168641010fe --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling byteorder v1.0.0
     Running `rustc --crate-name byteorder /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=3e6d4ae3e36234b8 -C extra-filename=-3e6d4ae3e36234b8 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling net2 v0.2.29
     Running `rustc --crate-name net2 /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.29/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="duration"' --cfg 'feature="default"' -C metadata=c101ea78292eca37 -C extra-filename=-c101ea78292eca37 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern cfg_if=/home/jbowen/bld/ion/target/release/deps/libcfg_if-d5011616501a0c3e.rlib --cap-lints allow`
   Compiling termion v1.4.0
     Running `rustc --crate-name termion /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.4.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=8c208c241d3b8b8b -C extra-filename=-8c208c241d3b8b8b --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --cap-lints allow`
   Compiling users v0.5.2
     Running `rustc --crate-name users /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/users-0.5.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=a0c245b023c5b9f0 -C extra-filename=-a0c245b023c5b9f0 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --cap-lints allow`
   Compiling iovec v0.1.0
     Running `rustc --crate-name iovec /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/iovec-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=e4149bb8d07c53bf -C extra-filename=-e4149bb8d07c53bf --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --cap-lints allow`
   Compiling mio v0.6.9
     Running `rustc --crate-name mio /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.9/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="with-deprecated"' -C metadata=579d9ac1066e036b -C extra-filename=-579d9ac1066e036b --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern slab=/home/jbowen/bld/ion/target/release/deps/libslab-1d39eb2650889945.rlib --extern net2=/home/jbowen/bld/ion/target/release/deps/libnet2-c101ea78292eca37.rlib --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern log=/home/jbowen/bld/ion/target/release/deps/liblog-afb927e2848cffe5.rlib --extern lazycell=/home/jbowen/bld/ion/target/release/deps/liblazycell-63c04d4976d78cbc.rlib --extern iovec=/home/jbowen/bld/ion/target/release/deps/libiovec-e4149bb8d07c53bf.rlib --cap-lints allow`
   Compiling void v1.0.2
     Running `rustc --crate-name void /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=336ac62ddf5bdb9f -C extra-filename=-336ac62ddf5bdb9f --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling unicode-width v0.1.4
     Running `rustc --crate-name unicode_width /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.4/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' -C metadata=81fae7784b7a2165 -C extra-filename=-81fae7784b7a2165 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling bytes v0.4.4
     Running `rustc --crate-name bytes /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.4/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=dd2cc4b8f5b0d9f7 -C extra-filename=-dd2cc4b8f5b0d9f7 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern byteorder=/home/jbowen/bld/ion/target/release/deps/libbyteorder-3e6d4ae3e36234b8.rlib --extern iovec=/home/jbowen/bld/ion/target/release/deps/libiovec-e4149bb8d07c53bf.rlib --cap-lints allow`
   Compiling liner v0.3.1
     Running `rustc --crate-name liner /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/liner-0.3.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=c26ab2657b07b57d -C extra-filename=-c26ab2657b07b57d --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern unicode_width=/home/jbowen/bld/ion/target/release/deps/libunicode_width-81fae7784b7a2165.rlib --extern termion=/home/jbowen/bld/ion/target/release/deps/libtermion-8c208c241d3b8b8b.rlib --cap-lints allow`
   Compiling nix v0.8.1
     Running `rustc --crate-name nix /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.8.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=9beb641f3c2299f3 -C extra-filename=-9beb641f3c2299f3 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern void=/home/jbowen/bld/ion/target/release/deps/libvoid-336ac62ddf5bdb9f.rlib --extern cfg_if=/home/jbowen/bld/ion/target/release/deps/libcfg_if-d5011616501a0c3e.rlib --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern bitflags=/home/jbowen/bld/ion/target/release/deps/libbitflags-50648a2c9f75de56.rlib --cap-lints allow`
   Compiling tokio-io v0.1.2
     Running `rustc --crate-name tokio_io /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=331858456c48be2f -C extra-filename=-331858456c48be2f --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern log=/home/jbowen/bld/ion/target/release/deps/liblog-afb927e2848cffe5.rlib --extern bytes=/home/jbowen/bld/ion/target/release/deps/libbytes-dd2cc4b8f5b0d9f7.rlib --extern futures=/home/jbowen/bld/ion/target/release/deps/libfutures-7bb57da4eebc8dbe.rlib --cap-lints allow`
   Compiling unicode-segmentation v1.2.0
     Running `rustc --crate-name unicode_segmentation /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-segmentation-1.2.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=749fcc60dea47ee3 -C extra-filename=-749fcc60dea47ee3 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling ansi_term v0.9.0
     Running `rustc --crate-name ansi_term /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.9.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=0a395e1076764f4f -C extra-filename=-0a395e1076764f4f --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling tokio-core v0.1.8
     Running `rustc --crate-name tokio_core /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=0c46b17a8aa2fad5 -C extra-filename=-0c46b17a8aa2fad5 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern bytes=/home/jbowen/bld/ion/target/release/deps/libbytes-dd2cc4b8f5b0d9f7.rlib --extern log=/home/jbowen/bld/ion/target/release/deps/liblog-afb927e2848cffe5.rlib --extern tokio_io=/home/jbowen/bld/ion/target/release/deps/libtokio_io-331858456c48be2f.rlib --extern scoped_tls=/home/jbowen/bld/ion/target/release/deps/libscoped_tls-c4803bb19056b839.rlib --extern slab=/home/jbowen/bld/ion/target/release/deps/libslab-1d39eb2650889945.rlib --extern mio=/home/jbowen/bld/ion/target/release/deps/libmio-579d9ac1066e036b.rlib --extern iovec=/home/jbowen/bld/ion/target/release/deps/libiovec-e4149bb8d07c53bf.rlib --extern futures=/home/jbowen/bld/ion/target/release/deps/libfutures-7bb57da4eebc8dbe.rlib --cap-lints allow`
   Compiling glob v0.2.11
     Running `rustc --crate-name glob /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/glob-0.2.11/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=d84927ef23f68535 -C extra-filename=-d84927ef23f68535 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling smallvec v0.3.3
     Running `rustc --crate-name smallvec /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.3.3/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=0d5c62c1f9ad2256 -C extra-filename=-0d5c62c1f9ad2256 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling smallstring v0.1.2
     Running `rustc --crate-name smallstring /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/smallstring-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="default"' -C metadata=d57c91c6f121101c -C extra-filename=-d57c91c6f121101c --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern smallvec=/home/jbowen/bld/ion/target/release/deps/libsmallvec-0d5c62c1f9ad2256.rlib --cap-lints allow`
   Compiling quote v0.3.15
     Running `rustc --crate-name quote /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-0.3.15/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=ad5221ea26e62a8e -C extra-filename=-ad5221ea26e62a8e --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling bitflags v0.9.1
     Running `rustc --crate-name bitflags /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.9.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 --cfg 'feature="example_generated"' --cfg 'feature="default"' -C metadata=6c33870564902cd0 -C extra-filename=-6c33870564902cd0 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --cap-lints allow`
   Compiling mio-uds v0.6.4
     Running `rustc --crate-name mio_uds /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-uds-0.6.4/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=3e1f76e4b29e304c -C extra-filename=-3e1f76e4b29e304c --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern mio=/home/jbowen/bld/ion/target/release/deps/libmio-579d9ac1066e036b.rlib --cap-lints allow`
   Compiling peg v0.5.4
     Running `rustc --crate-name peg /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/peg-0.5.4/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=89c8ae2d3019f373 -C extra-filename=-89c8ae2d3019f373 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern quote=/home/jbowen/bld/ion/target/release/deps/libquote-ad5221ea26e62a8e.rlib --cap-lints allow`
   Compiling tokio-signal v0.1.2
     Running `rustc --crate-name tokio_signal /home/jbowen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-signal-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=5c6672d974ee2573 -C extra-filename=-5c6672d974ee2573 --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern mio_uds=/home/jbowen/bld/ion/target/release/deps/libmio_uds-3e1f76e4b29e304c.rlib --extern tokio_core=/home/jbowen/bld/ion/target/release/deps/libtokio_core-0c46b17a8aa2fad5.rlib --extern futures=/home/jbowen/bld/ion/target/release/deps/libfutures-7bb57da4eebc8dbe.rlib --extern mio=/home/jbowen/bld/ion/target/release/deps/libmio-579d9ac1066e036b.rlib --cap-lints allow`
   Compiling ion-shell v1.0.3 (file:///home/jbowen/bld/ion)
     Running `rustc --crate-name build_script_build build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C debuginfo=2 -C metadata=cddf7969936a7e94 -C extra-filename=-cddf7969936a7e94 --out-dir /home/jbowen/bld/ion/target/release/build/ion-shell-cddf7969936a7e94 -L dependency=/home/jbowen/bld/ion/target/release/deps --extern version_check=/home/jbowen/bld/ion/target/release/deps/libversion_check-77ff85ef68de3231.rlib --extern ansi_term=/home/jbowen/bld/ion/target/release/deps/libansi_term-0a395e1076764f4f.rlib --extern peg=/home/jbowen/bld/ion/target/release/deps/libpeg-89c8ae2d3019f373.rlib`
     Running `/home/jbowen/bld/ion/target/release/build/ion-shell-cddf7969936a7e94/build-script-build`
warning: Ion was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.
     Running `rustc --crate-name ion src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C debuginfo=2 -C metadata=a4bf6c04f9116d8a -C extra-filename=-a4bf6c04f9116d8a --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern fnv=/home/jbowen/bld/ion/target/release/deps/libfnv-5d595168641010fe.rlib --extern permutate=/home/jbowen/bld/ion/target/release/deps/libpermutate-ce5a8e3ef93fd6df.rlib --extern liner=/home/jbowen/bld/ion/target/release/deps/libliner-c26ab2657b07b57d.rlib --extern tokio_signal=/home/jbowen/bld/ion/target/release/deps/libtokio_signal-5c6672d974ee2573.rlib --extern smallstring=/home/jbowen/bld/ion/target/release/deps/libsmallstring-d57c91c6f121101c.rlib --extern users=/home/jbowen/bld/ion/target/release/deps/libusers-a0c245b023c5b9f0.rlib --extern nix=/home/jbowen/bld/ion/target/release/deps/libnix-9beb641f3c2299f3.rlib --extern bitflags=/home/jbowen/bld/ion/target/release/deps/libbitflags-6c33870564902cd0.rlib --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern unicode_segmentation=/home/jbowen/bld/ion/target/release/deps/libunicode_segmentation-749fcc60dea47ee3.rlib --extern glob=/home/jbowen/bld/ion/target/release/deps/libglob-d84927ef23f68535.rlib --extern futures=/home/jbowen/bld/ion/target/release/deps/libfutures-7bb57da4eebc8dbe.rlib --extern tokio_core=/home/jbowen/bld/ion/target/release/deps/libtokio_core-0c46b17a8aa2fad5.rlib --extern smallvec=/home/jbowen/bld/ion/target/release/deps/libsmallvec-d18b01fb8f72be32.rlib`
error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:239:21
    |
239 |                     break code
    |                     ^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:244:21
    |
244 |                     break TERMINATED
    |                     ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:255:21
    |
255 |                     break TERMINATED
    |                     ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:263:17
    |
263 |                 break 100 // TODO what should we return here?
    |                 ^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:278:29
    |
278 |                             break code
    |                             ^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:283:29
    |
283 |                             break TERMINATED
    |                             ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:290:29
    |
290 |                             break TERMINATED
    |                             ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:298:25
    |
298 |                         break 100 // TODO what should we return here?
    |                         ^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:313:25
    |
313 |                         break code
    |                         ^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:318:25
    |
318 |                         break TERMINATED
    |                         ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:325:25
    |
325 |                         break TERMINATED
    |                         ^^^^^^^^^^^^^^^^

error: `break` with a value is experimental (see issue #37339)
   --> src/shell/pipe.rs:333:21
    |
333 |                     break 100 // TODO what should we return here?
    |                     ^^^^^^^^^

error: aborting due to 12 previous errors

The following warnings were emitted during compilation:

warning: Ion was unable to check rustc compatibility.
warning: Build may fail due to incompatible rustc version.

error: failed to compile `ion-shell v1.0.3 (file:///home/jbowen/bld/ion)`, intermediate artifacts can be found at `/home/jbowen/bld/ion/target`

Caused by:
  Could not compile `ion-shell`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ion src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C debuginfo=2 -C metadata=a4bf6c04f9116d8a -C extra-filename=-a4bf6c04f9116d8a --out-dir /home/jbowen/bld/ion/target/release/deps -L dependency=/home/jbowen/bld/ion/target/release/deps --extern fnv=/home/jbowen/bld/ion/target/release/deps/libfnv-5d595168641010fe.rlib --extern permutate=/home/jbowen/bld/ion/target/release/deps/libpermutate-ce5a8e3ef93fd6df.rlib --extern liner=/home/jbowen/bld/ion/target/release/deps/libliner-c26ab2657b07b57d.rlib --extern tokio_signal=/home/jbowen/bld/ion/target/release/deps/libtokio_signal-5c6672d974ee2573.rlib --extern smallstring=/home/jbowen/bld/ion/target/release/deps/libsmallstring-d57c91c6f121101c.rlib --extern users=/home/jbowen/bld/ion/target/release/deps/libusers-a0c245b023c5b9f0.rlib --extern nix=/home/jbowen/bld/ion/target/release/deps/libnix-9beb641f3c2299f3.rlib --extern bitflags=/home/jbowen/bld/ion/target/release/deps/libbitflags-6c33870564902cd0.rlib --extern libc=/home/jbowen/bld/ion/target/release/deps/liblibc-bac9883df7bea2d8.rlib --extern unicode_segmentation=/home/jbowen/bld/ion/target/release/deps/libunicode_segmentation-749fcc60dea47ee3.rlib --extern glob=/home/jbowen/bld/ion/target/release/deps/libglob-d84927ef23f68535.rlib --extern futures=/home/jbowen/bld/ion/target/release/deps/libfutures-7bb57da4eebc8dbe.rlib --extern tokio_core=/home/jbowen/bld/ion/target/release/deps/libtokio_core-0c46b17a8aa2fad5.rlib --extern smallvec=/home/jbowen/bld/ion/target/release/deps/libsmallvec-d18b01fb8f72be32.rlib` (exit code: 101)

**Comment by mmstick** [comment]
I see that the feature was stabilized in the Rust specs a while back, but it will only be enabled starting with Rust 1.19, so you'll need to use either Beta or Nightly for now.

**Comment by huntergoldstein** [comment]
Could we add a `rust-toolchain` or whatever magic file is used by `rustup`? That way we can commit what version `ion` should be compiled with.

**Comment by jwbowen** [comment]
I was just going to suggest adding a line at the top of the README.md to say something to the effect that Ion may use bleeding-edge features of Rust and thus may require the beta or nightly build of `rustc` to compile.

**Comment by mmstick** [comment]
That's the purpose of our build.rs code. It's supposed to generate a compiler error when the minimum Rust version is not met. It's currently passing because you have 1.18 and the minimum version is specified as 1.18.

**Comment by jwbowen** [comment]
Mind if I update the build.rs to specify 1.19.0 as the minimum version due to the RFC for `break`ing with a value?

**Comment by mmstick** [comment]
You may do so, as that's what is needed to be done. May also want to update the error message too.

**Comment by jwbowen** [comment]
PR #360 addressed this issue.

Closing.
