### ISSUE TITLE
Dead Code

### ISSUE THREAD

**Issue by soniceroy** [redox-os/ion#371]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Build with #[warn(deadcode)] on.
**Expected behavior**: [describe the behavior you would expect the repro to yield.]
No warnings or errors
**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
When I built ion, the following warning was displayed:

`warning: function is never used: `suspend`
  --> src/builtins/job_control.rs:24:1
   |
24 | / fn suspend(pid: u32) {
25 | |     let _ = signal::kill(-(pid as pid_t), Some(Signal::SIGTSTP));
26 | | }
   | |_^
   |
   = note: #[warn(dead_code)] on by default
`

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
May not really be an error, but figure I'd let you guys know.
Also one extra thing is that install instructions are not in the README. Wasn't a big deal for me, because I knew a bit about Rust, but someone new to all of this who just wanted to try out a fast shell, wouldn't know what to do.
------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by mmstick** [comment]
The master branch is under constant flux, especially at the moment where job control is being worked on, so there's bound to be some warnings between commits.

**Comment by soniceroy** [comment]
@mmstick thanks. I'm still learning git. I'm guessing i should have pulled from a different branch?

**Comment by mmstick** [comment]
We only have one branch, so it won't matter where you pull from. The warnings have no effect of the produced binary.

**Comment by soniceroy** [comment]
@mmstick got it, thanks!
