### ISSUE TITLE
export path doesn't work with tilde

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#375]
```
james:/home/james# export PATH = "~/.cargo/bin:/bin"; cargo
ion: command not found: cargo
james:/home/james# export PATH = "/home/james/.cargo/bin:/bin"; cargo
Rust's package manager
```

**Comment by huntergoldstein** [comment]
I'll note that POSIX-compliant shells do not expand tildes inside double quotes, but we do not have to be POSIX so this could be added.

**Comment by aeosynth** [comment]
i'm only using double quotes because the example does: https://github.com/redox-os/ion#export

**Comment by huntergoldstein** [comment]
Well that's silly; thank you for pointing that out

**Comment by mmstick** [comment]
Do we want to support this? I'm not sure if there's a good reason to not do what POSIX does in this particular area, as there must have been a reason for that decision.

**Comment by aeosynth** [comment]
my original issue doesn't bother me now that the readme was updated, but i found another issue with tilde: it only works in the first position:

```
james:/home/james# export PATH = ~/go/bin:~/.cargo/bin:/bin; cargo
ion: command not found: cargo
james:/home/james# export PATH = ~/.cargo/bin:~/go/bin:/bin; cargo
Rust's package manager
```
