### ISSUE TITLE
Enable Piping Functions & Background Execution

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#380]
Much like builtins, functions should also be able to be piped, and if the function is specified to run in the background, it should be forked.

**Comment by huntergoldstein** [comment]
How will we handle functions receiving a stream of data? e.g. can I specify if I want my function to receive data line by line, character by character? My immediate thought is we can do something like:
```
cat some_file.txt | $by_lines(function, ...)
```
where `$by_lines` takes in a function and perhaps allows partial application. So if you have a function:
```
fn nth line index
  echo @split(line)[index]
end
```
you can have:
```
cat some_file.txt | $by_lines(nth, _, 0)
```
where the underscore represents the input from the pipe.

**Comment by mmstick** [comment]
I'm not sure if we will implement piping to/from methods, but if we did, we would want to have a special string variable that's actually a front to the file descriptor of that fork's standard input. For functions specifically, they should be able to take advantage of the `read` builtin for reading input. We would just need to ensure that the stdin/stdout of the fork where our function is executing is properly mapped.

**Comment by mmstick** [comment]
Seems I forgot to close this.
