### ISSUE TITLE
Not providing an output for a pipe causes a panic 

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#381]
**Expected Behavior**:
```
$ cat build.rs |
<A sensible error message>
```

**Actual behavior**: 
```
$ cat build.rs |
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/shell/pipe.rs:337:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Build information**:
- `git rev-parse HEAD`: `a26cb67beb7e29afd6d7c3952afc526832c524af`

**Misc**: This occurs at a function which says `This function will panic if an argument is the empty vector`.

**Comment by mmstick** [comment]
Solution is to add more checks to the `QuoteTerminator` to also ensure that pipes/jobs are also terminated.

**Comment by mmstick** [comment]
Resolved
