### ISSUE TITLE
Fails to install on MacOS

### ISSUE THREAD

**Issue by Thomasdezeeuw** [redox-os/ion#386]
**Reproduction**: Tried to install ion on MacOS.

**Expected behavior**: Sucessfull install.

**Actual behavior**: Got a compiler error:

```bash
error[E0425]: cannot find value `WCONTINUED` in this scope
  --> /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/ion-shell-1.0.4/src/shell/job_control.rs:83:57
   |
83 |         match waitpid(-(pid as pid_t), Some(WUNTRACED | WCONTINUED | WNOHANG)) {
   |                                                         ^^^^^^^^^^ not found in this scope
   |
help: possible candidates are found in other modules, you can import them into scope
   |
76 | ) use libc::WCONTINUED;
   |
76 | ) use nix::libc::WCONTINUED;
   |

error: aborting due to previous error

error: failed to compile `ion-shell v1.0.4`, intermediate artifacts can be found at `/var/folders/lq/rzq0zxld0bb5mcy4jl1txrf00000gn/T/cargo-install.vz3Fh93nBvAP`

Caused by:
  Could not compile `ion-shell`.

To learn more, run the command again with --verbose.
```

**Comment by mmstick** [comment]
Think you could add `use nix::libc::WCONTINUED` in that function to see if that fixes it? I don't own any Apple hardware so I can't test for that platform.

**Comment by huntergoldstein** [comment]
I commandeered a Mac for a moment; adding `use nix::libc::WCONTINUED` doesn't quite work as `nix::sys::wait::WCONTINUED` is a strongly typed bitflag whereas `{nix::,}libc::WCONTINUED` is just an integer constant. [`WCONTINUED` does not appear to be a bitflag on non-Linux systems](https://docs.rs/nix/0.8.1/src/nix/sys/wait.rs.html#16). I can't find any evidence of it [in the man page for `waitpid` on macOS](http://www.manpages.info/macosx/waitpid.2.html) but I'm not sure if that man page is up to date.

**Comment by mmstick** [comment]
I wonder, then, if Mac OS has the `WCONTINUED` behavior enabled by default? Easily tested by doing a quick `if cfg(target_os = "linux") { linux-specific-flags } else { everyone else }` to enable `WCONTINUED` for Linux, and using all but that flag for everyone else, then running Ion, create a stopped background job, and resume that job. It should say `Running` when executing `jobs` if it's working.

**Comment by Thomasdezeeuw** [comment]
I have applied to following path, and it seems to work. But I have only run the tests on MacOS.

```diff
--- a/src/shell/job_control.rs
+++ b/src/shell/job_control.rs
@@ -80,7 +80,11 @@ pub fn watch_background (
         if !fg_was_grabbed {
             if fg.was_grabbed(pid) { fg_was_grabbed = true; }
         }
-        match waitpid(-(pid as pid_t), Some(WUNTRACED | WCONTINUED | WNOHANG)) {
+        #[cfg(target_os = "linux")]
+        let flags = Some(WUNTRACED | WCONTINUED | WNOHANG);
+        #[cfg(not(target_os = "linux"))]
+        let flags = Some(WUNTRACED | WNOHANG);
+        match waitpid(-(pid as pid_t), flags) {
             Ok(WaitStatus::Exited(_, status)) => {
                 if !fg_was_grabbed {
                     eprintln!("ion: ([{}] {}) exited with {}", njob, pid, status);
```

**Comment by huntergoldstein** [comment]
- We should be able to set up a situation to exactly test your hypothesis @mmstick 
- My only concern is that any non-Linux *nix needs to behave in this same way (`WCONTINUED` by default). For example, `WCONTINUED` _is_ a flag for OpenBSD but it is not exposed by `nix`

**Comment by mmstick** [comment]
Seems to just be a gap in the `nix` crate's implementation, that I will have fixed soon.

**Comment by Thomasdezeeuw** [comment]
Anything I can do to test? Like I said all the tests pass, however I don't haven't use job control in the shell it itself really.

**Comment by mmstick** [comment]
@Thomasdezeeuw  Just run

```ion
sleep 100 (then press Ctrl + Z)
jobs
bg 0
jobs
```

If the first `jobs` prints Stopped, and the second `jobs` prints `Running`, then it works.

**Comment by Thomasdezeeuw** [comment]
Afraid it doesn't work then, I got this:

```shell
thomas:/Users/thomas# sleep 100
^Zion: bg [0] 93702
thomas:/Users/thomas# jobs
[0] 93702 Stopped	sleep 100
thomas:/Users/thomas# bg 0
thomas:/Users/thomas# jobs
[0] 93702 Stopped	sleep 100
thomas:/Users/thomas#
```

**Comment by mmstick** [comment]
The fix for this will be included in a future release of the `nix` crate. I have this open PR: https://github.com/nix-rust/nix/pull/651

**Comment by mmstick** [comment]
May just be a good idea to ditch `nix` and use `libc` for the `waitpid` function.

**Comment by jwarner112** [comment]
I'm encountering this problem myself now. It looks like [nix-rust/nix#651](https://github.com/nix-rust/nix/pull/651) is on the verge of being merged; looking forward to it, thanks @mmstick!

**Comment by jackpot51** [comment]
@mmstick that would also make it easier to port background functions to Redox

**Comment by bb010g** [comment]
Looks like that PR's just needing a rebase to be ready.

**Comment by Thomasdezeeuw** [comment]
I've tried ion again and it compiled! I'm not sure what actually fixed it though. I also ran all tests and they passed, so I think this can be closed.
