### ISSUE TITLE
Path String Methods

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#390]
Pathname handling is a common activity in shell code, so we should promote them as first class methods. Rust will make this very easy to implement.

- $extension(filepath)
- $basename(filepath)
- $parent(filepath)
- $filename(filepath)

**Comment by pithonsmear** [comment]
Should these be methods that only take a filepath, or small applets like basename in Linux, where you can also add flags, like e.g. "basename -a src/main.rs src/lib.rs"?

**Comment by mmstick** [comment]
Combining this with #441
