### ISSUE TITLE
Unwrap Or Methods

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#391]
This is another set of methods that are trivial to implement. If the given variable does not exist, then use the specified default value. Only question is, should we also consider empty variables as not existing?

- $unwrap_or(string, "default value")
- @unwrap_or(array, [default, array])

**Comment by huntergoldstein** [comment]
- It looks like most other shells use parameter expansion to handle this, for reference
  - [parameter expansion in `bash`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02)
  - [parameter expansion in `zsh](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion)
  - `fish` [seems to rely on brace expansion]( to implicitly cover this behavior)
  - [I think `oil` is similar, but I can't quite tell](http://www.oilshell.org/blog/2016/10/26.html)
- I think given the name of the function it makes sense to consider empty vars as existing though I'd just call it `or` for short.
- Could we make it variadic? i.e. the user can supply some number of variables / expressions and the first one that exists is returned.

**Comment by bb010g** [comment]
I would leave emptiness to #392. +1 for a shorter name. `oil` seems to only allow literals for the default after `:-`.

**Comment by mmstick** [comment]
@huntergoldstein It can be variadic.
