### ISSUE TITLE
Escaping characters

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#4]
Like other shells we will need to allow the user to escape characters and strings. I would like to discuss the details here. Escaping is surprisingly involved in posix shells with four escaping mechanisms:
- Backslash: Escape the following character.
- Single quotes: Preserve literal value of all strings between quotes.
- Double quotes: Escape most characters between quotes with several exceptions
  - Dollar sign retains meaning.
  - Backtick retains meaning.
  - Backslash retains its meaning only when followed by a backtick, dollar sign, backslash, or newline. Otherwise it is preserved.
- Heredoc: Redirect standard input to read a multiline string provided at the command line. This string is escaped similar to double quotes. E.g., `<<EOF`. Zsh and bash actually implement escaping within heredocs in an incompatible way.
- Herestring: Not part of posix, but provided by Bash and other shells. It is like a one line heredoc, but at least in bash it provides no escaping. E.g., `<<<some string`.

The point of all this is to say that escaping is more complicated than meets the eye and I would like to discuss our approach to it here.

**Comment by Ticki** [comment]
Currently the parser is just a lot of hacks stiched together. We should create a correct LL(k) parser.

**Comment by Ticki** [comment]
I'll work on it when I'm done debugging the new buffer data structure for Sodium.

**Comment by skylerberg** [comment]
I am working on a tokenizer right now. I am handling quoting in the tokenizer. An LL(k) parser would be great, but I think we should handle escaping at the tokenization phase for now.

**Comment by skylerberg** [comment]
To start with I have just made double quotes and single quotes do the same thing and they both act like bash single quotes: https://github.com/redox-os/ion/pull/5.

**Comment by skylerberg** [comment]
I have started on a parser and it is on master in my fork right now. I will make a pull request tomorrow after rebasing once my current pull request has gone through.

**Comment by Ticki** [comment]
@skylerberg Which method do you use to parse?

**Comment by skylerberg** [comment]
Right now it is just a for loop over the tokens.

**Comment by skylerberg** [comment]
In case any stumbles upon this, we are now using rust-peg.

**Comment by mmstick** [comment]
Today, everything here has been implemented except for heredocs and herestrings.
