### ISSUE TITLE
run command when changing directories

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#400]
fish functions can trigger when variables (eg `PWD`) are changed; i use this to track my most used directories. shadowing `cd` isn't enough, as that wouldn't trigger on implicit directory changing.

https://fishshell.com/docs/current/commands.html#function

> -v or --on-variable VARIABLE_NAME tells fish to run this function when the variable VARIABLE_NAME changes value.

**Comment by mmstick** [comment]
@huntergoldstein What do you think of this? Assigning optional callbacks on variables that trigger when updated.

**Comment by mmstick** [comment]
If we do this, I'd also like to make it possible to assign a library in a plugin as a callback too.

**Comment by huntergoldstein** [comment]
This seems like it would be fairly useful, though I'll admit I can only think of good uses for updates of `PWD`.

**Comment by aeosynth** [comment]
Can I ask why this was closed?

**Comment by mmstick** [comment]
Not sure

**Comment by aeosynth** [comment]
@jD91mZM2 do you know which CDs won't be intercepted?

**Comment by jD91mZM2** [comment]
None that I know of. I just know that it's bound to happen some day or another.
