### ISSUE TITLE
[DANGER] Tidle is expanded into separate word when used with globbing

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#406]
**Reproduction**: Attempt to run a command that includes both globing and a tilde.

**Expected behavior**:
```
$ ls ~/Downloads/
cd61.iso
some.program.tar.gz
$ rm ~/Downloads/*
$ ls ~/Downloads
< nothing >
$
```

**Actual behavior**:
```
$ ls ~/Downloads/
cd61.iso
some.program.tar.gz
$ rm ~/Downloads/*
rm: cannot remove '/home/hunter': Is a directory
```

**Build information**: 
- `git rev-parse HEAD`: 244811eb8d58c07dd546cadc5abd0cc506f6e6bc

**Misc**: This is concerning and I don't think the fix is trivial. I'm going to try and get this done right now but I'm gone for the next few days and this seems urgent.

**Comment by jackpot51** [comment]
Shit :(
