### ISSUE TITLE
Globbing Issue w/ ? in URLs

### ISSUE THREAD

**Issue by nivkner** [redox-os/ion#408]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
use curl on a youtube URL leading to a video (any video seems to have this effect)

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
with verbose output: 
```
* Trying 216.58.208.46...
* TCP_NODELAY set
* Connected to youtube.com (216.58.208.46) port 443 (#0)
* ...
```
otherwise nothing.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
with verbose output:
```
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
otherwise just the second line.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
Ion version 1.0.4 Alpha, linux kernel 4.11.9-1 on antergos, gnome 3.24.2

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
when trying to reduce the number of elements in the url, it is recognized up-to the use of `?`.
same happens with /playlist.
also happens with youtube-dl, though the cause might be the same.

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by nivkner** [comment]
sorry, wrong bottom, will fill details

**Comment by mmstick** [comment]
Seems to be a globbing issue. The `?` in the URL causes the URL to become nothing.

**Comment by huntergoldstein** [comment]
I wonder if there's a sensible way to print a warning for glob failures (thinking of #406).

**Comment by nivkner** [comment]
the problem seems to be more then just `?`.
the following command produces just `hello`:
```
echo hello@world
```

also, when attempting to connect to a device through ssh using `ssh user@hostname` I got instead:
```
ssh: Could not resolve hostname user.hostname: Name or service not known
```
(with different names obviously, the point is `@` was replaced with `.`)

tested against the newly released ion 1.0.5 alpha, otherwise the build is the same

**Comment by mmstick** [comment]
@nivkner That's expected, actually, because @ is the array sigil. You need to escape the @.

**Comment by mmstick** [comment]
@huntergoldstein I believe the solution here will be the same as other shells do it. If there's a glob failure, just use the original string, rather than wiping it out and giving an empty string.

**Comment by mmstick** [comment]
Issue resolved via latest commit mentioned above.

**Comment by mmstick** [comment]
You may want to verify that you built Ion from that commit. The tests include that exact command and are passing with the correct output.
