### ISSUE TITLE
Stripping newlines from subshell expansion

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#410]
# Current Behavior
Grabbing the output of a command from an unquoted subshell expansion will strip the newlines from the output. For example:
```
$ ls -l
total 0
-rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 bar
-rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 baz
-rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 foo
$ let var = $(ls -l)
$ let
...
var = total 0 -rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 bar -rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 baz -rw-r--r-- 1 hunter hunter 0 Jul 13 12:26 foo
...
```
# Proposal
I believe it is clearer if sub-shell expansion does not modify the output of the shell (some discussion in #405). Other thoughts?

**Comment by bb010g** [comment]
I'd be for leaving expansion as-is and not requiring defensive quoting. If someone wants to convert their newlines into spaces, I'd think the idiomatic way would be working with an array and then using `$join()`, allowing the use of their delimiter of choice. This would probably work well with some way to specify the grapheme/string to split by for array-based command substitution.
