### ISSUE TITLE
constant crash with large history

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#415]
**Reproduction**:

    for x in $(seq 2000); echo $x >> ~/.local/share/ion/history; end
    fatal runtime error: out of memory
    fish: “ion” terminated by signal SIGILL (Illegal instruction)

**Expected behavior**: having a large history does not crash the shell

**Actual behavior**: shell becomes unusable (constantly OOM)

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]

    rustc 1.19.0-beta.3 (4b6f4f353 2017-07-07)
    5b434727642243eb4d198acfff4be1e87b06e339
    Linux void 4.11.10_1 #1 SMP PREEMPT Wed Jul 12 17:24:18 UTC 2017 x86_64 GNU/Linux

**Misc**: edit: after using ion, the history file blows up to over 1 gig

**Comment by mmstick** [comment]
This is very strange. I'm not able to replicate the history file reaching 1G, but I am getting the out of memory error. I have no idea at this stage as to why that would happen though. Liner handles the history file, and I wrote the code in Liner that uses a 4K array buffer for reading the history file and appending new commands to it, so it shouldn't be running out of memory with a 4K buffer.

**Comment by mmstick** [comment]
I found the issue. I forgot a `break` in a loop.

**Comment by mmstick** [comment]
The fix has been merged, and Ion's `Cargo.toml` now points to the master branch of liner which has the fix.
