### ISSUE TITLE
Create Ion Wiki

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#421]
As Ion nears completion, we should create some extensive documentation to cover all of Ion's features, behaviors, and implementation details so that users interested in gaining mastery of Ion know where everything is and how it works. Should also be available alongside Ion for offline viewing.

**Comment by jhasse** [comment]
What do you think about using this GitHub project's Wiki for that? GitHub wikis are also accessible via Git (so offline viewing would be possible).

**Comment by mmstick** [comment]
@jhasse I was thinking of having a `book` directory with markdown files contained within that can be compiled into a book with [mdBook](https://github.com/azerupi/mdBook).

**Comment by mmstick** [comment]
i'm beginning work on this.

**Comment by mmstick** [comment]
We now have a mdBook, available in the **manual** directory. It's not complete, but I will have it completed soon (maybe a day or so). https://github.com/redox-os/ion/tree/master/manual
