### ISSUE TITLE
Prompt Configuration

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#423]
All that needs to be done at the moment is:

- Check if a function named `PROMPT` exists
- Execute that function and obtain it's output as the prompt
- Fall back to the `PROMPT` variable if an error occurs

**Comment by jhasse** [comment]
> Three things

Did you forget a bullet point?

> Some means of easily changing colors in the prompt

What about ANSI color escape codes?

**Comment by aeosynth** [comment]
> What about ANSI color escape codes?

i don't think that's easy for users to manually enter. fish has [set_color](https://fishshell.com/docs/current/commands.html#set_color):

```
set_color red; echo "Roses are red"
set_color blue; echo "Violets are blue"
set_color 62A; echo "Eggplants are dark purple"
set_color normal; echo "Normal is nice" ## Resets the background too
```

**Comment by mmstick** [comment]
@jhasse I'm reluctant to implement those because they're downright awful to read and write. Instead, I think we should come up with a much better syntax that's easier to read/write, and also allow what fish does.

**Comment by mmstick** [comment]
Maybe something like this?

```
echo \c{red:bold}Here's some red, bolded text.\c{reset} And now back to the default.
echo \c{09F}Hex is also supported.
```

**Comment by mmstick** [comment]
It would be nice if a terminal could have a means of signaling it's shell that the background is dark or light.

**Comment by huntergoldstein** [comment]
- To avoid the "am I going to be able to see this color" problem, I've thought the idea is that the user just specifies the general color and the terminal emulator / framebuffer worries about what each color means.
- Does redox have some version of [`tput`](http://man7.org/linux/man-pages/man1/tput.1.html)? `tput` just outputs the correct ANSI escape codes, see: http://linux.101hacks.com/ps1-examples/prompt-color-using-tput/

**Comment by msehnout** [comment]
It would be also nice to have few predefined prompts as fish does. e.g. in documentation or in sample configuration.

**Comment by msehnout** [comment]
Is there a way to capture output of the `PROMPT_FN` function? Because `liner` takes prompt as an argument thus we need to make a string from the function somehow. Or is there a way to evaluate `PROMPT` variable right before passing it to liner?

**Comment by mmstick** [comment]
[This](https://github.com/redox-os/ion/blob/master/src/shell/binary.rs#L42:L48) is where the string for the prompt is generated. Conditional logic can be added there to determine if the PROMPT_FN variable was set, and if so, executing that prompt's function.

It should be possible to temporarily change the file descriptor of the stdout of the shell when executing the function (and may want to change the function signature to &mut self), and then read that FD to get the output as a string, and then setting stdout back to it's original FD.

**Comment by mmstick** [comment]
You can use `sys::dup` to create a new FD, and `sys::dup2` to change an existing FD to a newly-created FD. Then use `sys::dup2` again to set the FD back when you're done.

**Comment by mmstick** [comment]
Just a heads up that I'll have color support implemented soon.

**Comment by msehnout** [comment]
I was thinking about this exact solutions, but it seems like a horrible hack to me.

**Comment by mmstick** [comment]
This is the cleanest way to go about it, actually. Other methods would be horrible hacks.

**Comment by mmstick** [comment]
We now have 256-bit color support, and the ability to set multiple colors. The default prompt can now be written like so:

```
echo "${color::55,bold}${USER}${color::default}:${color::4B}${PWD}${color::default}#"
```

**Comment by mmstick** [comment]
I've just done some further work on color support, and now there's support for both decimal and hexadecimal notations for setting a 256-bit color. Hexadecimal values will now require to be prefixed with '0x', whereas decimal values will not require any notation. Additionally, I've added a shorthand for `color`, so you can now access the `color` namespace via `c`.

The Ion prompt can now be written as:

```
echo "${c::0x55,bold}${USER}${c::default}:${c::0x4B}${PWD}${c::default}#"

```

**Comment by mmstick** [comment]
I think what we'll do here is check if the `PROMPT` function was set, and if it's set, use that as the prompt. Otherwise, fall back to the default text-based `PROMPT` variable.

**Comment by mmstick** [comment]
This is now complete. https://github.com/redox-os/ion/commit/cc5fba63c5ab4f422a54891d35890ee12d5e646c
