### ISSUE TITLE
wildcard expansion after escaping

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#437]
```
# touch 'f x' 'f y'
# rm f\ *
rm: cannot remove ' *': No such file or directory
rm: cannot remove 'f': No such file or directory
# rm f*
```

**Comment by huntergoldstein** [comment]
The problem here seems to be that `WordIterator` will always cut off a word when processing escaped characters. I think this necessitates post-processing of escaped characters (i.e. explicitly scanning through a string and mapping, for example, `\(` to `(`).

**Comment by tormeh** [comment]
After messing around with this for a while I'm unsure how to handle this. I have a suggestion, though: When calling `WordIterator::new(data,...)` we can scan through the string, removing all single backslashes while at the same time building a vector with the indices of the escaped characters. The escaped characters later get special treatment. This lets us return wordtokens with slices of the data. The alternative is (as far as I can tell) to, for each returned wordtoken, convert to vector and remove backslashes. That sounds less efficient to me. It also requires some ugly logic in the `next` function to keep track of whether the next character is escaped or not.

What do you think? I'm not very familiar with the spec of ion, so I might have misunderstood something.

**Comment by mmstick** [comment]
@tormeh That may be a means of achieving this, although it would be more ideal if we could do this without performing a heap allocation. Each heap allocation we perform in this area could potentially cause some exponential performance loss (if the heap allocation is more costly than time to compute without the temporary allocation). Unless we could have this heap-allocated vector globally initialized, so that the cost is only paid once at the beginning of the application.

**Comment by tormeh** [comment]
OK, do you want a pull request on this, or do we wait until we've got a better solution?

**Comment by mmstick** [comment]
@tormeh If you have a solution, then you should submit a PR for review.

**Comment by tormeh** [comment]
OK. Working on it. Have a rough draft. Doesn't compile yet, but hopefully will be working sometime soon...

**Comment by tormeh** [comment]
Having some trouble getting this thing to compile. Once I change the type of data from "&'a str" to "String" I get a lot of errors I weren't expecting. They look like this:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter in function call due to conflicting requirements
   --> src/parser/shell_expand/words.rs:741:47
    |
741 |                 return WordToken::Whitespace(&self.data[start..self.read]);
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 732:5...
   --> src/parser/shell_expand/words.rs:732:5
    |
732 | /     fn whitespaces<I>(&mut self, iterator: &mut I) -> WordToken<'a>
733 | |         where I: Iterator<Item = u8>
734 | |     {
735 | |         let start = self.read;
...   |
745 | |         WordToken::Whitespace(&self.data[start..self.read])
746 | |     }
    | |_____^
note: ...so that reference does not outlive borrowed content
   --> src/parser/shell_expand/words.rs:741:47
    |
741 |                 return WordToken::Whitespace(&self.data[start..self.read]);
    |                                               ^^^^^^^^^
note: but, the lifetime must be valid for the lifetime 'a as defined on the impl at 718:1...
   --> src/parser/shell_expand/words.rs:718:1
    |
718 | / impl<'a, E: Expander + 'a> WordIterator<'a, E> {
719 | |     pub fn new(rawdata: &'a str, expand_processes: bool, expanders: &'a E) -> WordIterator<'a, E> {
720 | |         let flags = if expand_processes { EXPAND_PROCESSES } else { Flags::empty() };
721 | |         let (data, escaped_indices) = preprocess_escapes(rawdata);
...   |
1251| |     }
1252| | }
    | |_^
note: ...so that expression is assignable (expected parser::shell_expand::words::WordToken<'a>, found parser::shell_expand::words::WordToken<'_>)
   --> src/parser/shell_expand/words.rs:741:24
    |
741 |                 return WordToken::Whitespace(&self.data[start..self.read]);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Do you know what I have to do with these? I can harmonize the lifetime of the `&mut self` arguments with the return lifetime. That works for the individual functions, but I think they're all called from `next` and so eventually I have to try there as well, at which point the compiler says
```
error[E0308]: method not compatible with trait
    --> src/parser/shell_expand/words.rs:1285:5
     |
1285 | /     fn next(&'a mut self) -> Option<WordToken<'a>> {
1286 | |         if self.read == self.data.len() {
1287 | |             return None;
1288 | |         }
...    |
1492 | |         }
1493 | |     }
     | |_____^ lifetime mismatch
     |
     = note: expected type `fn(&mut parser::shell_expand::words::WordIterator<'a, E>) -> std::option::Option<parser::shell_expand::words::WordToken<'_>>`
                found type `fn(&'a mut parser::shell_expand::words::WordIterator<'a, E>) -> std::option::Option<parser::shell_expand::words::WordToken<'a>>`
note: the anonymous lifetime #1 defined on the method body at 1285:5...
    --> src/parser/shell_expand/words.rs:1285:5
     |
1285 | /     fn next(&'a mut self) -> Option<WordToken<'a>> {
1286 | |         if self.read == self.data.len() {
1287 | |             return None;
1288 | |         }
...    |
1492 | |         }
1493 | |     }
     | |_____^
note: ...does not necessarily outlive the lifetime 'a as defined on the impl at 1282:1
    --> src/parser/shell_expand/words.rs:1282:1
     |
1282 | / impl<'a, E: Expander + 'a> Iterator for WordIterator<'a, E> {
1283 | |     type Item = WordToken<'a>;
1284 | |
1285 | |     fn next(&'a mut self) -> Option<WordToken<'a>> {
...    |
1493 | |     }
1494 | | }
     | |_^

error: aborting due to previous error
```
I'm at loss here. The type signatures for these values are the same (`&str`) regardless of whether data is `String` or `&'a str` so I don't really get why it now doesn't work. Unless the WordTokens have to be used long after WordIterator is deallocated, in which case I understand why it doesn't work, but not what I should do about it.

Maybe you can take a look at it? [https://github.com/tormeh/ion/compare/wildcard_expansion_after_escaping_%23437___preprocess_string_solution](https://github.com/tormeh/ion/compare/wildcard_expansion_after_escaping_%23437___preprocess_string_solution)

**Comment by tormeh** [comment]
I'm giving up on this, at least until someone can give some advice on how to resolve the ownership issues.

**Comment by AgustinCB** [comment]
I'm going to take a look at this tomorrow.

**Comment by AgustinCB** [comment]
Uhm, this has more problems than I expected...
 
```ion
agustin:~# touch "f\'x"
agustin:~# ls
'f\'\''x'
```

I think it requires some deeper rethinking on the function than what I initially expected.

Because of the way we handle ownership in that part, it isn't particularly easy to modify the input string (as already mentioned) without touching all calls for expand_string.

What are the requirements and use cases for WordIterator? It'll help me make sure I don't break stuff while trying to fix this problem.

**Comment by stratact** [comment]
This bug has been solved in our GitLab server: https://gitlab.redox-os.org/redox-os/ion/merge_requests/784
