### ISSUE TITLE
Remove @len() and Migrate Logic Into $len()

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#448]
Now that we have support for providing expressions to methods, the `$len()` method should be made more versatile. If an array is passed into it, return the number of elements in the array. Once that's done, there's no longer a need for `@len()`.

**Comment by huntergoldstein** [comment]
Doesn't this run into the problem of not being able to tell between a string and a single element array?

**Comment by mmstick** [comment]
You're right. It should be able to tell that the original expression began with either an @ or [.

**Comment by mmstick** [comment]
Just implemented this: https://github.com/redox-os/ion/commit/ac15f60161fda79685fcf9ae7d203be8e38b32b8
