### ISSUE TITLE
issues with history file

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#455]
these issues happen when directly manipulating the history file, so conceivably it's just user error:

```
bash-4.4$ rm .local/share/ion/history
bash-4.4$ for x in $(seq 1000); do echo $x >> .local/share/ion/history; done
bash-4.4$ ion
james:/home/james# head -n3 .local/share/ion/history
1
2
3
james:/home/james# head -n3 .local/share/ion/history
head -n3 .local/share/ion/history
james:/home/james# for x in $(seq 1000); echo $x >> .local/share/ion/history; end
james:/home/james# head -n3 .local/share/ion/history
998
999
1000
```

create a 1000 line history file, see how it changes

```
0d8af9d76b04ddeb0ac060a85e4a05c6f8dca452
rustc 1.19.0 (0ade33941 2017-07-17)
Linux void 4.11.11_1 #1 SMP PREEMPT Sat Jul 15 21:48:45 UTC 2017 x86_64 GNU/Linux
```

**Comment by zwieberl** [comment]
This looks like an upstream-bug from `liner`.
I filed it here: https://github.com/MovingtoMars/liner/issues/76

**Comment by zwieberl** [comment]
This bug was fixed upstream. I tested it using liner v0.4.4 and now the history file works as expected.

**Comment by aeosynth** [comment]
indeed. new issue: 1000 lines is much too short for the default size.
