### ISSUE TITLE
Use ion variables to configure shell behavior

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#46]
For example, the maximum history stored in the shell should be set to a reasonable default and changed by changing the value of some variable.

Discussion: Should special variables that change shell behavior differ from normal variables in ion? With the history example, whenever someone pushes to history it would check to see if it exceeds the maximum history variable and then pop until this is not true. This works fine with normal variables. However, say we wanted to immediately shrink the history size when someone changed the variable. In this case we would need a special mechanism to fire a function on changes to the max history size variable.

**Comment by mmstick** [comment]
https://github.com/redox-os/ion/pull/116/
