### ISSUE TITLE
`examples/run_examples.sh` halts forever

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#461]
**Reproduction**: Execute `examples/run_examples.sh` 

**Expected behavior**:
```
$ examples/run_examples.sh              
   Compiling ion-shell v1.0.5 (file:///home/hunter/Documents/redox-os/ion)
    Finished dev [unoptimized + debuginfo] target(s) in 10.7 secs
Test /home/hunter/Documents/redox-os/ion/examples/arrays.ion [PASS]
Test /home/hunter/Documents/redox-os/ion/examples/basic_condition.ion [PASS]
Test /home/hunter/Documents/redox-os/ion/examples/braces.ion [PASS]
...
```

**Actual behavior**:
```
$ examples/run_examples.sh
   Compiling ion-shell v1.0.5 (file:///home/hunter/Documents/redox-os/ion)
    Finished dev [unoptimized + debuginfo] target(s) in 9.69 secs
...
<nothing happens>
```

**Build information**: 
- `git rev-parse HEAD`: e9cc1a1eb713c6184a01a8b8bfa6b825811676ee
- `rustc -V`: rustc 1.19.0 (0ade33941 2017-07-17)

**Misc**: 
- It looks like [Travis is also experiencing this issue](https://travis-ci.org/redox-os/ion/builds/256703813).
- I was able to track down the first offending commit: ec9df4341d8ec0b5abe7bbb372517fc51e1af28e

**Comment by huntergoldstein** [comment]
Specifically, what looks like is happening is that any time `ion` is a subprocess, it will halt on:
 ```
let _ = sys::tcsetpgrp(0, pid);
```
So `cargo run -- ...` and `run_examples.sh` both halt but just directly invoking `ion` is fine.

**Comment by huntergoldstein** [comment]
It appears that the solution is [https://stackoverflow.com/questions/5341220/how-do-i-get-tcsetpgrp-to-work-in-c](ignoring `SIGTTOU`). If I add the following line:
```
libc::signal(sys::SIGTTOU as libc::c_int, libc::SIG_IGN);
```
before setting the process group, the above works as expected.

**Comment by jackpot51** [comment]
Oops, thanks for catching that @huntergoldstein
