### ISSUE TITLE
Load an init file when starting the shell

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#47]
We need something like `.zshrc`, `.bashrc` or `.config/neovim/init.vim`.

**Comment by polymetric1** [comment]
I might try to do this.

**Comment by skylerberg** [comment]
Great! The main thing we need for this this is the logic for a `source` or `.` command. That is to say a command that takes a file and runs it in the context of the current shell. After that we just need logic for finding the file in a default location.

I haven't looked at the code in a while, but it may be worth looking at what happens when you try to run `ion` non-interactively. It opens a file and then executes the contents of it, which is pretty much identical to what we need.

**Comment by hauleth** [comment]
No `.` command! Make it noop (or equivalent to `cd .`, which is noop). Use only `source`.

**Comment by mmstick** [comment]
Is someone still attempting to implement this functionality right now?

**Comment by Ticki** [comment]
This should pretty much be fixed by a 5 line edit.

**Comment by polymetric1** [comment]
I totally forgot about this, I don't really think I know how, anyone else can do it

**Comment by mmstick** [comment]
I've implemented the functionality and will be making a pull request for it soon.

**Comment by mmstick** [comment]
Attempting to get this pull request merged: https://github.com/redox-os/ion/pull/102
