### ISSUE TITLE
Allow `read` builtin to take input from non-tty `stdin`

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#474]
**Reproduction**: Attempt to have `read` take input from anything except a terminal, for example:
```
$ echo foo | read bar
```
**Expected behavior**:
```
$ echo foo | read bar
$ echo $bar
foo
```

**Actual behavior**: 
```
$ echo foo | read bar
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("Unable to get Termios attribute.") }) }', /checkout/src/libcore/result.rs:860:4
$ echo $bar
<no output>
```

**Build information**: 
- `git rev-parse HEAD`: 2c62ffb8ff8c20aa442c6c3ae9d7f0397baf1460

------

The solution to this is to have the `read` builtin determine if its `stdin` is a tty or not; if so, it will use the nice `liner` prompt, otherwise it will read the next line from `stdin`.

**Comment by huntergoldstein** [comment]
I now realize that #469, because it forks the shell running the builtin, will discard all changes to the shell made within the pipeline, which means we'll need a new strategy to be able to do something like `echo foo | read bar`.

**Comment by mmstick** [comment]
Should be possible to pipe builtins without working, with some changes to builtin parameters and the builtins themselves to write direct to a FD instead of using `println`/`eprintln`/`io::stdout`/`io::stderr`.

**Comment by huntergoldstein** [comment]
I'm working on a quick fix for #332 right now which solves part of this: when we `execute` (i.e. a single command / builtin that isn't part of a data stream) I just overwrite stdin/stdout/stderr using `dup2` then restore them later.

**Comment by huntergoldstein** [comment]
One thing we can do is run the pipeline piece-wise: if we see a builtin we execute everything before the builtin, then execute the builtin, then the rest of the pipeline, and so on. The input for the builtin will be buffered in the pipe, the rest of the pipeline can run concurrently. Any other ideas?

**Comment by mmstick** [comment]
That sounds like a good idea, if it can be done.

**Comment by mmstick** [comment]
It'd be ideal if we can get them to run concurrently

**Comment by huntergoldstein** [comment]
Apparently `zsh` supports `read`ing from a pipe, but [it is undefined behavior in Bash](https://stackoverflow.com/questions/2746553/bash-script-read-values-from-stdin-pipe). [Here's the relevant source and explanation for `zsh`](https://sourceforge.net/p/zsh/code/ci/master/tree/Src/exec.c#l328). This issue is important for at least allowing:
```
$ read foo <<< ....
```
Or, if we implement #380, so that one can do:
```
fn foo
  while read bar
  ...
end
...
cat file.txt | foo
```
