### ISSUE TITLE
error when echoing to file

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#478]
```
# echo foo > bar
ion: failed to close file '3': Bad file descriptor (os error 9)
```

the file is created successfully

**Comment by mmstick** [comment]
I suppose we just need a conditional check to not attempt to close a Fd if that Fd is 1/2/3.

**Comment by huntergoldstein** [comment]
My bad; its because the file descriptor is double-closed (once by dropping `RefinedJob` another manually in `shell::pipe::builtin`). Fixing this by having the forked process handle closing the file descriptors.
