### ISSUE TITLE
Git prompt

### ISSUE THREAD

**Issue by msehnout** [redox-os/ion#489]
Is git plugin desired feature for Ion or should it be in a separate crate? Looking at the fish shell, it looks like they have git functions built in and used in a prompt.

If it is, is anyone working on it?

**Comment by mmstick** [comment]
No one is working on it, but I would like to see support integrated -- either directly within Ion or as a loadable plugin.

**Comment by msehnout** [comment]
Then I'd like to help with that. 

My idea is to implement a buildin, e.g. "ion_git_prompt", that would print something like "[master;2↑...]". This could be used while printing the prompt. But, Ion is using a variable to store prompt format, so this would have to be re-evaluated every time we print a prompt. Do you agree with such solution?

**Comment by mmstick** [comment]
How about a builtin named `ion-prompt` that takes a string argument and returns the corresponding information? Something else that we could do is enable prompt creation through functions. If a function named `ion_prompt' was created, then the output of that function would be used as the prompt.

**Comment by msehnout** [comment]
I can imagine the function, but not sure what you mean by the string for the `ion-prompt` builtin. Can you explain it in more detail? Would it take sth like this `{RED}{USER}@{HOSTNAME}|{GITPROMPT} $`?

**Comment by mmstick** [comment]
Wondering if it might be a good idea for us to have something like this:

```sh
echo ${git::branch} \
   ${git::untracked_count} \
   ${git::modified_count} \
   ${git::lines_added} \
   ${git::lines_removed}
```

Basically, elevate `git` to being a variable scope keyword.

**Comment by mmstick** [comment]
Just implemented variable namespace support. Will try creating a dynamic library for git namespace support, and importing it.

**Comment by mmstick** [comment]
I'll have plugin support and a git plugin out by the end of tomorrow. I have dynamic loading of plugins working really well on my local system, and a git plugin that currently supports getting the name of the current branch. Invoked by `${git::branch}`.

**Comment by mmstick** [comment]
Just landed some basic string namespace plugin support in master. The README has been updated and provides instructions for installing the git plugin, which is very limited at the moment. It only implements `branch`. More functions to come later.

**Comment by msehnout** [comment]
If you wanted any help, I'd like to contribute. I just don't want to duplicate your work.

**Comment by mmstick** [comment]
If there's features you want, I would go ahead and implement them. I'm pretty busy, so it may be a while before I can get around to implementing everything. I wouldn't worry about duplicated work. Duplicate work is better than no work. If you happen to submit a PR for something I began work on, then I'd just compare solutions and offer insight from my own solution, if needed.

**Comment by mmstick** [comment]
The color namespace has been added. I've added all the codes listed [here](http://misc.flogisoft.com/bash/tip_colors_and_formatting#terminals_compatibility) for 8/16-bit colors. IE:

```
echo ${color::bold}${color::light_red}test
echo ${color::cyanbg}test
```
