### ISSUE TITLE
Time Command Should Time Functions & Builtins

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#490]
The current `time` builtin is very simplistic, and only supports timing external commands.

**Comment by chrisvittal** [comment]
I've been looking into this. 

I'm wondering if there is any way to put the `args` back into the the shell and execute them there, or if that is even the best solution. Do we already have the full parse tree for the `args` here?

I don't know how `time` is implemented in other shells, however I feel like we shouldn't be timing how long it takes ion to join and re-parse the arguments time has been given.

Thanks!

**Comment by mmstick** [comment]
I believe the solution would be to make `time` a keyword, rather than a builtin command.

Statements are parsed & mapped in `src/parser/statement/parser.rs`. We'd just need to add `Time` as a Statement keyword on it's own. The logic for handling these variants is in `src/shell/flow.rs` -- we'd just treat the `Time` variant as if it were a regular pipeline.

Something to consider though is that because the time command can time other keywords, the `Time` variant should contain a `Statement`.
