### ISSUE TITLE
`not` ignores global paths

### ISSUE THREAD

**Issue by suhr** [redox-os/ion#493]
```
# ping
Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
# not ping
Error: Unable to find `ping' in PATH: No such file or directory
```

**Comment by drosseau** [comment]
Can you give some more information? I can't repeat this on my build.

**Comment by bb010g** [comment]
What versions of ion are both of you running?

**Comment by drosseau** [comment]
Mine is built from that commit (most recent).

We should probably have a `--version` flag.

**Comment by mmstick** [comment]
Doesn't happen on my end either. The not builtin hasn't been modified since creation, so it shouldn't matter which commit was in use.

**Comment by suhr** [comment]
Well, my `ping` is `/bin/ping`, not in `/usr/bin/ping`.

> What versions of ion are both of you running?

v1.0.5

**Comment by drosseau** [comment]
Did you use `cargo install ion-shell` or build from source? I don't recognize that error format, if it isn't finding the command it should be `ion: command not found: <CMD>`.

**Comment by suhr** [comment]
> Did you use `cargo install ion-shell`

Yes I did.

**Comment by drosseau** [comment]
The `not` builtin isn't in the version on crates.io. Try building from source.

**Comment by suhr** [comment]
Looks like this issue is fixed in the git version.

**Comment by bb010g** [comment]
The issue could probably be closed, then.

**Comment by suhr** [comment]
Ok, there was a problem with `/usr/bin/not`, not ion builtin.
