### ISSUE TITLE
src/parser/shell_expand/mod.rs:277 is reachable

### ISSUE THREAD

**Issue by msehnout** [redox-os/ion#495]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
```
let PROMPT = "${USER}@${PWD} (${git::branch})"
thread 'main' panicked at 'internal error: entered unreachable code', src/parser/shell_expand/mod.rs:277
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
see the `@${PWD}` which should have been `\@${PWD}`, but I forgot to backslash it.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

no crash

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, etc.]
$ git rev-parse HEAD
d144f190bdc3fda5760333896fb4511728010326

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by drosseau** [comment]
Looked at this a bit -- if anyone else is looking at it here is some info:

Seems to only be an issue when setting PROMPT.

A minimal example that causes this would be

```
# Note the whitespace
let PROMPT = " {}"
```

`expand_tokens` doesn't like having a that white space with something braced in the prompt.

```
let PROMPT = "{}"
```

works just fine. As does

```
let x = " {}"
```

**Comment by mmstick** [comment]
Yes, it's due to an assumption that we're parsing arguments that have been split, whereas the prompt variable wasn't sent through an argument splitter.
