### ISSUE TITLE
Multi-Line structures and in-line comments.

### ISSUE THREAD

**Issue by jwarner112** [redox-os/ion#498]
Hello,

I'm playing with Ion shell right now and it's so far proven to be very powerful. I'm looking forward to the way this project develops, as well as maybe being a contributor some time soon.

One problem I'm encountering where Bash has proven superior is in multi-line arrays. In Bash:

```
paths=(
    "/opt/bin"       `# A comment`
    "/bin"           `# Another comment`
    "/usr/bin"       `# Yet another comment`
    "/usr/local/bin" `# Some kind of comment I guess?`
)
```

This is a sequence that allows me to neatly edit my `$PATH` with all the above paths, and the backtick trick allows me to have inline comments explaining what each one is. The example is trivial but in production I make good use of this. I'd rather not _need_ the backtick hack, but that's the only way to get the desired behavior.

In Ion, there appears to be no equivalent-- I can't get inline comments and can't get a `#` to simultaneously respect the final `\` without the shell crashing on me.

I'm looking to discuss possible solutions, ranging from a simple inline-comment syntax to even a special syntax for collections that span multiple lines. For example, I like the way this looks:

```
let paths = [
    /opt/bin,       # The quotes here are optional
    /bin,           # I left them out of this example because what the hey
    /usr/bin,       # the ',' character tells Ion explicitly not to IGNORE the newline,
    /usr/local/bin, # but omit it when storing the array, so that the comment can properly be dropped
    # mixed feelings on this end comment
    # And also on this last-element-trailing-comma, but I normally work in Python
];
```

Still, it might be easier to implement this:

```
let paths = [ \
    /opt/bin       /*Inline comment that ends here ->*/ \
    /bin           /*Another comment*/ \
    /usr/local/bin /*You get the idea*/ \
];
```

Thoughts?

**Build information**:
```
jwarner:~$ rustup -V
rustup 1.5.0 (92d0d1e9e 2017-06-24)
jwarner:~$ rustc -V
rustc 1.19.0 (0ade33941 2017-07-17)
jwarner:~$ cargo -V
cargo 0.20.0 (a60d185c8 2017-07-13)
jwarner:~$ uname -a
Linux jwarner 4.4.0-81-generic #104~14.04.1-Ubuntu SMP Wed Jun 14 12:45:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
jwarner:~$ # ion-shell = 1.0.5 (but can't find where to get that via CLI) 
```

**Comment by mmstick** [comment]
### Version Info

To get version information, the exact git commit is the only piece of information that matters.

#### With Bash:

```sh
git log -n 1 | head -1 | awk '{print $2}'
```

#### With Ion:

```sh
echo @(git log -n 1)[1]
```

### Solution To Problem

Basically, this is easily resolved by adding the required logic to the QuoteTerminator structure. It is what determines whether a given statement is terminated, or unterminated, and thus whether a subsequent line should be requested. We may just want to add `[` as a character that is allowed to be unterminated, and if unterminated, request subsequent lines until the corresponding `]` is found. We can support the following syntax pretty easily:

```ion
let array = [
    one # this is a comment
    two # this is also a comment
   three # and another comment
]
echo @array
> one two three
```

Now, if you're interested in implementing this, I would simply look for the QuoteTerminator structure and implement it there.

**Comment by jwarner112** [comment]
Thank you!

> Version Info

Does any or all of this hold if it was installed solely by Cargo and is not connected to the Git repo? The hash would have to be whichever matches the stable commit for `1.0.5`.

> QuoteTerminator

Thanks for the tip! Since I want to dig into this soon, if you wanted to let this issue float for awhile I'll be happy to at least look into it. That said, if this gets higher priority, no need to wait on me. I'm just starting Rust-wise.

**Comment by mmstick** [comment]
Ion development moves at such a rapid pace that the stable build is basically a decade old in Ion years. Much has been implemented and fixed since them. So, I'd recommend always testing against the latest master of Ion when reporting issues.

If you need tips on how to implement this, I can help out.

**Comment by jwarner112** [comment]
Oh cool, I'll give that a look once I get a few minutes then and see if
it's still happening. Same with the help, if I need it!

**Comment by BafDyce** [comment]
+1 for the feature request! Looking forward to its implementation! ;)

Also, thanks for pointing out this neat comment trick for bash! Will definitely come in handy in the future :)

**Comment by mmstick** [comment]
Are you still working on this? I may look into implementing this feature soon.

**Comment by jwarner112** [comment]
I wish I could say I was, but work has been real busy lately. If you have time to get to it, have at it!

**Comment by mmstick** [comment]
Alright, so I've implemented this. Everything seems to be working, but could use some additional testing.
