### ISSUE TITLE
Add environment variable to define commands that should NOT be saved in the history

### ISSUE THREAD

**Issue by BafDyce** [redox-os/ion#503]
For example, bash (and probably other shells too) ignores commands starting with a space when `HISTCONTROL` is set to `ignorespace` or `ignoreboth` (see www.delorie.com/gnu/docs/bash/bashref_62.html). This would be a useful feature and is part of my current daily workflow.

For ion, we could add a variable such as `HISTORY_IGNORE` which contains rules to influence which commands are saved to the history.

**Blocking/related**: #502 

**Misc**:
I'd be happy to implement this feature, however I'd like to have it discussed it first:
* Do you/the community think this is a useful addition?
* Is `HISTORY_IGNORE` a good name?
* Should the "ignore-character" always be a space? Any whitespace? Any user-defined character?
* What's a sane way to combine this with the issue mentioned in #502?

**Note**:
I've created two separate issues, feel free to merge them if you think that would be better.

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by mmstick** [comment]
- I think the name would be fine, or we could even just use the same name as Bash.
- For simplicity, we should probably simply have it as any whitespace.
- As for #502, it would be ideal if we could just have a temporary history buffer that stores the last issued command in memory, whether it failed or not, without committing it to the disk for long term calling. However, you'd need to delve into the liner crate to figure out how to implement that.

**Comment by BafDyce** [comment]
I started implementing this feature today. However, I am not quite sure what the ` || self.control_flow.level > 0` check in [src/shell/binary.rs, line 278](https://github.com/redox-os/ion/blob/master/src/shell/binary.rs#L278) is for.

This condition will only be checked when `self.previous_status` equals `NO_SUCH_COMMAND`. And if I understand the logic in [src/shell/flow_control.rs](https://github.com/redox-os/ion/blob/master/src/shell/flow_control.rs) correctly, `self.control_flow.level` is only greater than zero if we're inside a function, if/else block, match body, etc. Therefore, I don't get this additional check at all. Is someone able to explain this to me?

**@ name** I'll use `HISTORY_IGNORE` as this is consistent with  `HISTORY_SIZE`. Also, I'd like to use a different name than in bash as the syntax/keywords will be different. However, we could also make it consistent with `HISTFILE*` env variables and name the variables `HISTSIZE` and `HISTIGNORE`.

**@ whitespace**: sounds like a reasonable default. I will use this.

**@ 502**: if it's ok, then i'll add a "no_such_command" switch to the ignore variable, however I'll definitely look into possible solutions for such a temporary buffer.

**Comment by mmstick** [comment]
@BafDyce I don't believe it's useful to have that extra part anymore, so it can be removed. It does do exactly what you think it does -- being greater than 0 indicates that the statement being executed belongs to a nested block.

**Comment by mmstick** [comment]
I also wonder if it would be useful to block commands from being stored based on a regular expression, if we had an array that defined expressions to check for.

**Comment by BafDyce** [comment]
Then the statement never made sense, I guess :D
I'll remove it.

Regular expressions will definitely be a nice extension. I'll try to come up with a way to cleanly integrate it.
