### ISSUE TITLE
Suggested Auto-complete doesn't disappear after not being selected

### ISSUE THREAD

**Issue by rschulman** [redox-os/ion#510]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Issue a command with an argument (`ls stuff` is a good example).
Following that, begin typing the same command (`ls`) and ion will auto-suggest `stuff`.
Hit enter to accept only the shorter command (`ls<CR>`).

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
Ion should remove the autosuggested text, unless it was actually used by the user.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
Ion shows the correct output (e.g. directory listing of the current directory, not the suggested one) but on the command line still shows the unused suggested text.

**Comment by drosseau** [comment]
I have a pull request on liner for this right now.

**Comment by BafDyce** [comment]
Link to the PR in question, if anyone wanna see it.

https://github.com/MovingtoMars/liner/pull/66

**Comment by drosseau** [comment]
This is now fixed using the latest liner.

**Comment by bb010g** [comment]
Since we're depending on 0.4.1, can this be closed?

**Comment by mmstick** [comment]
Indeed. Closing now.
