### ISSUE TITLE
Add a mechanism to get ions version

### ISSUE THREAD

**Issue by BafDyce** [redox-os/ion#515]
**Expected behavior**:
It would be great if ion would provide some mechanisms to retrieve some version information about the binary. e.g. via `help about` or `ion --version`
This information could include a "fixed" version such as `1.0.5 Alpha` and/or the latest commit hash when the binary was compiled, as well as (optional) the systems' version.

This is especially helpful during development to quickly check if one runs the "new" version or not. 

**Actual behavior**:
Currently, ion does not provide any mechanism to retrieve its version.

**Misc**:
To be honest, I don't know how hard it is to retrieve the latest commits hash at compile time. Another useful addition would be to display additional information such as the current (at compile time) branch and whether there were unstaged changes.

**Comment by mmstick** [comment]
Very easy to get the commit hash, actually. Off the top of my head, we could modify the `build.rs` file to grab the commit and write the hash to a file, then just use an `inline_str!(FILEPATH)` macro to embed that string into the binary.

**Comment by drosseau** [comment]
Seems like this wasn't auto closed because I put the wrong format in the PR. It can be closed now I believe.
