### ISSUE TITLE
1eceb5e broke array assignments?

### ISSUE THREAD

**Issue by BafDyce** [redox-os/ion#517]
1eceb5e for reference

**Reproduction**:
```
# let good:[] = [ 1 ]
# let bad = [ 1 ]
thread 'main' panicked at 'internal error: entered unreachable code', src/shell/assignments.rs:253
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Expected behavior**:
`let bad = [ 1 ]` should work just the same way as before.

**Build information**:
```
$ target/debug/ion --version
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev 1eceb5e36002cfca610f18d78e2b99336c04fbe5
```

**Misc**:
In d778741 this was still working.

**Comment by mmstick** [comment]
I see. Missed a variant type. Should also allow the `Any` type.
