### ISSUE TITLE
Should ion compile with stable or nightly?

### ISSUE THREAD

**Issue by BafDyce** [redox-os/ion#519]
The current master (6308880) only compiles with nightly, and also `.travis.yml` is set up to compile with nightly.
However, I think @mmstick once mentioned that ion should target the stable release channel of rustc. This is also supported by the "Compile / Install Instructions" section in the readme. (no instructions to switch to rustc nightly)

So, we (or better: ions core team) should agree on whether ion should always compile with the stable version of rustc or with nightly. Afterwards, the following steps should be done:
- Update `.travis.yml`
- Add a note about which rustc channel to target to the readme

Things to consider:
- redox requires the nightly toolchain. When compiling redox, the same rustc version is used for compiling ion too (I think). Is it guaranteed for software which compiles with stable rust, to always also compile with nightly? If not, ion should probably target nightly in order to avoid failing builds of redox.

**Comment by mmstick** [comment]
I think the main problem is that rustfmt keeps formatting code so that it only compiles nightly, by removing commas from match cases.

**Comment by mmstick** [comment]
Oh and, at the moment, we are Ion's core team :P

**Comment by BafDyce** [comment]
> I think the main problem is that rustfmt keeps formatting code so that it only compiles nightly, by removing commas from match cases.

I see. Well, then I'll also switch to rust-nightly. I will also see into setting up rustfmt.

> Oh and, at the moment, we are Ion's core team :P 

Oh, haha :D

**Comment by bb010g** [comment]
The AUR [`ion-git`](https://aur.archlinux.org/packages/ion-git/) package needs to be updated then to use nightly instead of stable.

**Comment by mmstick** [comment]
Surprised that the AUR wasn't already using nightly, given how often we bump up to higher versions / occasionally require nightly temporarily.

**Comment by mmstick** [comment]
Anyway, I'm going to say that we should probably just based our development on Nightly. Nightly has all the good stuff for development, and Ion's not released yet. No point worrying about stable support at the moment.
