### ISSUE TITLE
Running ion produces error, "ion: extra values were supplied and ignored"

### ISSUE THREAD

**Issue by logankaser** [redox-os/ion#525]
**Reproduction**: Run ion

**Expected behavior**: 
No error on run as previously. 

**Actual behavior**: 
Ion errors with:
"ion: extra values were supplied and ignored"

**Build information**:
ion 1.0.5 (x86_64-unknown-linux-musl)
rev 0a1564efeb3acfaa2d30960f12a8162903d8d46d

**Misc**: 
This seems to be a regression introduced with the recent refactoring.

**Comment by mmstick** [comment]
What's in your init script? Sounds like too many values were supplied in a let expression.

**Comment by logankaser** [comment]
If that's the case sorry for taking up your time needlessly.
Some sort of indication that this error happened during the parsing of
the init script might be a good idea.

```
#!/usr/bin/env ion
export CHARSET=UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.local/bin:
~/.cargo/bin
export PAGER=less
export PS1='\h:\w\$ '
export XDG_RUNTIME_DIR = /tmp
drop PROMPT
export PROMPT = ${c::0x55,bold}${USER}${c::default}\) ${c::reset}
alias s=sudo
```

**Comment by logankaser** [comment]
Wrapping the prompt string in quotes fixed the issue..
I blame coffee.

**Comment by mmstick** [comment]
It's probably the prompt variable. I would have it enclosed within single quotes. It's possible to set multiple variables at the same time, so each value on the right hand side (whether it's an array or a string) will be mapped to their corresponding key.

**Comment by mmstick** [comment]
I will enhance the error message to print the name of the variable that's receiving too many values.

**Comment by logankaser** [comment]
That's a great idea!
