### ISSUE TITLE
ion does not work with dmenu

### ISSUE THREAD

**Issue by logankaser** [redox-os/ion#526]
**Reproduction**: Run dmenu with ion as the shell

**Expected behavior**:
ion would allow dmenu to run shell commands and aliases as with other shells.

**Actual behavior**:
Ion crashes with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 25, message: "Not a tty" } }', src/libcore/result.rs:860:4
                               note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Build information**:
ion 1.0.5 (x86_64-unknown-linux-musl)
rev 0a1564efeb3acfaa2d30960f12a8162903d8d46d
(Not relevant here, has been a long standing issue.)

**Misc**:
Related to #506 where dmenu does not work as expected in scripts.
I believe that this is the cause of #506 .

**Comment by mmstick** [comment]
I'm not seeing this with the current master of Ion.

**Comment by logankaser** [comment]
I'll verify it on my machine.


28. Oct 2017 11:13 by notifications@github.com:

**Comment by logankaser** [comment]
I'm still working on this, unfortunately Alpine Linux does not support rust nightly so I'll need to do a bit more work and setup a container to compile it from void linux.

**Comment by mmstick** [comment]
@logankaser So you can't use rustup to install Rust on Alpine?

**Comment by logankaser** [comment]
@mmstick Unfortunately not, rustup does not support alternative lib C's at the moment. Void linux has rolled their own rust nightly package that works with musl. There is an ongoing issue for this in rustup.

**Comment by logankaser** [comment]
After much headaches and pitfalls, I got Ion to run on Alpine by cross-compiling from a docker container of a distro with rust nightly support.
I now get this error:
```
dmenu_run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 25, message: "Not a tty" } }', /checkout/src/libcore/result.rs:906:4
                                                                                                                                                                           note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Note the different line number of the error. It is now line`906` instead of line `860`.

**Comment by mmstick** [comment]
How are you running dmenu?

**Comment by logankaser** [comment]
`dmenu_run`, no arguments.

**Comment by logankaser** [comment]
Backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr:
Os { code: 25, message: "Not a tty" } }', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   5: core::panicking::panic_fmt
             at /checkout/src/libstd/panicking.rs:498
   6: core::result::unwrap_failed
   7: liner::context::Context::read_line_with_init_buffer
   8: <ion::shell::Shell as ion::shell::binary::Binary>::readln
   9: <ion::shell::Shell as ion::shell::binary::Binary>::main
  10: ion::main
  11: main
```

**Comment by stratact** [comment]
@logankaser have you tried the latest revision? Using dmenu doesn't seem to crash Ion anymore.

**Comment by aeosynth** [comment]
with latest, `dmenu_run` w/o arguments works fine, launches programs successfully.
