### ISSUE TITLE
Help flag

### ISSUE THREAD

**Issue by mcandre** [redox-os/ion#528]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

```console
$ ion -h
ion: failed to open "-h": No such file or directory (os error 2)
$ ion --help
ion: failed to open "--help": No such file or directory (os error 2)
$ man ion
No manual entry for ion
See 'man 7 undocumented' for help when manual pages are not available.
```

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

Some basic listing of supported command line flags is displayed.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

ion mistakes both `-h` and `--help` for script paths.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, `ion --version`, etc.]

```console
$ ion --version
ion: failed to open "--version": No such file or directory (os error 2)

$ which ion
/root/.cargo/bin/ion

$ rustc -V
rustc 1.20.0 (f3d6973f4 2017-08-27)

$ cargo search ion-shell
    Updating registry `https://github.com/rust-lang/crates.io-index`
ion-shell = "1.0.5"    # The Ion Shell

$ uname -a
Linux e5ff9b33d0d8 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jD91mZM2** [comment]
This seems to be fixed in the latest ion version. @mmstick perhaps close this issue?
