### ISSUE TITLE
Not able to clone git repos

### ISSUE THREAD

**Issue by olanod** [redox-os/ion#538]
When trying to clone a git(github) repository in my Linux(Arch+gnome) machine git times out trying to connect. 
```
ssh: connect to host git.com port 22: Connection timed out
fatal: Could not read from remote repository.
```
Other shells work as expected. It probably relates to ion not being able to prompt and unlock my ssh key. For example when I use zsh and try to clone a repo I get a (gnome)dialog to unlock the ssh key the first time, for future clones it doesn't ask for the key.

**Comment by mmstick** [comment]
What's the full command that you are using? It works fine on my end.

**Comment by aeosynth** [comment]
> git.com

i had this same issue, the command needs to be escaped/quoted

**Comment by logankaser** [comment]
I believe it is an issue with Ion array syntax using the @ symbol, as HTTPS repos will work fine.
also
`git clone https://url` works fine, while `git clone git@url.git` does not.

**Comment by mmstick** [comment]
Just as the $ sigil is used for obtaining a string variable, the @ sigil is used for obtaining array variables. Arrays are first class citizens here. So you just escape the character, same as you would for $.

```
git clone git\@url.git
```
