### ISSUE TITLE
Syntax for completely launching and disowning a process

### ISSUE THREAD

**Issue by japm48** [redox-os/ion#539]
### Feature request

I would like to see something similar to `&!` in zsh ([documentation](http://zsh.sourceforge.net/Doc/Release/Jobs-_0026-Signals.html#Jobs-_0026-Signals)).

This allows launching e.g. `firefox &!` and keep it running even after the shell (and the terminal window) is closed.

In addition, I would like to see something like `&!!` (not implemented in ZSH or any other shell I know of) which also detaches `stdin` and `stdout` from the spawned process, as some GUI programs can be noisy. This would be a lot cleaner than having to manually redirecting to `/dev/null`.

**Comment by mmstick** [comment]
So this can actually be done right now using the `disown` builtin, which supports the `-h` flag for specifying that a process running in the background should not receive the SIGHUP signal when the shell exits. It works like so:

```ion
firefox &
disown -h 0
exit
```

The `0` being the job ID of the background process. The shell will exit, but the program will continue running.

**Comment by mmstick** [comment]
Now that I think about it, the disown builtin should default to the last-spawned job ID if no job ID is provided.

**Comment by japm48** [comment]
I made some tests, and unfortunately it is not so easy.
If the disowned process tries to output something it will receive the `SIGHUP` signal.
Same problem occurs in bash, see: https://unix.stackexchange.com/a/148698.

Also, this doesn't solve the second request: a clean way to ignore stderr and stdout without using `/dev/null`.

I'm still learning so please bear with me.

In particular I ask a **clean** way to have these behaviours:

1. Spawning a background process.

2. Not killing the process when the shell exits. Solved by `disown` or zsh `&!`; I preferred the zsh way because it already spawns "disowned" and never appears in the `jobs` list, possibly (?) avoiding race conditions when the shell is killed just before executing the disown line.

3. Not killing the process (by SIGHUP) when it writes to stdout or stderr (solved by `nohup`).

4. Not redirecting to the stderr or stdout without having to explicitly redirect to `/dev/null` as it leads to verbose code, also is NOT an option in non-Unix systems, `/dev/null` is not garanteed to exist.

"1", "2" and "3" could be achieved with special `disown` flags; but for "2" I still prefer the zsh way.

"4" can only happen at the start of the process.

Also those behaviours may (or may not?) be optional, e.g.: print to the default stdout/err and automatically *redirect* to `/dev/null` when the spawned process when the shell receives SIGHUP (maybe with a new flag in `disown`?).

I will post an example to easily reproduce the SIGHUP issue.

**Comment by japm48** [comment]
Here is the example test:

File `hello_loop.py` (executable):

```python
#!/usr/bin/env python3
from time import sleep
while True:
    print("Hello World!")
    sleep(1)
```

File `test.ion` (executable):

```sh
#!/usr/bin/env ion
./hello_loop.py & 
disown -h 0
```

Launch with (the important thing is that the terminal **window** should close immediately):
`xterm ./test.ion`

**Comment by japm48** [comment]
Sorry for posting so many replies in a row.

I just found some code I wrote long time ago for "proper detaching" in C: https://gist.github.com/japm48/7d455b195bb28f85577a5b692c8ecda1

Also, of interest:
 - http://stackoverflow.com/a/8888612
 - `daemon` man page in BSD: https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=3 
 - and Linux: http://man7.org/linux/man-pages/man3/daemon.3.html

**Comment by mmstick** [comment]
This can easily be done. Just need to determine the syntax that we'd like to use to specify this behavior. Given that zsh uses `&!`, there's a precedence for us also adopting that syntax. As for also specifying to redirect stdout/stderr, I'm not sure about a good syntax to convey that.

Seems it should be possible to just do the following:

```ion
firefox &> /dev/null &
disown -h 0 (or disown -ah)
```

DOS/Windows actually supports the concept of /dev/null, but they do this by making any attempt to write to a file named 'nul' as doing the same as /dev/null on *nix systems. That said, Ion doesn't support non-unix platforms, and it would be very difficult to gain support for Windows.

There also shouldn't be any race conditions. The only way for the shell to terminate before invoking the disown command would be if you executed the exit command, or had exit-on-error enabled and ran a command that returned an error before you called disown.

**Comment by japm48** [comment]
Ok, that makes perfect sense to me. You can close this issue if you prefer not to implement `&!`.

Some other things:

- I think I hit a bug: `firefox &> /dev/null &` does not put it in background here (something in the parser or am I doing something wrong?). Will file a separate issue for this if you confirm it.

- Another reason I didn't like `>/dev/null` is overhead: accessing the file system to build a pipe to nowhere looked wasteful to me, but I guess that's the Unix way™, so I shouldn't question that :)

- I finally found my original unreadable mess: it was something that needed to go inside a crontab, needed redirects inside `su` and "`bash`ishms" were forbidden (including `&>`). So, nothing actually related to the shell. Sorry for overcomplicating things and diverging.

**Comment by mmstick** [comment]
I believe it's not been implemented yet. There's a number of simple paper cuts in the shell that haven't been addressed yet. That's one of them. Another is performing a redirection and using a conditional operator at the same time. The redirection is only handled for the last job.

As for /dev/null, I'm pretty sure that most shells simply check if that file was given, and automatically handle it without needing to access the file location directly.

**Comment by mmstick** [comment]
This is an update that the multi-stream redirection support has been implemented. I'm currently running Firefox launched from the following command, and the original shell no longer running:

```
firefox-nightly &> /dev/null &
```

Now that this work is complete, implementing the `&!` syntax should be very simple. That is, if we are settled on using `&!` to declare this meaning.

**Comment by jD91mZM2** [comment]
Ok so I was implementing this, but then I noticed that closing `ion` didn't close *any* processes, disowned or not. What's that about?
