### ISSUE TITLE
Request: A cleaner way to export local variables

### ISSUE THREAD

**Issue by Fuzen-py** [redox-os/ion#540]
Currently to export a variable that was defined locally at one time you have to do
```
let ROCKET_LOG="critical"
export ROCKET_LOG=$ROCKET_LOG
```
Is it possible to add a simple ``export $ROCKET_LOG`` or even ``export << $ROCKET_LOG``

**Comment by mmstick** [comment]
If we do it, `export $ROCKET_LOG` would be much easier / efficient to implement.

**Comment by jackpot51** [comment]
@mmstick the syntax should be `export VARIABLE` without a dollar sign

**Comment by Fuzen-py** [comment]
Maybe it could be ``pub let`` at the time of defining the variable, giving it the concept of scope?

**Comment by mmstick** [comment]
Fixed. Source code that implemented the feature is [here](https://github.com/redox-os/ion/commit/863d77946da26e291d525677362477faa0b57a14).
