### ISSUE TITLE
variables and arrays can have the same name

### ISSUE THREAD

**Issue by dns2utf8** [redox-os/ion#541]
**Reproduction**: 
```
user:/tmp# let xs = [ one two 'three four' ]
user:/tmp# echo @xs
one two three four
user:/tmp# let xs = 42
user:/tmp# echo $xs
42
user:/tmp# echo @xs
one two three four
```

**Expected behavior**:
```
user:/tmp# let xs = [ one two 'three four' ]
user:/tmp# echo @xs
one two three four
user:/tmp# let xs = 42
### error ###
````
issue an error message and deny the set or override the array

**Actual behavior**:
Well, it allows the double use.

**Build information**:
installed with `cargo install`
ion-shell       v1.0.5

**Blocking/related**: 

**Misc**: 
In my opinion the feature or storing the arrays and the variables in different namespaces will cause **a lot** of confusion and head scratching.

**Comment by mmstick** [comment]
It's not an issue because of the explicitness. The only way to create an array is to use the [] syntax, and the only way to call an array is with the @ sigil. So I don't see where the confusion would be.

**Comment by ids1024** [comment]
I agree that this is somewhat unintuitive, and possibly could be improved, but I don't know what would be better.

In bash:

```bash
> a=(1 2 3)
> echo $a
1
```

Bash's behavior is probably no less confusing, but in a different way. Another option is for arrays to coerce to strings (adding spaces) and strings coerce to one-element arrays, but that has its own issues.
