### ISSUE TITLE
distinct completions for dir and dir/

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#544]
if i implicit cd to both `~/dir` and `~/dir/`, when i press `~/di<Tab>` i see both of those completions presented; i would expect `~/dir/` to be completed automatically.

**Comment by mmstick** [comment]
Issue is important from a usability perspective. Directories stored in history should always have their ending `/` character.

**Comment by mmstick** [comment]
If I have time after fixing #543, I'll look into fixing this today as well.
