### ISSUE TITLE
hash is not escaped

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#554]
```
$ touch '#abc'
$ rm #<Tab> # rm #abc
rm: missing operand
```

`#<Tab>` should expand to `\#abc`

**Comment by mmstick** [comment]
Likely happened when I added multi-array support. Would you be willing to help add integration tests for things like this?

**Comment by aeosynth** [comment]
i can try, but i'm not very familiar with rust. how would i start?

**Comment by mmstick** [comment]
Integration tests don't require any knowledge. See the examples directory. You could add a line in an ion script there, like

```
echo '#test'
```

Then add the output you expect in it's corresponding `.out` file. Then you could push a PR with that. Your branch will fail if Ion produces an output that's not expected in the out file.

If you want to actually fix the issue, it should be fairly simple. There's a quote.rs module in the parser directory. It's handling the hashes at this time. Sounds like we just need to add a condition to only consider a hash as a comment if neither SQUOTE or DQUOTE flags are set.

**Comment by mmstick** [comment]
Can check if the flags are set with this:

```rust
if self.flags.intersects(DQUOTE | SQUOTE) {
    // Not a comment
} else {
    // A comment
}
```

Which can also be written as

```rust
if self.flags & (SQUOTE + DQUOTE) != 0
```

**Comment by bjnyfv** [comment]
If @aeosynth doesn't want to implement the fix, I would be more than happy to take a stab at it.

**Comment by aeosynth** [comment]
how would i trigger a tab expansion in a script? that's what needs testing.

**Comment by mmstick** [comment]
Do you mean unescaping a tab like `echo -e "\t"`, or tab completion? Tab completion can't really be tested by a script -- scripts don't have access to the `liner` crate's `Context` field in the shell. Tab completion-related tests would have to be written as a unit test either within `liner` or Ion's source code.
