### ISSUE TITLE
$escape() and $unescape() methods

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#556]
Essentially, Bash allows one to convert ASCII sequences into their corresponding codes if that string is enclosed within single quotes that follow the `$`.

```bash
echo $'this\nstring\thas\tspecial\ncodes'
```

```
this
string	has	special
codes
```

We should support this with an `$unescape()` method, like so:

```sh
echo $unescape('this\nstring\thas\tspecial\ncodes')
```

As well as a corresponding `$escape()` method that will do the opposite. We could likely re-use logic from the `echo` builtin to do this.

**Comment by AgustinCB** [comment]
Can I take this task? It will probably take some days, since I need to get used to the code. But I think I understand the parts that are involved and how to do it.

**Comment by mmstick** [comment]
Sure. You would implement this [here](https://github.com/redox-os/ion/blob/master/src/parser/shell_expand/words/methods/strings.rs#L84), with the rest of the string methods.
