### ISSUE TITLE
~/h expands to ~/home

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#557]
```
mkdir ~/h
~/h<Tab> # ~/home/james/h
```

**Comment by zwieberl** [comment]
For me this happens only, if there exists a directory inside ~ that starts with h as well:
if there is none
`~/h<Tab>` -> Nothing happens
if there is e.g. "htest/" inside my home:
`~/h<Tab>` -> `~/home/zwieberl/htest`

Also this happens only for `h`. `~/D<Tab>` works as expected.

**Comment by mmstick** [comment]
Am looking into this now

**Comment by zwieberl** [comment]
I think this might fix it:
diff --git a/src/shell/completer.rs b/src/shell/completer.rs
\-                        if let Some(e_index) = completion.find(search) {
\+                        if let Some(e_index) = completion.rfind(search) {

**Comment by mmstick** [comment]
In addition to this, I think it's about time we thought about how we will go about supporting custom completions and application-specific completions.

**Comment by zwieberl** [comment]
Yes, although this probably deserves its own issue then?
