### ISSUE TITLE
Add !! (bangbang) and !$ syntax

### ISSUE THREAD

**Issue by sajattack** [redox-os/ion#560]
I always forget sudo when running as user so it would be nice to have `!!` so I could `sudo !!`. In case anyone is unaware of what !! is it replays the last command in history. and !$ replays the args. Here's a quick example:
```
$ pkg install gcc
Error blah blah
$ sudo !!
sudo pkg install gcc
Success
```
```
$ ls /tmp
file.txt
file2.txt
$ rm -rf !$
rm -rf /tmp
```

**Comment by mmstick** [comment]
I wonder if this is something that'd make sense as a shortcut in liner, rather than needing syntax support in the language?

**Comment by mmstick** [comment]
To be implement this in ion though, you'd just expand `!!` and `!$` arguments according during the pre-expansion phase. Particularly, if an argument matches one of those, expand it as so, or otherwise pass it on to be expanded by the expander.

**Comment by mmstick** [comment]
Alright, I'll have this implemented in a few minutes.
