### ISSUE TITLE
Command Not Found Hook

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#567]
Ion should do as other shells and offer a means of executing a custom handler in the event of a command not being found. Common use case is for Linux distributions to do a search of their software repository for a package that contains that command.

As for how we do it, I'd think that having a variable define the command to execute would be a good idea, and failing to find that, a function. Something like `let COMMAND_NOT_FOUND = pkgfile`, and if a command isn't found, simply execute `pkgfile <command>` in it's place.

**Comment by zwieberl** [comment]
Should this hook only be applied for a simple statement, or also for stuff like "while" and "if"?
I personally think, only for simple statements, as I would not be comfortable to execute the hook for each iteration of a while-loop for example.

**Comment by jD91mZM2** [comment]
Wouldn't it be better with something like  
```ion
fn COMMAND_NOT_FOUND command
    pkgfile "$command"
end
```
