### ISSUE TITLE
Perform Builtin Lookup When Parsing

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#569]
Jobs should make note if they are a builtin or not during parsing, rather than execution. This would lead to some possibly-big improvements for loops. With the static builtin map, functions will always have the same index position, so the `Job` structure could be extended to contain a static reference to it's builtin function.

**Comment by AgustinCB** [comment]
I just started working on this.

**Comment by mmstick** [comment]
Thanks for looking into this! Will have to see how much of a performance impact this makes on that fibonacci script, and then repost new benchmark scores. We really need more benchmark scripts though.

**Comment by AgustinCB** [comment]
Cool! I'll include it in the PR.
