### ISSUE TITLE
cd should push to the directory stack

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#57]
Once this is implemented, the main difference between `cd` and `pushd` will be that `pushd` prints the directory stack and `cd` does not. Also `cd` should have options like `cd -`, however that is not in the scope of this issue.

**Comment by jackpot51** [comment]
Will there be a limit on stack size?

**Comment by Ticki** [comment]
@jackpot51 `zsh` behavior is to truncate the stack.

**Comment by skylerberg** [comment]
@jackpot51 Yes. It will be the same as the limit on history. I should switch the dir stack to use a VecDeque. It will also be the same as zsh http://zsh.sourceforge.net/Intro/intro_6.html, which just to clarify pops the oldest leaving the DIRSTACKSIZE most recent directories on the stack.

**Comment by skylerberg** [comment]
https://github.com/redox-os/ion/pull/59 closes this issue and limits the stack size.

**Comment by Ticki** [comment]
yay

**Comment by jackpot51** [comment]
cool
