### ISSUE TITLE
can't use empty arguments

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#573]
i have to go into bash to use `rename`:

```
james:~/src/bar# touch long_a long_b
james:~/src/bar# rename long_ '' *
james:~/src/bar# ls
long_a  long_ab
```

**Comment by mmstick** [comment]
I'm confused. Rename accepts empty arguments as valid inputs?

**Comment by aeosynth** [comment]
well, maybe 'empty argument' isn't the right phrase, but rename does accept the empty string: `''`

http://man7.org/linux/man-pages/man1/rename.1.html#EXAMPLES

    Provide an empty string for shortening:

              rename '_with_long_name' '' file_with_long_name.*

    will remove the substring in the filenames.

**Comment by mmstick** [comment]
I see. I guess I'll need to do a more complex action of eliminating empty arguments from array expansions, but allowing them from string expansions.

**Comment by mmstick** [comment]
This is going to require #482 to be implemented.

**Comment by aeosynth** [comment]
btw this is the 3rd time i've reported this issue: #345

**Comment by mmstick** [comment]
It's a very tricky matter to address. There are some scenarios where empty arguments should not be allowed. For example, slicing an array where the range is out of bounds.
