### ISSUE TITLE
C dependency: decimal

### ISSUE THREAD

**Issue by mssun** [redox-os/ion#581]
I found that ion depends on a C library.

The dependency chain is like this: ion -> calc -> decimal (compiled from c code and provide FFI).

I don't know if the statement in the introduction is accurate:

> Ion is a modern system shell that features a simple, yet powerful, syntax. It is written **entirely** in Rust, which greatly increases the overall quality and security of the shell, eliminating the possibilities of a ShellShock-like vulnerability, and making development easier. 

Do we knew that and already have plan to replace it?

  - https://github.com/alkis/decimal

**Comment by mmstick** [comment]
It will be replaced once [bigdecimal](https://github.com/akubera/bigdecimal-rs) is ready.
