### ISSUE TITLE
clear && read: 100% cpu usage

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#584]
clear && read x

**Comment by jD91mZM2** [comment]
Alright, since `clear` is just printing some escape sequences I looked to see if this happened with any program, and it does. Though, echo... clear-ly... doesn't crash it because it's a builtin. Interesting.

**Comment by mmstick** [comment]
I may look into this tomorrow and see if I can figure it out.

**Comment by mmstick** [comment]
We do need to submit a patch to liner to do something about spawning a background thread. I'd like to see the background thread removed entirely, and possibly exposing an event loop function instead, so that we can use a fork w/ a memmap instead of a thread.

**Comment by mmstick** [comment]
@aeosynth Can you verify if this still happens with the latest `master`? Not able to replicate on my end.

**Comment by aeosynth** [comment]
seems fixed, thanks!
