### ISSUE TITLE
Panic With `let a = @(())` / `let a = $(( () ))`

### ISSUE THREAD

**Issue by xTibor** [redox-os/ion#585]
**Reproduction**: 
```
let a = @((b))
```

**Actual behavior**:
A panic with this message: `thread 'main' panicked at 'attempt to subtract with overflow', src/parser/arguments.rs:87:25`
[Backtrace](https://gist.github.com/xTibor/635e560c6fc25f9e5c1ba6aa75da18cf)

**Build information**:
`rustc -V`: `rustc 1.23.0-nightly (d6b06c63a 2017-11-09)`
`git rev-parse HEAD`: 2f176ebe1010b4ebd9e2a9031ad354e598cdee9c
System: KDE neon 5.11 (Ubuntu 16.04 LTS)

**Misc**:
The panic is only reproducible in debug mode. In release mode these overflow checks are disabled by the compiler.

**Comment by xTibor** [comment]
A different expression that triggers the same panic:

```
let a = $(( () ))
```

**Comment by mmstick** [comment]
Should be easy to solve. I'm guessing it has something to do with the `))` at the end. A few eprintln! statements should get to the bottom of that. I can't work on this myself at the moment though.

**Comment by AgustinCB** [comment]
Not sure I understand what's the expected output, sorry, could you expand please?

**Comment by xTibor** [comment]
The first example: No idea, most likely a syntax error. As far as I know there's no such expansion as `@(())` in Ion, only `@()`.

The second example: Ion should try to evaluate the `()` expression inside the `$(())` and throw a calc error that it's invalid. (`expected number token, got CloseParen`)

**Comment by mmstick** [comment]
Seems to be resolved.

**Comment by xTibor** [comment]
Checked it again just to make sure it has been fixed, however it's still reproducible for me with 95fefdd8078b618513e84297241606046dcf3357.

**Comment by mmstick** [comment]
@xTibor Which command are you using to get a panic?

**Comment by xTibor** [comment]
The examples I posted above. Both of them still triggers the panic.

**Comment by mmstick** [comment]
This is what happens on my end:

```
mmstick:~/S/ion# ion --version
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev 95fefdd8078b618513e84297241606046dcf3357
mmstick:~/S/ion# echo @((b))
ion: syntax error: '(' at position 1 is out of place

)
mmstick:~/S/ion# echo $(( () ))
expected number token, got CloseParen instead
```

**Comment by xTibor** [comment]
Try the exact commands with the `let` keywords I posted:
```
tibor:~/git/ion# let a = $(( () ))
thread 'main' panicked at 'attempt to subtract with overflow', src/parser/arguments.rs:83:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
