### ISSUE TITLE
zsh-like autocompletion (paths)

### ISSUE THREAD

**Issue by matthiaskrgr** [redox-os/ion#601]
On both ion and zsh, I can write something like ````cd rust-i<tab>```` and it will autocomplete to ````cd rust-ion````, however zsh also supports path autocompletion between ````/````s, let's say I have /home/matthias/vcs/github/rust, I can write cd ````/h/m/v/g/r<tab>```` and it will autocomplete to ````/home/matthias/vcs/github/rust```` if that is the only match found.
Even /////rust would work if I only had a single "rust" directory at that directory depth in any subfolder (usually this is a silly idea though since zsh would query the FS for all the folder names which causes longer IO wait than actually typing a few letters of the path manually).

Anyway this saves me quite some typing, would be nice to have that in ion as well, in my opinion. :)

**Comment by emturner** [comment]
Hi, am happy to start looking at this - would be nice to have

**Comment by emturner** [comment]
I've been spending time looking through the source code, and slowly trying to piece a few things together.  I've managed to get a (small) example of globbing working - so I'm going to start trying to implement this now
