### ISSUE TITLE
Duplicated method unescape

### ISSUE THREAD

**Issue by AgustinCB** [redox-os/ion#604]
Right now there're three methods `unescape`:

https://github.com/redox-os/ion/blob/5e2b08abafbb2732a5f6f7ae63497d319336127b/src/shell/completer.rs#L130
https://github.com/redox-os/ion/blob/13054955db8ca3ff46dbf0934a35fb2b7f3f0ee1/src/parser/shell_expand/words/methods/pattern.rs#L7
https://github.com/redox-os/ion/blob/0b279389a4dfe2f6c1618964db1bdfe0f690c6c0/src/parser/shell_expand/words/methods/strings.rs#L15

Although the first one is special by itself (as far as I can tell), the other two seem to be used for the same thing.

Should they be merged? Renamed?

**Comment by mmstick** [comment]
The first is specific for escaping filenames for the completer. The other two are for similar purposes, so they could be merged.
