### ISSUE TITLE
Recursive aliases

### ISSUE THREAD

**Issue by passcod** [redox-os/ion#610]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]

```ion
$ alias y=pacaur
$ alias ys='y -Ss'
```

**Expected behavior**: [describe the behavior you would expect the repro to yield.]

```ion
$ ys foo
<`pacaur -Ss foo` runs>
```

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].

```ion
$ ys
ion: command not found: y
```

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, `ion --version`, etc.]

```
passcod:~# uname -a
Linux kaydel-ko 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
passcod:~# rustc +nightly -V
rustc 1.23.0-nightly (e97ba8328 2017-11-25)
passcod:~# ion --version
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev bfe7dffe507bb2565cf9feb92b46da6059b7757b
```

Built from git using cargo install.

**Comment by mmstick** [comment]
A simple while loop should fix this.

**Comment by mmstick** [comment]
All it took was changing `if let Some(alias)` to `while let Some(alias)`.

**Comment by passcod** [comment]
Awesome, thanks 🎉
