### ISSUE TITLE
else if

### ISSUE THREAD

**Issue by pepa65** [redox-os/ion#617]
I have been reading through https://doc.redox-os.org/ion-manual/ and it really makes me want to use **ion** (except I haven't been able to get a working install...)

There  was only one big red flag that went up when reading `7.1 Conditionals`. Now it might be that the description there is not accurately reflecting the actual design choices, but the example raised a big concern that is connected with using `else if` instead of `elif` or `elsif` or `elseif` or `else-if`.

Usually in languages that don't have this, `else if` can still be used, but it is parsed according to normal parsing rules (I am disregarding significant-whitespace languages). But in **ion** it seems there is a keyword that contains a space, `else if` that functions as `else-if`. What happens if there are 2 spaces, will it still work as `else-if`? Or is it parsed regularly when written as `else; if` (requiring an extra end for the new `if`)? I think having a 'keyword' with a space is unusual and bound to be confusing, and I think it will be confusing to people who expect this to work:
```
if c1
    a1
else if c2
        a2
    else
        a3
    end
end
```

I think you're not doing yourselves (as builders/implementers/testers) or users of **ion** any favour. I think the `else-if` functionality is very useful and clear, but not like this. Sorry for sounding impossibly pedantic, I just don't understand why you're doing this to yourselves and the rest of the world.

**Comment by mmstick** [comment]
This was already taken into consideration early on in Ion's lifetime when conditionals were first implemented. [This line of code](https://github.com/redox-os/ion/blob/master/src/parser/statement/parse.rs#L111) is responsible for trimming any whitespace after `"else"`, and then if the string that remains starts with `"if "`, then we know that we have an else if condition. Simple.

```ion
if c1
    a1
else if c2
        a2
    else
        a3
    end
end
```

This would work -- you'd just get a warning about an extra end after the conditional executes.

**Comment by pepa65** [comment]
Of course you can implement it this way. It is just not wise.

The fact that this bad example code would work with only a warning about an extraneous end means that your language cannot be trusted. :-(

**Comment by mmstick** [comment]
@pepa65 Effectively every programming language implements else if as two separate words -- [Fish also does this with their shell](https://fishshell.com/docs/current/tutorial.html#tut_conditionals). So no, there is nothing wrong with having spaces between else and if. The only language that I can think of that invented it's own else if keyword rather than using 'else if' is POSIX shell, and we are not implementing POSIX shell.

**Comment by pepa65** [comment]
Oh, you are right, fish shell does it too..! And Fortran...

The defining characteristic of else-if is that it doesn't start a new clause, but it is a part of the if clause. Hence why it can be confusing for the human parser, the `if` in `else if` doesn't start a new clause, there is no extra `end` statement.

I'll leave you to it.
