### ISSUE TITLE
and/or followed by let results in command not found

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/ion#619]
**Reproduction**:

```
echo "This does not have a bad exit status"; and let x = "something"
```

**Expected behavior**:
`x` is set to `something`

**Actual behavior**:
```
ion: command not found: let
```

**Build information**:

A `git bisect` showed that this started at 7d9584ee254b6019343d034a4de07e2b5c3e19bd

**Comment by mmstick** [comment]
Fix should be to check if the first argument is a builtin command or not, and handling it accordingly.

**Comment by Sag0Sag0** [comment]
Working on it.

**Comment by AgustinCB** [comment]
Would this make sense in the first place? Why not just `echo "This does not have a bad exit status"; and eval let x = "something"`? (Which works as expected)

**Comment by dlrobertson** [comment]
Not excited about forcing the use of `eval` in this case, but it certainly reasonable.

**Comment by mmstick** [comment]
In other shells, the `and`, `not`, and `or` commands are not builtins, but keywords (like `let`).

**Comment by mmstick** [comment]
Then again, it seems Fish has them as builtins?

**Comment by mmstick** [comment]
Funny how that works, but their source code looks similar-ish to ours https://github.com/fish-shell/fish-shell/blob/master/src/builtin.cpp#L409:L464

**Comment by mmstick** [comment]
Then again, maybe not? Is confusing that they have control flow keywords listed as builtins.

**Comment by AgustinCB** [comment]
I don't use fish, what happens when you do a similar command there?

On the other hand, when I think of those boolean operations (`and`, `not` and `or`) I think of boolean operations. `let` doesn't return a value, so it wouldn't make sense to use it in this kind of operations. For example, why would you support `not let x = "something";`? If the idea is to do a conditional... Well, you can just use `if`. In that sense, I prefer an strong well defined syntax over a flexible one.

I guess this will require solve some question first:

- Should `and`, `not` and `or` be just boolean operations or some kind of control flow?
- If they should be boolean, but we want to support that syntax, what should be the return value of `let` or how should they treat that return value?
- Should they be keywords or bultins?

**Comment by AgustinCB** [comment]
I just tried `echo 'hola'; and set x "something"` in https://tio.run/#fish-shell and it works as suggested here. I think the difference is that `set` is a builtin: https://github.com/fish-shell/fish-shell/blob/master/src/builtin.cpp#L454 and it handles status codes: https://github.com/fish-shell/fish-shell/blob/master/src/builtin_set.cpp#L155.

Maybe that's the way to go?

**Comment by mmstick** [comment]
We should probably implement them as keywords in our shell, because `let` requires special parsing rules (hence the need for let to be a keyword). Keywords have the highest level of control over their execution.

**Comment by AgustinCB** [comment]
I just tried echo 'hola'; and set x "something" in https://tio.run/#fish-shell and it works as suggested here. I think the difference is that set is a builtin: https://github.com/fish-shell/fish-shell/blob/master/src/builtin.cpp#L454 and it handles status codes: https://github.com/fish-shell/fish-shell/blob/master/src/builtin_set.cpp#L155.

Maybe that's the way to go?

**Comment by AgustinCB** [comment]
Oh, sorry, I didn't see your last message:

Yeah, that makes sense. And what should be the behavior of things like:

```
let x = "something"; and echo "hola"
```

When should echo be executed? Every time?

**Comment by mmstick** [comment]
In the above example, the `let` command would exit with a `SUCCESS` exit status, which would thereby continue to print `hola`. There are cases where a `let` operation can fail though. For example, the `and` condition that follows will not execute:

```ion
let x:int = something; and echo "hola"
```

**Comment by mmstick** [comment]
@AgustinCB Look for `Statement::Time` as an example of how And/Or/Not could be implemented. Their implementation would be similar, but rather than computing times, you'd just execute based on the current exit status stored in the shell.
