### ISSUE TITLE
'\@' not being escaped properly in prompt

### ISSUE THREAD

**Issue by covercash2** [redox-os/ion#641]
**Reproduction**: 

in initrc:
```ion
fn PROMPT
    printf "username\@$(hostname)"
end
```

outputs:
`username`

**Expected behavior**:
expected output:
`username@host`

**Build information**: 
ion 1.0.5 (x86_64-apple-darwin)
rev 2224412590d0d86a46bfc6a3603faf0c5c276981

rustc 1.24.0-nightly (c8ddf2852 2017-12-07)

**Misc**

i tested the same input in my Debian VM and was unable to reproduce the bug. so, AFAIK, this is a macOS bug.

ion 1.0.5 (x86_64-unknown-linux-gnu)
rev c6bdc75cbf3152b3dc3ddfe20c81c73d26f28899

rustc 1.24.0-nightly (c8ddf2852 2017-12-07)

**Comment by mmstick** [comment]
A Mac OS bug? That's odd, as there shouldn't be anything OS-specific happening in Ion (beyond using common UNIX syscalls & their Redox equivalents). Yet I also can't replicate this from my Solus & Arch machines.

**Comment by covercash2** [comment]
[here's](https://github.com/redox-os/ion/blob/e81543bfc389136a355815d3e47e5266adb405b8/src/shell/binary/prompt.rs#L24) where i've tracked it to so far.

#### minimal initrc

initrc:
`fn PROMPT
    printf "${USER}\@$(hostname) > "
end`

in the `Ok(result) =>` block i printed the string returned from the stdout of the forked process. the '@' symbol is being escaped prematurely on macOS. 

i.e., fn PROMPT output:

Debian 4.9.51-1:
`username\@host > `

macOS (Darwin Kernel Version 15.6.0):
`username@host > `

fn [expand_string](https://github.com/redox-os/ion/blob/e81543bfc389136a355815d3e47e5266adb405b8/src/shell/binary/prompt.rs#L13) then interprets the `@host` portion as an array declaration, so the prompt string is printed as `username > `. 

the funny thing is: if the prompt function is run from the REPL, it outputs just fine. 

i.e., `$ PROMPT` outputs `username@host > ` as expected.

### conclusion and notes

[this seems to be the offending line](https://github.com/redox-os/ion/blob/e81543bfc389136a355815d3e47e5266adb405b8/src/shell/binary/prompt.rs#L25), so far as i've been able to discern. 

i just wanted to report to make it easier for anyone who's got more experience with this codebase to either point me in the right direction or test it on another macOS machine. my fork has some useful `eprintln!` statements in lieu of my poor debugger skills, if that helps.

**Comment by mmstick** [comment]
I'm pretty sure I know how to fix this, so I will push a commit soon for you to test.

**Comment by covercash2** [comment]
seems to have done it. thanks!

**Comment by covercash2** [comment]
if you don't mind, what is happening here? the solution looks like a more concise version of the same code.

**Comment by mmstick** [comment]
It was never intended for the stdout of function prompts to be expanded. Before, the prompt variable would be set to either the stdout of the function prompt, or the PROMPT variable's contents, and then expanded. Now, only the PROMPT variable is expanded, whereas the function prompt's stdout is left as is.

**Comment by covercash2** [comment]
ah. i see that now

**Comment by covercash2** [comment]
it's fixed on macOS, but now i'm getting `username\@host` on linux

**Comment by mmstick** [comment]
That's #640
