### ISSUE TITLE
test -h prints help when the man page says it tests for a symbolic link

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/ion#653]
**Reproduction**:
```
$ test --help | rg -e "-h" -A 2
    -h FILE
        FILE exists and is a symbolic link (same as -L)
$ test -h /path/to/file
... prints help
```

**Expected behavior**:
Same as `-L`.

**Workaround**:
Use `-L`.

**Build information**:
Starts with d096b4d1eebbe10f227412fed70ef7047e8f630d due to the addition of `check_help`.

**The fix**:

  - Rely on `--help` for showing help text for `test`.

**Comment by mmstick** [comment]
The `test` command should be implemented identically to `test` in other POSIX shells.
