### ISSUE TITLE
ion suspends after finishing job under root login (such as using sudo -i or sudo su)

### ISSUE THREAD

**Issue by Coding-Doctors** [redox-os/ion#656]
**Reproduction**: 
Login to root while on a user account using sudo, run ``sudo -i`` or ``sudo su``, then run any command, short to finish commands preferred (``ls`` for example)

**Expected behavior**: 
ion continues to work following job finishing

**Actual behavior**: 
ion suspends requiring you to bring the job back with something like ``fg`` to return to ion.

**Build information**:
```
$ rustc -V
rustc 1.24.0-nightly (3bee2b44c 2017-12-16)
$ qemu-i386 -version
qemu-i386 version 2.10.1
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
$ uname -a
Linux benjamin-thinkpad-void 4.14.4_1 #1 SMP PREEMPT Tue Dec 5 11:34:28 UTC 2017 x86_64 GNU/Linux
$ ion --version
ion: failed to open "--version": No such file or directory (os error 2)
```
(no clue why version refuses to work, but I'm using 1.0.5)

**Comment by AgustinCB** [comment]
Which revision?

**Comment by mmstick** [comment]
> ion: failed to open "--version": No such file or directory (os error 2)

Seems you are using a very ancient version of Ion, pre-August, from before the time of the `--version` flag. You should be getting this, instead:

```
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 4c2a71fd94f83022e711482eee9c2ee5c1f73506
```

**Comment by Coding-Doctors** [comment]
Its definitely pre-august, 1.0.5 alpha was released in July, I'll compile from source and see if the problem persists.

**Comment by mmstick** [comment]
Closing due to the version being too old.
