### ISSUE TITLE
array_methods example run failed

### ISSUE THREAD

**Issue by Matrix-Zhang** [redox-os/ion#658]
the output is:
```
one one
one twoone
o n e t w o
111 110 101 116 119 111
o n e t w o
ion: lines: invalid array method

ion: reverse: invalid array method

ion: reverse: invalid array method

ion: reverse: invalid array method

```

my ion's version is:
```
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev e81543bfc389136a355815d3e47e5266adb405b8
```

**Comment by AgustinCB** [comment]
I wonder why this wasn't caught by the CI. I'm taking a look, it was probably me anyway.

**Comment by AgustinCB** [comment]
Ehe, you're using an old version of ion. The revision of your executable is before the reverse method was added. Pull, recompile and try again.
