### ISSUE TITLE
Create an examples folder and use it as part of the testing process

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#66]
It would be helpful to have example ion scripts to both help out users and enhance testing. We could have an `examples/` directory with scripts in it. Each script would end with `.ion` and we could also have `.out` files to show the expected output for each script. Once we have this we could easily add an automatic test to run each of these and compare the actual output with the expected output. This type of integrations testing would add much more confidence for me than any amount of unit testing would.

**Comment by polymetric1** [comment]
Good idea. I'll write the scripts. I might try to implement it into cargo test, but I'm not experienced with Rust tests or really Rust in general.

**Comment by skylerberg** [comment]
FYI, I recently changed ion from using `fi` to using `end`.

Here is one example that I have been using. It is a slightly modified version of a file that was in redox for a while:
```
if a == a
  echo true a == a
  if b != b
    echo true b != b
  else
    echo false b != b
    if 3 > 2
      echo true 3 > 2
    else
      echo false 3 > 2
    end
  end
else
  echo false a == a
end
```

As for the testing, I wasn't thinking it would need any Rust code. It could just be something in `.travis.yml` that runs the scripts and makes sure their output it correct. Better yet, we could include a script that runs the scripts and verifies their output, then Travis could just run that script.

Eventually, once ion is more fully featured we can have the scripts verify themselves with something like assertions (could just be if not condition exit(1)).

I can deal with the automated checking part.

**Comment by skylerberg** [comment]
As much as I would prefer to leave low-hanging fruit to newcomers to the project, this is high impact so I am just gonna get it done. I think having examples of ion scripts will do more to help people than just the SYNTAX.md.
