### ISSUE TITLE
History leaks between ion sessions

### ISSUE THREAD

**Issue by ijt** [redox-os/ion#660]
**Reproduction**: [describe how you are able to reproduce ("trigger") this bug/issue.]
Type something in one ion shell for example "echo blerg"
Open another ion session.
Press ctrl-p to get the previous command.

**Expected behavior**: [describe the behavior you would expect the repro to yield.]
No command should appear because there is no previous command in the new session.

**Actual behavior**: [describe the actual behavior, which is presented through the repro.].
"echo blerg" appears.

**Build information**: [output of `rustc -V`, `git rev-parse HEAD`, `qemu-i386 -version`, `uname -a`, `ion --version`, etc.]
rustc 1.22.1 (05e2e1c41 2017-11-22)
Linux issac.c.googlers.com 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev bc49acb6b9555942ba8d568914d61389052e9b2b

**Blocking/related**: [issues or PRs blocking or being related to this issue.]

**Misc**: [optional: for other relevant information that should be known or cannot be described in the other fields.]

------

_If the above does not fit the nature of the issue feel free to modify it._

**Comment by mmstick** [comment]
This is supposed to happen.

**Comment by ijt** [comment]
This is a design flaw. I want to be able to work on distinct things in different sessions and not have them cross-contaminate. Please reconsider!
