### ISSUE TITLE
Pushd doesn't work

### ISSUE THREAD

**Issue by SeanTater** [redox-os/ion#683]
**Reproduction**: Type `pushd SOMEWHERE`

**Expected behavior**: It should show the new directory stack and change the directory.

**Actual behavior**: It doesn't actually change the directory.

**Build information**:
- git commit 08cf7ed1
- rustc 1.25.0-nightly (ae920dcc9 2018-01-22)
- Native mac, not qemu
- Darwin segallag-1d8b53 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
- ion 1.0.0-alpha (x86_64-apple-darwin)
   rev 08cf7ed14096459d6ed2efb962e0435159d5928c

**Comment by SeanTater** [comment]
I was mistaken. `pushd` *does* change directory, but it doesn't update the prompt, which leads to confusion. For example:
```
segallag:~/iredell-2017-11-08# dirs
/Users/segallag/iredell-2017-11-08 /Users/segallag/iredell-2017-11-08/external-resources/fusion/3.1.3
segallag:~/iredell-2017-11-08# pushd
/Users/segallag/iredell-2017-11-08/external-resources/fusion/3.1.3 /Users/segallag/iredell-2017-11-08
segallag:~/iredell-2017-11-08# dirs
/Users/segallag/iredell-2017-11-08/external-resources/fusion/3.1.3 /Users/segallag/iredell-2017-11-08
segallag:~/iredell-2017-11-08# pushd
/Users/segallag/iredell-2017-11-08 /Users/segallag/iredell-2017-11-08/external-resources/fusion/3.1.3
segallag:~/iredell-2017-11-08#
```

**Comment by Sag0Sag0** [comment]
Fixed, I think.
