### ISSUE TITLE
When cd'ing into a directory symlink, the path is replaced the absolute path to the symlinked directory

### ISSUE THREAD

**Issue by forbjok** [redox-os/ion#684]
I don't know whether this is intentional or an unwanted side-effect of the way paths are handled, but when changing into a directory symlink, the original symlinked path is lost and replaced with the absolute path to the symlinked directory.

**Expected behavior**:
The symlinked path being preserved, so that doing `cd ..` in the symlinked directory via the symlink will put you back in the directory containing the symlink.
This is what happens in every other shell I've used. (sh, bash, zsh)

The expected behavior as seen in bash:
![screenshot from 2018-01-27 12-46-43](https://user-images.githubusercontent.com/4687674/35471668-3220f2cc-0360-11e8-8f6a-fd7a06e050bb.png)

**Actual behavior**:
if you `cd` into the symlink and then `cd ..`, you end up in the parent directory of the symlinked directory instead of back in the directory containing the symlink.

This screenshot illustrates it:
![screenshot from 2018-01-27 12-30-57](https://user-images.githubusercontent.com/4687674/35471601-acdddfcc-035e-11e8-926d-5214b1072882.png)

**Build information**:
```
$ rustc -V
rustc 1.25.0-nightly (bacb5c58d 2018-01-26)

$ uname -a
Linux ariana 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux

$ ion --version
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 08cf7ed14096459d6ed2efb962e0435159d5928c
```

**Comment by sourgrasses** [comment]
Hmm, isn't this correct behavior? I would expect changing directory to ../ to take me one branch up the tree with reference to the current directory because ../ belongs to the current directory and not to the shell, and in using a symlink you're jumping to another branch on the tree. This is how fish behaves, anyway, and then you can just use the directory history to `cd -` into the previous directory, which I think is an option on bash and works on ion also.

**Comment by forbjok** [comment]
I can't really say whether or not it's objectively correct or not, just that it differs from the behavior of every other shell I know of, and hence from what I would expect. It also seems less practical than how other shells behave, since when you make a symlink you basically want it to behave as if it was just a regular directory in the location of the symlink and this breaks that behavior.

Also, `cd -` takes you back to the previous directory you were in, not the parent directory, so it will only situationally work. Personally, I often `cd` directly from the user home directory into a directory several nodes in, in which case doing `cd -` afterwards would take me directly back to the user home directory instead of to the parent directory of the one I'm currently in.

**Comment by quartsize** [comment]
(One of) fish's discussions, for reference: https://github.com/fish-shell/fish-shell/issues/3350

I think this is at least not something definitively *wrong* with Ion, just different than how some (most?) other shells work, so it doesn't seem right for this to be tagged as a bug, especially for a shell that's not dedicated to being strictly compatible with those shells.

**Comment by forbjok** [comment]
I implemented a fix for this and opened a pull request.
