### ISSUE TITLE
pushd on current directory

### ISSUE THREAD

**Issue by zen3ger** [redox-os/ion#696]
**Reproduction**:
```sh
zen3ger:~/Projects/ion# pushd .
. /home/zen3ger/Projects/ion
zen3ger:~/Projects/ion# cd ../
ion: failed to set current dir to : No such file or directory (os error 2)
zen3ger:~/Projects/ion# popd
/home/zen3ger/Projects/ion
zen3ger:~/Projects/ion# cd ../
zen3ger:~/Projects/ion# pwd
/home/zen3ger/Projects
```

**Expected behavior**: 
I should be able to push `.` on the dir stack and back up a directory. After `popd` the prompt should show the current directory path.

**Actual behavior**: 
ion fails to execute `cd ../` on `.` directory. After removing `.` from the dir stack with `popd` the prompt freezez and shows the directory name where `popd` got executed.

**Build information**:
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 18b6f5eb4a9a10ca404c9fbd302ab5b216c2f45a

**Comment by Sag0Sag0** [comment]
I'm unsure about the correct way to fix this. Should the `pushd` builtin expand `.` and `..` and if not where should they be expanded?
