### ISSUE TITLE
first pushd does not change directory

### ISSUE THREAD

**Issue by zen3ger** [redox-os/ion#697]
**Reproduction**:
```sh
zen3ger:~/Projects/ion# pushd ~
/home/zen3ger /home/zen3ger/Projects/ion
zen3ger:~/Projects/ion# pwd
/home/zen3ger/Projects/ion
zen3ger:~/Projects/ion# pushd
/home/zen3ger/Projects/ion /home/zen3ger
zen3ger:~/Projects/ion# dirs -v
 0  /home/zen3ger/Projects/ion
 1  /home/zen3ger
zen3ger:~/Projects/ion# pwd
/home/zen3ger/Projects/ion
zen3ger:~/Projects/ion# pushd
/home/zen3ger /home/zen3ger/Projects/ion
zen3ger:~# pwd
/home/zen3ger
zen3ger:~# pushd Documents/
Documents/ /home/zen3ger /home/zen3ger/Projects/ion
zen3ger:~# pwd
/home/zen3ger
zen3ger:~# pushd
/home/zen3ger Documents/ /home/zen3ger/Projects/ion
zen3ger:~# pushd
Documents/ /home/zen3ger /home/zen3ger/Projects/ion
zen3ger:~/Documents# pwd
/home/zen3ger/Documents
```

**Expected behavior**:
ion changes directory on first `pushd $NEW_DIR` to `$NEW_DIR`

**Actual behavior**:
After `pushd $NEW_DIR` ion stays at the same directory. When I try to flip the directory order of the 0th and 1st entry with `pushd` it takes two cycles to actually get to the `$NEW_DIR` I've intended to go to.
It seems like after `pushd $NEW_DIR` results in the correct dir stack order of:
0 - NEW_DIR
1 - OLD_DIR
but the `cd $NEW_DIR` never happens when argument is passed to `pushd`.

**Build information**: 
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 18b6f5eb4a9a10ca404c9fbd302ab5b216c2f45a

**Blocking/related**:
#696

**Comment by Sag0Sag0** [comment]
Fixed.

**Comment by zen3ger** [comment]
Should I close this one?

**Comment by Sag0Sag0** [comment]
Yes.
