### ISSUE TITLE
Let Command

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#7]
Instead of having a special case for the user typing `$` and displaying the environment variables, we should use a dedicated command `set` command like fish does. Adding this command will get rid of two special cases: `$` and `KEY=VALUE` which make the current implementation clunkier and less discoverable (there is no help for these actions).

I am posting this here as a note to remind myself to do this soon and let others know part of what I am working on. It is a little too late tonight to bite this off.

**Comment by hauleth** [comment]
I would prefer `let` instead of `set`, but maybe it my personal preference. It could be even: `let VARNAME = VALUE`.

**Comment by mgattozzi** [comment]
I'm more of a let kind of guy, mostly since my job involves Haskell. Rust also uses let, but in the case of the average user set would be all right

**Comment by Ticki** [comment]
I'm for let too.

**Comment by skylerberg** [comment]
`let` it will be then.

**Comment by skylerberg** [comment]
Closed by https://github.com/redox-os/ion/pull/51.
