### ISSUE TITLE
Support user defined functions in ion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#70]
I think we should do functions differently than other shells. I think they should be able to have a set number of arguments like a normal scripting language.

The first step toward this that I want to implement is zero argument functions. These will basically be like aliases. Like Fish, I don't think ion needs aliases when functions can do the job.

**Comment by nounoursheureux** [comment]
We should define the syntax for the functions. We could do something like this:
```
<function_keyword> function_name arg0 arg1
    echo $arg0
end
```
Or like this:
```
<function_keyword> function_name arg0 arg1 {
    echo $arg0
end
```
(See #99 for curly braces versus begin...end blocks)

The keyword could be `function`, `fn`, `def`, ...      
What do you think ?

**Comment by skylerberg** [comment]
@nounoursheureux I like the first one. I am not picky on the keyword, but I like `fn` because it is less typing than function without any harm to readability in my opinion (everyone knows what `fn` is). I am excited to have functions that actually have named parameters in a shell language finally.

**Comment by nounoursheureux** [comment]
@skylerberg so the function would be defined like this:
```
fn function_name arg0 arg1
    echo $arg0
end
```
And called like this:
```
function_name arg0="foo" arg1="bar"
```
@Ticki @jackpot51 are you OK with this ?

**Comment by nounoursheureux** [comment]
I think we can close this
