### ISSUE TITLE
POSIX compliant?

### ISSUE THREAD

**Issue by polarathene** [redox-os/ion#704]
Will ion be able to be used as `/bin/sh` like dash?

This didn't seem to be clear on the README and I didn't see any issues stand out to clarify it. I did notice the comparison to being faster than dash.

I saw a simple command to compare dash and bash performance, this works for zsh as well but I didn't have luck with ion. Is it a bug or something to do with ion's goals where it will not be supported?

```
$ time ion -c 'for i in $(seq 1 1000000);do [ 1 = 1 ];done'
ion: unexpected end of arguments: expected end block for `For { .. }`

real    0m0.004s
user    0m0.003s
sys     0m0.002s
```

Expected output is the same minus the error, the values given would be higher, here is dash:

```
$ time dash -c 'for i in $(seq 1 1000000);do [ 1 = 1 ];done'

real    0m0.748s
user    0m0.708s
sys     0m0.021s
```

**Comment by mmstick** [comment]
It's in large, bold text: https://doc.redox-os.org/ion-manual/#Why%20Not%20POSIX?

**Comment by polarathene** [comment]
> It's in large, bold text: https://doc.redox-os.org/ion-manual/#Why%20Not%20POSIX?

Thank you for the link. As stated, when finding this project repo on Github, the README.md does not mention anything about POSIX. Others can discover this issue if they come across ion in the same way.
