### ISSUE TITLE
Asterisk tilde (*~) acts as asterisk space tilde (* ~)

### ISSUE THREAD

**Issue by kirch7** [redox-os/ion#708]
**Reproduction**: Suppose you are in a directory `$HOME/IC/superboids/`. In this directory there are some files endding in tilde (e.g. `pineapple.sh~`). Now you want to remove theses files using `rm`.

**Expected behavior**:
`rm *~` should remove all files in the current directory whose names end in tilde.
```
kirch:~/IC/superboids# ls
b	   lines.py   Makefile	     onion.py	   pineapple.sh~  video2types_.gp  video.gp	 video.py	virtuais3.avi
lines.dat  lines.py~  Miniboid.cpp~  pineapple.sh  progress.txt   video2types.gp   video_inf.gp  virtuais2.avi	virtuais.avi
```
```
kirch:~/IC/superboids# rm *~
```
```
kirch:~/IC/superboids# ls
b	   lines.py   Makefile	     onion.py	   video2types_.gp  video.gp	 video.py	virtuais3.avi
lines.dat  pineapple.sh  progress.txt   video2types.gp   video_inf.gp  virtuais2.avi	virtuais.avi
```

**Actual behavior**:
`rm *~` actually acts as `rm * ~`.
```
kirch:~/IC/superboids# ls
b	   lines.py   Makefile	     onion.py	   pineapple.sh~  video2types_.gp  video.gp	 video.py	virtuais3.avi
lines.dat  lines.py~  Miniboid.cpp~  pineapple.sh  progress.txt   video2types.gp   video_inf.gp  virtuais2.avi	virtuais.avi
```
```
kirch:~/IC/superboids# rm *~
rm: cannot remove '.git': Is a directory
rm: cannot remove 'b': Is a directory
rm: cannot remove '/home/kirch': Is a directory
```
```
kirch:~/IC/superboids# ls
b
```

**Build information**:
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 96d5b5d2ef53d8d9e93a4a41019560175cc12598

**Related**:
https://github.com/redox-os/ion/issues/406
https://github.com/redox-os/ion/pull/407

**Misc**: I had similar problems with `ls`. I had backup, there was no huge problem.

**Comment by ishanjain28** [comment]
This is a bug related to #709 and it has been fixed in PR #710
