### ISSUE TITLE
Add tilde expansion

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#72]
Here is how bash does it https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html.

I would like to discuss what parts of this we should also do. Let me know what you think.

**Comment by mmstick** [comment]
At the very least, we should implement the minimum functionality of ~. I've just uploaded a pull request which implements the `$HOME` variable, so we should be able to just expand ~ to $HOME's value when it is detected.

**Comment by skylerberg** [comment]
One thing we need to make sure is that tilde expansion happens during variable assignment. We also need to make sure that we respect quoting when doing tilde expansion. I will raise these as separate issues if need be.

**Comment by skylerberg** [comment]
https://github.com/redox-os/ion/pull/154
