### ISSUE TITLE
running `ls` gives `ion: waitpid error: Invalid argument` and messes up newlines

### ISSUE THREAD

**Issue by wilem82** [redox-os/ion#723]
**Reproduction**: build ion manually as described in the docs, cargo install, run ion, run ls

**Expected behavior**: not give the error and print newlines properly

**Actual behavior**: running `ls` gives `ion: waitpid error: Invalid argument` and messes up newlines

**Build information**:
rustc 1.27.0-nightly (79252ff4e 2018-04-29)

Linux DESKTOP-OL0Q75O 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 74bbb9ed4a08a3459343f434af9f633f3111adc3

**Misc**:

running openssh-server in the WSL (Debian 9), connecting through ssh using ZOC Terminal, so it's not a cmd.exe environment.

**Comment by mmstick** [comment]
You may want to file this issue with Microsoft.
