### ISSUE TITLE
Arguments passed incorrectly to recursively called functions

### ISSUE THREAD

**Issue by xTibor** [redox-os/ion#728]
**Reproduction**:
```
fn recursive a b c d
    echo $a $b $c $d
    sleep 1
    recursive $d $a $b $c
end

recursive 1 2 3 4
```

**Expected behavior**:
```
1 2 3 4
4 1 2 3
3 4 1 2
2 3 4 1
1 2 3 4
...
```

**Actual behavior**:
```
1 2 3 4
4 4 4 4
4 4 4 4
4 4 4 4
4 4 4 4
...
```

**Build information**: 
`rustc -V`: `rustc 1.28.0-nightly (952f344cd 2018-05-18)`
`git rev-parse HEAD`: 017d807566560684cec6d2ee79dd8775ed5a24b0
System: KDE neon 5.12 (Ubuntu 16.04)

**Comment by BafDyce** [comment]
If, instead of moving `$d` to the front one moves the `$a` to the back another strange thing happens:

```
fn recursive a b c d
    echo $a $b $c $d
    sleep 1
    recursive $b $c $d $a
end

recursive 1 2 3 4
```

leads to

```
1 2 3 4
2 3 4 2
3 4 2 3
4 2 3 4
2 3 4 2
3 4 2 3
```

expected would be:

```
1 2 3 4
2 3 4 1
3 4 1 2
4 1 2 3
1 2 3 4
...
```

Unfortunately, I have no idea where to look for the source of this bug.

**Comment by niluxv** [comment]
This doesn't only happen to recursive functions:
```
fn not_recursive_fn a b c d
    echo $a $b $c $d
    echo_fn $d $a $b $c
end

fn echo_fn a b c d
    echo $a $b $c $d
end

not_recursive_fn 1 2 3 4
```
also outputs:
```
1 2 3 4
4 4 4 4
```

**Comment by mmstick** [comment]
@niluxv That should make it easier to figure out what's happening.

**Comment by jD91mZM2** [comment]
Since variables are global, it seems like the function argument `a` does `a=$d`, and then `b` does `b=$a`, and then `c=$b` etc, resulting in 4 4 4 4. Would be fixed by cloning the necessary parameters so they don't get overwritten.

**Comment by jD91mZM2** [comment]
For anybody wanting to fix this, the issue lies [here](https://github.com/redox-os/ion/blob/master/src/lib/shell/flow_control.rs#L192-L202). It's pushing stuff to variables_backup and overwriting the original. But then `value_check` is reading this newly set variable instead of the backup. What you need to do is make sure the values are evaluated before anything is overwritten.

**Comment by niluxv** [comment]
Fixed it. @jD91mZM2 thank you.
I will create a pull request tomorrow.

**Comment by stratact** [comment]
@niluxv you need to submit that pull request to our gitlab server, if you can.

**Comment by mmstick** [comment]
It's looking good now, with the initial scopes in place.

```
/~ # fn recursive a b c d
    echo $a $b $c $d
    sleep 1
    recursive $b $c $d $a
    end
/~ # recursive 1 2 3 4
1 2 3 4
2 3 4 1
3 4 1 2
4 1 2 3
1 2 3 4
2 3 4 1
3 4 1 2
4 1 2 3
1 2 3 4
```
