### ISSUE TITLE
tab completion broken, eats all ram 

### ISSUE THREAD

**Issue by matthiaskrgr** [redox-os/ion#738]
ion 1.0.0-alpha (x86_64-unknown-linux-gnu)
rev 301c8170bb9938e9516eae4eca5eb9f4d11da94b

rustc 1.28.0-nightly (990d8aa74 2018-05-25)

Linux t470 4.17.0-1-MANJARO #1 SMP PREEMPT Fri May 25 07:25:58 UTC 2018 x86_64 GNU/Linux

typing simple paths like  ````"/h/m<tab>"```` (for /home/matthias) causes ion shell to eat all the ram on my system before it's OOM-killed.

**Comment by stratact** [comment]
This bug might be fixed with this revision 292b7372d7f53f1ce6658dd2a0c5eb5087f613e8. Have you tried the newer revisions?

**Comment by matthiaskrgr** [comment]
Ah yes. I just updated and it looks good. Sorry for the noise :/
