### ISSUE TITLE
$(^) Parsing Bug

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#761]
The following command will hang the ion shell:

```
whois $(dig gitlab.com | grep ^gitlab.com)
```

Unsure at this time as to the cause. Either the parser or job execution

**Comment by emturner** [comment]
@mmstick so I've done some more digging, the issue now seems like job execution?
The command ```$(a | sleep 2)``` hangs.  If you execute ```a | sleep 2``` you get ```command not found: a``` and then the shell hangs, though ```CTRL+C``` works.  

 So seems like the subprocess isn't registring ```CTRL+C``` after an error in the pipeline?

**Comment by mmstick** [comment]
`a` should exit due to not being found (thus becoming a zombie process), and sleep should exit after 2 seconds (and becoming a zombie process), in which the foreground waitpid event loop should then immediately reap both of them and continue.

**Comment by emturner** [comment]
yeah, so the hanging (when it does occur) is due to ```waitpid``` blocking - so presumably the processes aren't signalling exit status correctly

interestingly, ```CTRL+C``` on ````sleep 2``` matches ```errno()```, while the same on ```a | sleep 2``` matches ```WIFSIGNALED(status)```

**Comment by emturner** [comment]
Have discovered that setting ```pgid = current_pid - 1``` seems to fix ```a | echo 1``` - looking into why
