### ISSUE TITLE
Names '...', '....' etc. are not supported for aliases/functions

### ISSUE THREAD

**Issue by myfreeweb** [redox-os/ion#770]
Ion says "alias name is invalid" for the following:

```bash
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
```

And "not a valid function name" for functions with the same names.

The first one is handled by implicit cd, but I want to have the other ones too...

**Comment by mmstick** [comment]
I guess we can add `.` to the list of acceptable characters in an alias.
