### ISSUE TITLE
Use an auto-changlog tool such as clog

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#79]
https://github.com/clog-tool/clog-cli

**Comment by skylerberg** [comment]
I hope these tools don't require every commit to follow the format. I would like to adopt as a convention that all the formatted commit messages should go in merge commit messages. That way, whenever someone makes a change I can look over it and figure out what it changes. I don't like the idea that every commit has something that should go into the changelog because that discourages committing often.

**Comment by Ticki** [comment]
I've never been a fan of the formatting of commit messages in `clog`. The idea is great, though!

**Comment by polymetric1** [comment]
I think it should register only when you prefix a commit with something, like `[clog]`

**Comment by skylerberg** [comment]
I am going to close this. I don't think a change log will be helpful unless we have a user base that is not expecting breaking changes.
