### ISSUE TITLE
Catch signals

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#85]
Ion should not die when it catches a signal such as you get when you hit `^C`. Instead we should handle the signal.

We may have some trouble because as far as I can tell, Rust does not have a great way to deal with signals. https://github.com/rust-lang/rfcs/issues/1368.

**Comment by mmstick** [comment]
Referencing the Redox issue here. https://github.com/redox-os/redox/issues/585

Once Redox has support for signals, we can implement it here.

**Comment by mmstick** [comment]
Basic SIGINT handling is now implemented.

**Comment by mmstick** [comment]
SIGINT handling now aborts control flow logic when a signal is detected.
