### ISSUE TITLE
Add noop command

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#87]
Most shells have a command called `:` that is a noop. We should add this to ion. It can either be called `:` or `noop`; I don't care which, but if anyone does, just say your opinion.

**Comment by polymetric1** [comment]
I think it should be `noop`, here's why:
We chose variable binding to be `let variable=value` over `variable=value`, using keywords over operators is more readable and it's just more consistent. A good example of what not to do, C# uses `in` in `foreach` and java uses `:` in its equivalent of that loop type, yet it uses `extends` for class heirarchy and C# uses `:`. Both those language features are inconsistent, and they're basically just swapped.

**Comment by skylerberg** [comment]
Agreed. Also, it is easier to guess what `noop` does than what `:` does.

**Comment by mmstick** [comment]
Is there even a point to having a `noop` command when it's effectively just going to be an alias of `true`?

**Comment by jackpot51** [comment]
I agree, `:` is just `true`, so this is already complete

If there is a use case for a noop that doesn't set the exit status to 0 (which is the only thing true does), I can't see it

**Comment by skylerberg** [comment]
We do not have a builtin true. We should probably have one so that if someone is doing a massive loop with a noop it doesn't spawn a process.

**Comment by mmstick** [comment]
We now have a builtin true and false, but it's not very useful right now because if does not accept single arguments as input, and the while loop construct doesn't exist.

**Comment by skylerberg** [comment]
Thanks for adding this! Closing.
