### ISSUE TITLE
Add command line options to dirs, pushd, popd

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#88]
https://www.gnu.org/software/bash/manual/html_node/Directory-Stack-Builtins.html

**Comment by memoryleak47** [comment]
Please keep in mind, that the command line options for dirs and pushd are not yet implemented, So closing this issue may be a little overhasty.
I can follow up implementing them, though.
Btw. do you have a formatting standard? it does not seem to be rustfmt.

**Comment by mmstick** [comment]
@memoryleak47 There is no formatting standard for Ion as of yet. Rustfmt will be used eventually though.
