### ISSUE TITLE
Use nom for parsing

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#9]
https://github.com/Geal/nom

**Comment by Ticki** [comment]
Isn't nom overkill in this case? I mean, we could probably yield a better performance by using a custom parser.

**Comment by hauleth** [comment]
I think not. Do not write code that someone has written for you, in that case you can't screw it.

**Comment by polymetric1** [comment]
I agree. Nom is fine for this situation. It's just a parser, think of it like yacc or bison in the C world. Those are used for things all the way from search query parsers to language compilers.

**Comment by mgattozzi** [comment]
It's much easier to use someone elses code that's written for a specific purpose. Why reinvent the wheel?

**Comment by Ticki** [comment]
Generally, shell parsing is no hard task. Just a LL(k) parser.

**Comment by Ticki** [comment]
Anyways, `nom` is pretty fast and convenient.

**Comment by hauleth** [comment]
> Generally, shell parsing is no hard task. Just a LL(k) parser.

Tell that bash developers after ShellShock.

**Comment by Ticki** [comment]
GNU Bash parser was horrible written. And it wasn't even by hand1

**Comment by skylerberg** [comment]
I just looked at `nom` again. It looks like they are adding features to parse in a string-oriented rather than byte oriented way. This seems like a critical feature for us. That said, it doesn't appear done. Most of the macros do not have a string oriented version. For now I am going to add features to my parser instead of changing to `nom`. That said, my parser was quickly thrown together and should not stick around forever. If someone else wants to switch to `nom`, another crate, or write a new parser, I would be very happy. Otherwise, I will keep on with mine for a little while and replace it sometime in the future.

**Comment by Ticki** [comment]
What's wrong with being byte oriented?

**Comment by skylerberg** [comment]
Ion, as a language should be based on utf-8 encoding, right? If this is the case, going byte by byte seems like it would complicate the parsing logic. After parsing we would want to switch everything to `&str` and then everything would be `Option`s. Of course, I guess we could just convert to `&str` and abort with a parse error if it doesn't work. If you don't think it will be a big problem being byte oriented, I will take another look.

**Comment by skylerberg** [comment]
I chatted a little on `nom`'s gitter and I guess I was wrong about the string thing. That said, I just spent the past couple of hours trying to get it to work and I encountered more baffling errors than anything I have seen before.

This is not the first time that I have tried to use `nom`, I have really wanted us to have a parser built on a better foundation. I have tried several times and each time I have come away with nothing. I am throwing in the towel. Either I or `nom` is not up for the task. If someone else want to take the mantle on this and creates a parser with similar capabilities to what we have without `nom`, then I will be thrilled.

Until then, I am going to follow a different plan. I will add some more features to my janky parser and start thinking about how I can refactor it to be less janky.

**Comment by skylerberg** [comment]
Since I have switched to a parser generator called `rust-peg`, I don't think this is relevant anymore.

**Comment by Ticki** [comment]
Good work, @skylerberg!

**Comment by munyari** [comment]
Is there still any will to consider nom? What are the advantages and disadvantages of using nom as compared to peg?

**Comment by skylerberg** [comment]
@munyari Sure we could consider nom, but I don't see any practical advantage. IMO peg is much easier to use and shows the grammar in a representation that is more independent of the implementation. I think switching to nom would be the result of bike shedding and a waste of implementation effort.

**Comment by skylerberg** [comment]
No apologies required, it is fine to continue a discussion here.

I have not reviewed the code for peg, but it is most likely possible to do it zero-copy because it mostly just returns you views into a string, which I am guessing is the original. However, our code does copy strings in some places for ease of implementation. It is much easy to pass around an owned string than deal with lifetime issues  throughout the entire program. This is unlikely to be the performance bottleneck and would be a premature optimization to handle. For the effort required to change the code and deal with it all being zero-copy we would need to show that copying in the parser was having a real world impact.

I looked at LARLPOP briefly before using peg, but I never used it. I decided to go with rust peg because it is much more expressive than an LR(1) parser, which is what LARLPOP is.

**Comment by munyari** [comment]
Awesome, thanks for discussing that with me!

**Comment by munyari** [comment]
I would also tend to agree with you. I've been building a shell which I think may eventually implement the POSIX shell spec. In that respect, nom's lack of recursive grammar definitions is a huge pain. I may look to a tool like PEG in the future.

**Comment by skylerberg** [comment]
I would recommend PEG, but you would want to read up on how it differs from BNF because though it looks similar, it actually has some major differences (e.g., the ordering of rules matters). I would also recommend doing some of the expansions as part of a lexing phase before parsing with your grammar for a posix shell.
