### ISSUE TITLE
Getting ion works under windows

### ISSUE THREAD

**Issue by lygstate** [redox-os/ion#91]

**Comment by Ticki** [comment]
Most of us are Linux users, so ability to test it can be a little hard. I think @polymetric1 is a Windows user, though.

**Comment by lygstate** [comment]
I am also a Windows user, indeed, bash have a very bad experience on windows, I hope ion would change the situation.

**Comment by lygstate** [comment]
Does ion depends on the fork api of POSIX?

**Comment by Ticki** [comment]
No, it does not. It has very few dependencies due to the ability to run on Redox.

**Comment by lygstate** [comment]
Then I may try to port it to windows, I am very familiar with Win32 API.

**Comment by Ticki** [comment]
Well, sure thing. It shouldn't be very hard to get it runnin' on Windows!

**Comment by skylerberg** [comment]
Not having the ability to test on Windows myself, I would be interested to hear what difficulties there are.

**Comment by jackpot51** [comment]
I thought it already was working on Windows, could you post any vidence it does not?

**Comment by skylerberg** [comment]
I am closing this for now and will open new issues when we have incompatibilities that are specific. For example, as part of implementing piping I am going to break windows compatibility and at that time I will open an issue for it.

**Comment by smarts** [comment]
see #285
