### ISSUE TITLE
How to calling external ion shell scripts?

### ISSUE THREAD

**Issue by lygstate** [redox-os/ion#93]
How to calling a function in a external scripts?

**Comment by skylerberg** [comment]
I am not sure I understand the question. Ion does not have functions yet, so there is no way to call functions. External scripts can be run the same way that they can on other systems, e.g. `./script.ion`. To make ion run the script you should have a shebang at the beginning of the script, .e.g. `#!/path/to/ion`.

**Comment by skylerberg** [comment]
I am closing this for now, but I welcome a response and will reopen if I missed anything.
