### ISSUE TITLE
Add builtin document/ planned implemented builtin .

### ISSUE THREAD

**Issue by lygstate** [redox-os/ion#94]

**Comment by Ticki** [comment]
I'm not sure what you mean, can you elaborate on this?

**Comment by lygstate** [comment]
For example,
cd
pushd
popd

**Comment by stratact** [comment]
Well, we already have those specific commands builtin, so are you suggesting we list the completed ones in the README.md and add what else we haven't implemented yet? Although I think we covered all the builtin commands that we wanted to implement.

**Comment by lygstate** [comment]
@stratact It's should at somewhere named builtin.md or spec.md

**Comment by skylerberg** [comment]
Having some more documentation would be great. Right now, you can get a list of all builtins by running ion and typeing `help`.

**Comment by polymetric1** [comment]
Oh, I see what he means, like what I did with coreutils. I'd rename this to "Document complete and incomplete builtins" or something.
