### ISSUE TITLE
Curly braces or if...end blocks ?

### ISSUE THREAD

**Issue by nounoursheureux** [redox-os/ion#99]
The current syntax use if...end blocks, but the proposed syntax uses curly braces. I think we should decide now which syntax we want to use. In my opinion the curly braces would have a more Rust-like feel, and the if...end blocks feel more like other shells (Bash for example). So, what do you think ?

**Comment by Ticki** [comment]
I prefer curly braces, due two the fact that they are more readable. On the concerns of interactive sessions: You could have `end` as a command closing all delimiters.

**Comment by nounoursheureux** [comment]
I agree that `end` would be nice for interactive sessions, but it would be really weird in scripts as you would have opening braces with no closing braces.

**Comment by Ticki** [comment]
Maybe go so far and deny scripts using it?

**Comment by skylerberg** [comment]
I don't think we should use curly braces.

First, being Rust-like should not be a goal. Rust is a great systems language, it would be an awful shell language. It's main goals are to be safe, concurrent, and high performance. None of these are particularly important in a shell language. In a shell language We need to favor interactivity. Favoring interactivity is something that is not really important for any other type of language, so you get a radically different design.

Second, I disagree that curly braces are more readable. In non-interactive scripts, indentation should be the main way to distinguish code blocks. Many people psuedo-code this way. Not to mention languages like Python and Ruby do not suffer from a readability problem that curly braces would help. Python is known for being one of the most readable languages or all time.

Third, I don't like the idea of having much stuff that is only or generally only used interactively or in scripts. We will probably have to do a bit of this, but I would like to keep just one language across interactive sessions and script files.

**Comment by jackpot51** [comment]
I also don't think we should use curly braces. It isn't very script-like, and many users will be coming from bash and will not expect that syntax

**Comment by skylerberg** [comment]
Syntax is updated to not have curly braces. https://github.com/redox-os/ion/pull/100.
